(()=>{
const out=document.getElementById('terminalOut'),input=document.getElementById('commandInput'),right=document.getElementById('rightBody'),rightTitle=document.getElementById('rightTitle'),returnBtn=document.getElementById('returnStageBtn');
let stage=null,startAt=0,finishAt=0,timer=null,controls=new Set(),controlCount=0,cmdHistory=[],histPos=0,finished=false,sim=null,lastCommand=null,lastCommandAt=null,lastControl=null,lastControlAt=null,stableSince=null;
let debugLogEnabled=true,debugLog=[],debugLogNextSample=5,debugLogLastSafe=null;
function logTime(){return stage&&sim?sim.simTime:0}
function debugLogAdd(text,t=logTime()){if(!debugLogEnabled)return;debugLog.push(`[${t.toFixed(1).padStart(6)}] ${text}`)}
function debugSnapshot(){if(!stage||!sim)return;debugLogAdd(`SNAPSHOT SAFE=${baseSafeState()?'YES':'NO'} STABLE=${stableFor().toFixed(1)}s | ${debugExtra().join(' | ')}`)}
function debugSampleDue(){if(!debugLogEnabled||!stage||!sim)return;while(sim.simTime>=debugLogNextSample){debugLogAdd(`SNAPSHOT SAFE=${baseSafeState()?'YES':'NO'} STABLE=${stableFor().toFixed(1)}s | ${debugExtra().join(' | ')}`,debugLogNextSample);debugLogNextSample+=5}}
const p=(t='',c='')=>{const d=document.createElement('div');d.textContent=t;if(c)d.className=c;out.appendChild(d);out.scrollTop=out.scrollHeight;if(debugLogEnabled&&stage&&t&&(t.startsWith('AUTO ACTION:')||t.startsWith('INTERLOCK:')||t.startsWith('COMMAND ACCEPTED:')||t.startsWith('COMMAND REJECTED:')||t.startsWith('RPS:')||t.startsWith('RCP-A:')))debugLogAdd(`EVENT ${t}`)};
const block=(a,c='')=>p(a.join('\n'),c);
const elapsed=()=>stage?Math.floor(((finished&&finishAt)?finishAt:Date.now())-startAt)/1000:0;
const elapsedPrecise=()=>stage?(((finished&&finishAt)?finishAt:Date.now())-startAt)/1000:0;
const fmtTime=v=>v===null?'--':v.toFixed(1)+' s';
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const approach=(v,target,rate,dt)=>v<target?Math.min(target,v+rate*dt):Math.max(target,v-rate*dt);
function insert(cmd){input.value=cmd;input.focus();input.setSelectionRange(input.value.length,input.value.length)}
function decayHeat(seconds){const pts=[[0,6.5],[60,4.0],[300,2.8],[600,2.3],[1800,1.8]];for(let i=1;i<pts.length;i++){if(seconds<=pts[i][0]){const [t0,v0]=pts[i-1],[t1,v1]=pts[i];const q=(seconds-t0)/(t1-t0);return v0+(v1-v0)*q}}return 1.8}
function flowFromFrv(pos){if(pos<=10)return pos*2.5;if(pos<=25)return 25+(pos-10)*(35/15);if(pos<=50)return 60+(pos-25)*(40/25);return Math.min(105,100+(pos-50)*0.5)}
function initialSim(id){const tripped=[3,5,6,8].includes(id);return {
  lastTick:Date.now(),simTime:0,reactorTripped:tripped,reactorTripAt:tripped?0:null,turbineTripped:[3,5,6,8].includes(id),
  rcpA:{state:'RUNNING',speed:id===8?100:97,flow:id===8?100:95,vib:id===8?1.0:1.8,bearing:id===8?70:75,stopAt:null},
  s1:{thermalRisk:0.18,rcsTemp:320},
  s2:{frvCmd:'AUTO',frvActual:48,fw:95,sg:56,steam:100,trend:0,recoveryAt:null},
  s3:{sgPressure:7.35,sgLevel:46,sgTrend:0,afwFlow:35,steamDumpCmd:'AUTO',steamDumpActual:30,rcsTemp:320},
  s4:{condenser:12,steamDumpCmd:'AUTO',steamDumpActual:0,steamDumpFlow:0,atmCmd:'STANDBY',atmActual:0,atmFlow:0,afwFlow:0,sgPressure:6.9,sgLevel:56,sgTrend:0,rcsTemp:320,tripReported:false},
  s5:{offsite:0,busA:0,busB:0,edgA:{state:'CRANKING',speed:0,breakerCmd:'AUTO',breaker:'OPEN'},edgB:{state:'CRANKING',speed:0,breakerCmd:'AUTO',breaker:'OPEN',closeAt:null},rcsTemp:318},
  s6:{mfw:0,afwA:100,afwB:0,afwC:100,afwBPump:'RUNNING',afwValveCmd:'CLOSED',afwValveActual:0,sgA:55,sgB:55,sgC:55,sgTrend:0,rcsTemp:318},
  s7:{trueLevel:54.5,ch1:18,ch2:54.8,ch3:54.1},
  s8:{decayHeat:6.5,rcsTemp:320,rcsTrend:0,sgLevel:55},
  history:{nextSample:10,data:{}}
}}
function pushHist(key,t,v){const a=sim.history.data[key]||(sim.history.data[key]=[]);a.push({t,v});if(a.length>18)a.shift()}
function seedHistory(id){const seed=(key,arr)=>arr.forEach(([t,v])=>pushHist(key,t,v));
 if(id===1){seed('RCP-A FLOW',[[-300,100],[-240,99],[-180,98],[-120,96],[-60,95]]);seed('RCP-A VIBRATION',[[-300,1.1],[-240,1.3],[-180,1.5],[-120,1.7],[-60,1.8]]);seed('RCP-A SPEED',[[-300,100],[-240,99],[-180,98],[-120,97],[-60,97]])}
 if(id===2){seed('SG-B LEVEL',[[-240,60],[-180,59],[-120,58],[-60,57],[0,56]]);seed('FRV-B POSITION',[[-240,52],[-180,51],[-120,50],[-60,49],[0,48]])}
 if(id===4)seed('CONDENSER PRESSURE',[[-180,7],[-120,9],[-60,11],[0,12]]);
 if(id===5)seed('BUS-B VOLTAGE',[[-20,100],[-10,0],[0,0]]);
 if(id===6)seed('AFW-B FLOW',[[-60,0],[-30,0],[0,0]]);
 if(id===7){seed('SG-B-LVL-CH1 LEVEL',[[-180,54],[-120,18],[-60,18],[0,18]]);seed('SG-B-LVL-CH2 LEVEL',[[-180,56],[-120,55],[-60,54.8],[0,54.8]])}
}
function sampleHistory(t){if(stage.id===1){pushHist('RCP-A FLOW',t,sim.rcpA.flow);pushHist('RCP-A VIBRATION',t,sim.rcpA.vib);pushHist('RCP-A SPEED',t,sim.rcpA.speed)}
 if(stage.id===2){pushHist('SG-B LEVEL',t,sim.s2.sg);pushHist('FRV-B POSITION',t,sim.s2.frvActual)}
 if(stage.id===4)pushHist('CONDENSER PRESSURE',t,sim.s4.condenser);
 if(stage.id===5)pushHist('BUS-B VOLTAGE',t,sim.s5.busB);
 if(stage.id===6)pushHist('AFW-B FLOW',t,sim.s6.afwB);
 if(stage.id===7){pushHist('SG-B-LVL-CH1 LEVEL',t,sim.s7.ch1);pushHist('SG-B-LVL-CH2 LEVEL',t,sim.s7.ch2)}
}
function showSelect(){stage=null;finished=false;finishAt=0;sim=null;stableSince=null;controlCount=0;lastCommand=null;lastCommandAt=null;lastControl=null;lastControlAt=null;if(timer)clearInterval(timer);returnBtn.classList.add('hidden');rightTitle.textContent='STAGE SELECT';right.className='right-body';right.innerHTML='<div class="stage-select-head"><div><h1>SELECT STAGE</h1></div></div><div id="stageGrid" class="stage-grid"></div>';const grid=right.querySelector('#stageGrid');STAGES.forEach(s=>{const d=document.createElement('div');d.className='stage-card';d.innerHTML=`<h3>STAGE-${s.id}</h3><button>START</button>`;d.querySelector('button').onclick=()=>startStage(s);grid.appendChild(d)});out.innerHTML='';p('TERMINAL READY');p('SELECT A STAGE FROM THE RIGHT PANEL.');}
function startStage(s){stage=s;startAt=Date.now();finishAt=0;finished=false;controls=new Set();controlCount=0;stableSince=null;lastCommand=null;lastCommandAt=null;lastControl=null;lastControlAt=null;sim=initialSim(s.id);seedHistory(s.id);debugLog=[];debugLogNextSample=5;debugLogLastSafe=baseSafeState();debugLogAdd(`STAGE-${s.id} START`);out.innerHTML='';returnBtn.classList.remove('hidden');rightTitle.textContent=`OPERATING & MAINTENANCE MANUAL // STAGE-${s.id}`;Manual.render(right,insert,'cover');p('!! EVENT !!','alarm');p('');p(`STAGE-${s.id} INITIALIZED`);p(s.brief,'alarm');p('');if(timer)clearInterval(timer);timer=setInterval(tick,1000);}
function tripReactor(){if(!sim.reactorTripped){sim.reactorTripped=true;sim.reactorTripAt=sim.simTime}}
function updateRcpA(dt,mode){const r=sim.rcpA;
 if(r.state==='RUNNING'){if(mode==='DEGRADE'){r.speed=clamp(r.speed-.06*dt,68,100);r.flow=clamp(r.flow-.085*dt,55,100);r.vib=clamp(r.vib+.007*dt,1,4.5);r.bearing=clamp(r.bearing+.045*dt,70,94)}}
 else if(r.state==='COASTDOWN'){r.speed=clamp(r.speed-7*dt,0,100);r.flow=clamp(Math.max(8,r.speed),8,100);r.vib=clamp(r.vib-.08*dt,1.0,4.5);r.bearing=clamp(r.bearing-.10*dt,68,94);if(r.speed<=1){r.speed=0;r.flow=8;r.state='STOPPED'}}
 else if(r.state==='STOPPED'){r.vib=clamp(r.vib-.03*dt,1.0,4.5);r.bearing=clamp(r.bearing-.08*dt,68,94)}
 else if(r.state==='STARTING'){r.speed=clamp(r.speed+10*dt,0,100);r.flow=clamp(Math.max(8,r.speed),8,100);r.vib=approach(r.vib,1.0,.08,dt);r.bearing=approach(r.bearing,70,.08,dt);if(r.speed>=99){r.speed=100;r.flow=100;r.state='RUNNING'}}
}
function advanceStep(dt){sim.simTime+=dt;const t=sim.simTime;
 if(stage.id===1){updateRcpA(dt,'DEGRADE');const r=sim.rcpA,s=sim.s1;if(!sim.reactorTripped&&r.flow<75){tripReactor();p('AUTO ACTION: RPS REACTOR TRIP — PRIMARY FLOW VERY LOW','alarm')}
   if(!sim.reactorTripped){const forcedLoss=r.state==='RUNNING'?Math.max(0,90-r.flow)/90:1;s.thermalRisk=clamp(s.thermalRisk+(0.001+forcedLoss*.015)*dt,0,1.2);s.rcsTemp=clamp(s.rcsTemp+(r.state==='RUNNING'?forcedLoss*.05:.12)*dt,300,340)}
   else{const secured=r.state==='STOPPED';s.thermalRisk=clamp(s.thermalRisk-(secured?.010:.004)*dt,0,1.2);s.rcsTemp=clamp(s.rcsTemp-(secured?.09:.04)*dt,300,340)}}
 if(stage.id===2){const s=sim.s2;if(s.frvCmd==='OPEN')s.frvActual=approach(s.frvActual,60,1.4,dt);else if(s.frvCmd==='CLOSE')s.frvActual=approach(s.frvActual,0,1.8,dt);else s.frvActual=clamp(s.frvActual-.11*dt,0,100);const target=flowFromFrv(s.frvActual);s.fw+= (target-s.fw)*Math.min(1,.35*dt);s.fw=clamp(s.fw,0,105);s.trend=(s.fw-s.steam)*.006;s.sg=clamp(s.sg+s.trend*dt,0,100)}
 if(stage.id===3){const s=sim.s3;s.afwFlow=approach(s.afwFlow,80,1.2,dt);s.steamDumpActual=approach(s.steamDumpActual,s.steamDumpCmd==='OPEN'?100:80,1.5,dt);s.sgPressure=approach(s.sgPressure,6.9,.018,dt);const old=s.sgLevel;s.sgLevel+= (55-s.sgLevel)*.012*dt;s.sgLevel=clamp(s.sgLevel,0,100);s.sgTrend=(s.sgLevel-old)/dt;s.rcsTemp+= (308-s.rcsTemp)*.012*dt}
 if(stage.id===4){const s=sim.s4;s.condenser=clamp(s.condenser+.15*dt,0,40);if(!sim.turbineTripped&&s.condenser>=25){sim.turbineTripped=true;tripReactor();s.tripReported=true;p('AUTO ACTION: TURBINE TRIP / REACTOR TRIP — CONDENSER VACUUM LOW','alarm')}
   if(s.steamDumpCmd==='OPEN')s.steamDumpActual=approach(s.steamDumpActual,100,4,dt);const condenserAvail=clamp((25-s.condenser)/15,0,1);s.steamDumpFlow=s.steamDumpActual*condenserAvail;
   if(s.atmCmd==='OPEN')s.atmActual=approach(s.atmActual,100,4,dt);s.atmFlow=s.atmActual;
   if(sim.reactorTripped)s.afwFlow=approach(s.afwFlow,80,1.5,dt);const adequate=sim.reactorTripped&&s.atmFlow>=60&&s.afwFlow>=50;const old=s.sgLevel;if(sim.reactorTripped){if(adequate){s.sgPressure=approach(s.sgPressure,6.9,.02,dt);s.sgLevel+= (55-s.sgLevel)*.012*dt;s.rcsTemp+= (309-s.rcsTemp)*.012*dt}else{s.sgPressure=clamp(s.sgPressure+.012*dt,6.7,7.8);s.sgLevel=clamp(s.sgLevel-.035*dt,0,100);s.rcsTemp=clamp(s.rcsTemp+.035*dt,300,340)}}s.sgTrend=(s.sgLevel-old)/dt}
 if(stage.id===5){const s=sim.s5;s.edgA.speed=clamp(s.edgA.speed+10*dt,0,100);s.edgB.speed=clamp(s.edgB.speed+10*dt,0,100);if(s.edgA.speed>=100)s.edgA.state='RUNNING';if(s.edgB.speed>=100)s.edgB.state='RUNNING';if(t>=15&&s.edgA.breaker==='OPEN'){s.edgA.breaker='CLOSED';s.edgA.breakerCmd='AUTO'}if(s.edgA.breaker==='CLOSED')s.busA=approach(s.busA,100,25,dt);if(s.edgB.breakerCmd==='CLOSE'&&s.edgB.closeAt!==null&&t-s.edgB.closeAt>=2)s.edgB.breaker='CLOSED';if(s.edgB.breaker==='CLOSED')s.busB=approach(s.busB,100,25,dt);s.rcsTemp=clamp(s.rcsTemp+(s.busA>=95&&s.busB>=95?-.05:.005)*dt,300,335)}
 if(stage.id===6){const s=sim.s6;if(s.afwValveCmd==='OPEN')s.afwValveActual=approach(s.afwValveActual,100,5,dt);s.afwB=clamp(s.afwValveActual,0,100);s.sgA=approach(s.sgA,52,.03,dt);s.sgC=approach(s.sgC,52,.03,dt);const old=s.sgB;s.sgTrend=(s.afwB>=60?.08:-.12);s.sgB=clamp(s.sgB+s.sgTrend*dt,0,100);s.rcsTemp=clamp(s.rcsTemp-(s.afwB>=60?.06:.025)*dt,300,335)}
 if(stage.id===7){const s=sim.s7;s.trueLevel=clamp(s.trueLevel-.003*dt,53,55);s.ch1=18;s.ch2=s.trueLevel+.3;s.ch3=s.trueLevel-.4}
 if(stage.id===8){updateRcpA(dt,'NORMAL');const s=sim.s8,old=s.rcsTemp;s.decayHeat=decayHeat(t);if(sim.rcpA.state==='RUNNING')s.rcsTemp=clamp(s.rcsTemp-.07*dt,295,330);else if(sim.rcpA.state==='STARTING')s.rcsTemp=clamp(s.rcsTemp-.025*dt,295,330);else if(sim.rcpA.state==='COASTDOWN')s.rcsTemp=clamp(s.rcsTemp+.015*dt,295,330);else s.rcsTemp=clamp(s.rcsTemp+(s.decayHeat>4.5?.03:-.01)*dt,295,330);s.rcsTrend=(s.rcsTemp-old)/dt;s.sgLevel=clamp(s.sgLevel-.003*dt,53,55)}
 while(sim.history.nextSample<=sim.simTime){sampleHistory(sim.history.nextSample);sim.history.nextSample+=10}
}
function updateSim(){if(!stage||finished||!sim)return;const now=Date.now();let dt=(now-sim.lastTick)/1000;if(dt<=0)return;sim.lastTick=now;while(dt>0){const step=Math.min(.5,dt);advanceStep(step);dt-=step}debugSampleDue()}
function currentFissionPower(){if(!sim.reactorTripped)return 100;const x=Math.max(0,sim.simTime-(sim.reactorTripAt??0));if(x<2)return Math.max(5,100-47.5*x);if(x<5)return Math.max(.8,5-(x-2)*1.4);return 0}
function currentDecay(){if(!sim.reactorTripped)return null;return decayHeat(Math.max(0,sim.simTime-(sim.reactorTripAt??0)))}
function rcsTemp(){if(stage.id===1)return sim.s1.rcsTemp;if(stage.id===3)return sim.s3.rcsTemp;if(stage.id===4)return sim.s4.rcsTemp;if(stage.id===5)return sim.s5.rcsTemp;if(stage.id===6)return sim.s6.rcsTemp;if(stage.id===8)return sim.s8.rcsTemp;return 320}
function sgData(which){const d={level:56,pressure:6.9,mfw:100,afw:0,steam:100};if(stage.id===2&&which==='B'){d.level=sim.s2.sg;d.mfw=sim.s2.fw}if(stage.id===3){d.level=sim.s3.sgLevel;d.pressure=sim.s3.sgPressure;d.mfw=0;d.afw=sim.s3.afwFlow}if(stage.id===4){d.level=sim.s4.sgLevel;d.pressure=sim.s4.sgPressure;d.mfw=0;d.afw=sim.s4.afwFlow}if(stage.id===6){d.level=which==='A'?sim.s6.sgA:which==='B'?sim.s6.sgB:sim.s6.sgC;d.mfw=0;d.afw=which==='A'?sim.s6.afwA:which==='B'?sim.s6.afwB:sim.s6.afwC}if(stage.id===7&&which==='B')d.level=sim.s7.trueLevel;if(stage.id===8&&which==='B')d.level=sim.s8.sgLevel;return d}
function systemStates(){const id=stage.id;const sA=sgData('A'),sB=sgData('B'),sC=sgData('C');const steamWarn=[sA,sB,sC].some(s=>s.level<50||s.level>60||s.pressure<6.7||s.pressure>7.1)||id===7;let primary='NORMAL';if(id===1&&(sim.rcpA.speed<98||sim.rcpA.flow<95||sim.rcpA.vib>1.4))primary='WARNING';if(id===8&&sim.rcpA.state!=='RUNNING')primary='WARNING';let fw='NORMAL';if(id===2&&Math.abs(sim.s2.fw-100)>5)fw='WARNING';if([3,4,6].includes(id))fw='WARNING';let elec='NORMAL';if(id===5&&(sim.s5.offsite<95||sim.s5.busA<95||sim.s5.busB<95))elec='WARNING';return {reactor:sim.reactorTripped?'TRIPPED':'NORMAL',primary,steam:steamWarn?'WARNING':'NORMAL',feedwater:fw,electrical:elec,safety:sim.reactorTripped?'ACTIVE':'STANDBY',instrument:id===7?'DISAGREEMENT':'NORMAL'}}
function status(name){updateSim();const st=systemStates(),id=stage.id;if(!name){block([`REACTOR       ${st.reactor}`,`PRIMARY       ${st.primary}`,`STEAM         ${st.steam}`,`FEEDWATER     ${st.feedwater}`,`ELECTRICAL    ${st.electrical}`,`SAFETY        ${st.safety}`,`INSTRUMENT    ${st.instrument}`]);return}
 if(name==='reactor')block(['REACTOR',`STATE        ${sim.reactorTripped?'TRIPPED':'RUNNING'}`,`POWER        ${currentFissionPower().toFixed(currentFissionPower()<10?1:0)} %`,`DECAY HEAT   ${sim.reactorTripped?currentDecay().toFixed(1)+' %':'--'}`]);
 else if(name==='primary')block(['PRIMARY SYSTEM',`LOOP-A       ${id===1||id===8&&sim.rcpA.state!=='RUNNING'?'WARNING':'NORMAL'}`,`LOOP-B       NORMAL`,`LOOP-C       NORMAL`,`RCS PRESS    15.5 MPa`,`HOT LEG      ${rcsTemp().toFixed(0)} C`]);
 else if(name==='steam'){const a=sgData('A'),b=sgData('B'),c=sgData('C');block(['STEAM / SG',`SG-A LEVEL   ${a.level.toFixed(0)} %`,`SG-B LEVEL   ${id===7?`${sim.s7.ch1.toFixed(0)} / ${sim.s7.ch2.toFixed(0)} / ${sim.s7.ch3.toFixed(0)}`:b.level.toFixed(0)} %`,`SG-C LEVEL   ${c.level.toFixed(0)} %`,`SG PRESS     ${b.pressure.toFixed(2)} MPa`])}
 else if(name==='feedwater'){if(id===6)block(['FEEDWATER','MFW-A FLOW   0 %','MFW-B FLOW   0 %','MFW-C FLOW   0 %',`AFW-A FLOW   ${sim.s6.afwA.toFixed(0)} % AFW-RATED`,`AFW-B FLOW   ${sim.s6.afwB.toFixed(0)} % AFW-RATED`,`AFW-C FLOW   ${sim.s6.afwC.toFixed(0)} % AFW-RATED`]);else if(id===3)block(['FEEDWATER','MFW FLOW     0 %',`AFW FLOW     ${sim.s3.afwFlow.toFixed(0)} % AFW-RATED`,'AFW DEMAND   YES']);else if(id===4)block(['FEEDWATER','MFW FLOW     0 %',`AFW FLOW     ${sim.s4.afwFlow.toFixed(0)} % AFW-RATED`,`AFW DEMAND   ${sim.reactorTripped?'YES':'NO'}`]);else block(['FEEDWATER','MFW-A FLOW   100 %',`MFW-B FLOW   ${id===2?sim.s2.fw.toFixed(0):100} %`,'MFW-C FLOW   100 %','AFW DEMAND   NO'])}
 else if(name==='turbine')block(['TURBINE / GENERATOR',`TURBINE      ${sim.turbineTripped?'TRIPPED':'RUNNING'}`,`GENERATOR    ${sim.turbineTripped?'OFFLINE':'ONLINE'}`]);
 else if(name==='condenser')block(['CONDENSER',`PRESSURE     ${id===4?sim.s4.condenser.toFixed(1):'7.0'} kPa(abs)`,`AVAILABLE    ${id===4&&sim.s4.condenser>=25?'NO':'YES'}`]);
 else if(name==='electrical')block(['ELECTRICAL',`OFFSITE      ${id===5?'LOST':'AVAILABLE'}`,`BUS-A        ${id===5?sim.s5.busA.toFixed(0):'100'} %`,`BUS-B        ${id===5?sim.s5.busB.toFixed(0):'100'} %`,`EDG-A        ${id===5?sim.s5.edgA.state:'STANDBY'}`,`EDG-B        ${id===5?sim.s5.edgB.state:'STANDBY'}`]);
 else if(name==='safety')block(['SAFETY / PROTECTION',`RPS          ${sim.reactorTripped?'TRIP COMPLETE':'STANDBY'}`,`AFW          ${[3,4,6].includes(id)?'DEMAND / ACTIVE':'STANDBY'}`,`INTERLOCKS   NORMAL`]);
 else if(name==='instrumentation')block(['INSTRUMENTATION',`SG-B LVL CH1 ${id===7?sim.s7.ch1.toFixed(0)+' % STABLE':'VALID'}`,`SG-B LVL CH2 ${id===7?sim.s7.ch2.toFixed(0)+' %':'VALID'}`,`SG-B LVL CH3 ${id===7?sim.s7.ch3.toFixed(0)+' %':'VALID'}`]);
 else p('UNKNOWN STATUS SYSTEM','danger')}
function read(dev){updateSim();const id=stage.id;const normalRcp=n=>block([n,'STATE        RUNNING','SPEED        100 %','FLOW         100 %','VIBRATION    1.0 INDEX','BEARING      70 C']);
 if(dev==='RCP-A'){if(id===1||id===8)block(['RCP-A',`STATE        ${sim.rcpA.state}`,`SPEED        ${sim.rcpA.speed.toFixed(0)} %`,`FLOW         ${sim.rcpA.flow.toFixed(0)} %`,`VIBRATION    ${sim.rcpA.vib.toFixed(1)} INDEX`,`BEARING      ${sim.rcpA.bearing.toFixed(0)} C`]);else normalRcp(dev)}
 else if(['RCP-B','RCP-C'].includes(dev))normalRcp(dev);
 else if(/^SG-[ABC]$/.test(dev)){const which=dev.at(-1),d=sgData(which),lines=[dev,`LEVEL        ${d.level.toFixed(0)} %`,`PRESSURE     ${d.pressure.toFixed(2)} MPa`,`STEAM FLOW   ${d.steam.toFixed(0)} %`];if([3,4,6].includes(id)){lines.push(`MFW FLOW     ${d.mfw.toFixed(0)} %`);lines.push(`AFW FLOW     ${d.afw.toFixed(0)} % AFW-RATED`)}else lines.push(`FEEDWATER    ${d.mfw.toFixed(0)} %`);block(lines)}
 else if(/^FRV-[ABC]$/.test(dev)){const b=dev==='FRV-B'&&id===2;block([dev,`COMMAND      ${b?sim.s2.frvCmd:'AUTO'}`,`ACTUAL       ${b?sim.s2.frvActual.toFixed(0):'50'} %`,`FLOW         ${b?sim.s2.fw.toFixed(0):'100'} %`,b?'FAULT FLAG   NOT AVAILABLE TO OPERATOR':'STATE        NORMAL'])}
 else if(dev==='CONDENSER')block(['CONDENSER',`PRESSURE     ${id===4?sim.s4.condenser.toFixed(1):'7.0'} kPa(abs)`,`AVAILABLE    ${id===4&&sim.s4.condenser>=25?'NO':'YES'}`]);
 else if(dev==='EDG-A'){if(id===5)block(['EDG-A','DEMAND       YES',`ENGINE       ${sim.s5.edgA.state}`,`SPEED        ${sim.s5.edgA.speed.toFixed(0)} %`,`BREAKER CMD ${sim.s5.edgA.breakerCmd}`,`BREAKER      ${sim.s5.edgA.breaker}`]);else block(['EDG-A','DEMAND       NO','ENGINE       STANDBY','SPEED        0 %','BREAKER      CLOSED'])}
 else if(dev==='EDG-B'){if(id===5)block(['EDG-B','DEMAND       YES',`ENGINE       ${sim.s5.edgB.state}`,`SPEED        ${sim.s5.edgB.speed.toFixed(0)} %`,`BREAKER CMD ${sim.s5.edgB.breakerCmd}`,`BREAKER      ${sim.s5.edgB.breaker}`]);else block(['EDG-B','DEMAND       NO','ENGINE       STANDBY','SPEED        0 %','BREAKER      CLOSED'])}
 else if(dev==='EDG-B-BREAKER')block(['EDG-B BREAKER',`COMMAND      ${id===5?sim.s5.edgB.breakerCmd:'AUTO'}`,`POSITION     ${id===5?sim.s5.edgB.breaker:'CLOSED'}`,`BUS-B        ${id===5&&sim.s5.busB<10?'DEAD':'ENERGIZED'}`]);
 else if(dev==='BUS-A')block(['BUS-A',`VOLTAGE      ${id===5?sim.s5.busA.toFixed(0):'100'} %`]);
 else if(dev==='BUS-B')block(['BUS-B',`VOLTAGE      ${id===5?sim.s5.busB.toFixed(0):'100'} %`]);
 else if(dev==='OFFSITE')block(['OFFSITE POWER',`STATE        ${id===5?'LOST':'AVAILABLE'}`,`VOLTAGE      ${id===5?'0':'100'} %`]);
 else if(/^AFW-[ABC]$/.test(dev)){const w=dev.at(-1);let demand=[3,4,6].includes(id),pump='STANDBY',flow=0;if(id===3){pump='RUNNING';flow=sim.s3.afwFlow}else if(id===4){pump=sim.reactorTripped?'RUNNING':'STANDBY';flow=sim.s4.afwFlow}else if(id===6){pump='RUNNING';flow=w==='A'?sim.s6.afwA:w==='B'?sim.s6.afwB:sim.s6.afwC}block([dev,`DEMAND       ${demand?'YES':'NO'}`,`PUMP         ${pump}`,`FLOW         ${flow.toFixed(0)} % AFW-RATED`])}
 else if(/^AFW-VALVE-[ABC]$/.test(dev)){const w=dev.at(-1);if(id===6&&w==='B')block(['AFW-B DELIVERY VALVE',`COMMAND      ${sim.s6.afwValveCmd}`,`ACTUAL       ${sim.s6.afwValveActual.toFixed(0)} %`]);else block([dev,'COMMAND      AUTO','ACTUAL       OPEN'])}
 else if(dev.startsWith('SG-B-LVL-CH')){const n=dev.slice(-1),v=id===7?(n==='1'?sim.s7.ch1:n==='2'?sim.s7.ch2:sim.s7.ch3):55;block([dev,`VALUE        ${Number(v).toFixed(0)} %`,`QUALITY      VALID`])}
 else if(dev==='REACTOR')status('reactor');
 else if(dev==='RCS')block(['RCS','PRESSURE     15.5 MPa',`HOT LEG      ${rcsTemp().toFixed(0)} C`,`COLD LEG     ${(rcsTemp()-30).toFixed(0)} C`,`DELTA-T      30 C`]);
 else if(dev==='PZR')block(['PZR','PRESSURE     15.5 MPa','LEVEL        52 %','HEATER       AUTO','SPRAY        AUTO']);
 else if(dev==='RPS')status('safety');
 else if(dev==='TURBINE'||dev==='GENERATOR')status('turbine');
 else if(dev==='STEAM-DUMP'){if(id===3)block(['STEAM-DUMP',`COMMAND      ${sim.s3.steamDumpCmd}`,`ACTUAL       ${sim.s3.steamDumpActual.toFixed(0)} %`,'HEAT SINK    CONDENSER','AVAILABLE    YES']);else if(id===4)block(['STEAM-DUMP',`COMMAND      ${sim.s4.steamDumpCmd}`,`ACTUAL       ${sim.s4.steamDumpActual.toFixed(0)} %`,`FLOW         ${sim.s4.steamDumpFlow.toFixed(0)} %`,`CONDENSER    ${sim.s4.condenser>=25?'UNAVAILABLE':'DEGRADED'}`]);else block(['STEAM-DUMP','COMMAND      AUTO','ACTUAL       0 %','AVAILABLE    YES'])}
 else if(dev==='ATM-DUMP'){if(id===4)block(['ATM-DUMP',`COMMAND      ${sim.s4.atmCmd}`,`ACTUAL       ${sim.s4.atmActual.toFixed(0)} %`,`FLOW         ${sim.s4.atmFlow.toFixed(0)} %`]);else block(['ATM-DUMP','COMMAND      STANDBY','ACTUAL       0 %'])}
 else p('UNKNOWN DEVICE','danger')}
function histLabel(t){if(t<0){const sec=Math.abs(Math.round(t));return `T-${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}const sec=Math.round(t);return `T+${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function historyCmd(dev,param){updateSim();const key=`${dev} ${param}`.trim(),data=sim.history.data[key];if(!data||!data.length){p('NO HISTORY DATA','danger');return}const unit=key.includes('VIBRATION')?'':key.includes('POSITION')||key.includes('FLOW')||key.includes('LEVEL')||key.includes('VOLTAGE')||key.includes('SPEED')?' %':key.includes('PRESSURE')?' kPa':'';const lines=[`${key} HISTORY`];data.slice(-8).forEach(x=>lines.push(`${histLabel(x.t).padEnd(10)} ${Number(x.v).toFixed(key.includes('VIBRATION')?1:0)}${unit}`));let nowVal=null;if(key==='RCP-A FLOW')nowVal=sim.rcpA.flow;if(key==='RCP-A VIBRATION')nowVal=sim.rcpA.vib;if(key==='RCP-A SPEED')nowVal=sim.rcpA.speed;if(key==='SG-B LEVEL')nowVal=sim.s2.sg;if(key==='FRV-B POSITION')nowVal=sim.s2.frvActual;if(key==='CONDENSER PRESSURE')nowVal=sim.s4.condenser;if(key==='BUS-B VOLTAGE')nowVal=sim.s5.busB;if(key==='AFW-B FLOW')nowVal=sim.s6.afwB;if(key==='SG-B-LVL-CH1 LEVEL')nowVal=sim.s7.ch1;if(key==='SG-B-LVL-CH2 LEVEL')nowVal=sim.s7.ch2;if(nowVal!==null)lines.push(`NOW        ${Number(nowVal).toFixed(key.includes('VIBRATION')||key.includes('PRESSURE')?1:0)}${unit}`);block(lines)}
function activeAlarms(){const id=stage.id,a=[];const add=(code,msg)=>a.push([code,msg]);if(id===1){if(sim.rcpA.speed<95)add('A-110','RCP-A SPEED LOW');if(sim.rcpA.flow<90)add('A-111','PRIMARY LOOP-A FLOW LOW');if(sim.rcpA.vib>2)add('A-112','RCP-A VIBRATION HIGH');if(sim.rcpA.bearing>80)add('A-113','RCP-A BEARING TEMP HIGH');if(sim.reactorTripped)add('A-114','REACTOR TRIP')}
 if(id===2){if(Math.abs(sim.s2.fw-sim.s2.steam)>20)add('A-120','FW-B / STEAM FLOW MISMATCH');if(sim.s2.sg<40)add('A-121','SG-B LEVEL LOW');if(sim.s2.sg<25)add('A-122','SG-B LEVEL VERY LOW')}
 if(id===3){add('A-130','TURBINE TRIP');add('A-131','REACTOR TRIP');if(sim.s3.sgPressure>7.3)add('A-132','SG PRESSURE HIGH');if(sim.s3.sgLevel<40)add('A-133','SG LEVEL LOW')}
 if(id===4){if(sim.s4.condenser>15)add('A-140','CONDENSER VACUUM DEGRADED');if(sim.s4.condenser>25)add('A-141','CONDENSER VACUUM LOW');if(sim.turbineTripped)add('A-142','TURBINE TRIP');if(sim.reactorTripped)add('A-143','REACTOR TRIP')}
 if(id===5){add('A-150','OFFSITE POWER LOST');if(sim.s5.busA<90)add('A-151','BUS-A UNDERVOLTAGE');if(sim.s5.busB<90)add('A-152','BUS-B UNDERVOLTAGE');if(sim.simTime>15&&sim.s5.edgB.state==='RUNNING'&&sim.s5.busB<10)add('A-153','EDG-B OUTPUT NOT CONNECTED')}
 if(id===6){add('A-160','MAIN FEEDWATER LOST');if(sim.s6.afwBPump==='RUNNING'&&sim.s6.afwB<40)add('A-161','AFW-B DELIVERY LOW');if(sim.s6.sgB<40)add('A-162','SG-B LEVEL LOW');if(sim.s6.sgB<25)add('A-163','SG-B LEVEL VERY LOW')}
 if(id===7){if(sim.s7.ch1<40)add('A-170','SG-B LEVEL LOW CH-1');if(Math.max(sim.s7.ch1,sim.s7.ch2,sim.s7.ch3)-Math.min(sim.s7.ch1,sim.s7.ch2,sim.s7.ch3)>10)add('A-171','SG-B LEVEL CHANNEL DISAGREEMENT')}
 if(id===8){add('A-180','REACTOR TRIP / PROTECTION ACTUATION');if(sim.rcpA.state!=='RUNNING')add('A-181','PRIMARY FORCED CIRCULATION DEGRADED')}
 return a}
function alarms(detail=false){updateSim();const a=activeAlarms();if(!a.length){block(['ACTIVE ALARMS','','NONE']);return}block(['ACTIVE ALARMS','',...a.map(x=>`${x[0]}   ${x[1]}`),detail?'\nNOTE: Alarm source is not necessarily root cause.':''])}
function acceptControl(cmd,msg,fn){if(fn)fn();controls.add(cmd);controlCount++;p('COMMAND ACCEPTED: '+cmd.replace('CONTROL ','').toUpperCase(),'ok');if(msg)p(msg,'alarm');stableSince=null;return true}
function rejectControl(msg){p('COMMAND REJECTED: '+msg,'danger');return false}
function noChange(msg){p('COMMAND ACKNOWLEDGED: '+msg,'alarm');return false}
function control(cmd){if(finished){p('STAGE COMPLETE: CONTROL DISABLED','danger');return false}updateSim();const id=stage.id;
 if(cmd==='CONTROL REACTOR TRIP'){if(sim.reactorTripped)return noChange('REACTOR ALREADY TRIPPED');return acceptControl(cmd,'RPS: REACTOR TRIP COMPLETE',()=>tripReactor())}
 if(cmd==='CONTROL RCP-A STOP'){if(![1,8].includes(id))return rejectControl('RCP-A MANUAL CONTROL NOT AUTHORIZED IN CURRENT STAGE');if(sim.rcpA.state==='STOPPED'||sim.rcpA.state==='COASTDOWN')return noChange('RCP-A ALREADY STOPPING / STOPPED');return acceptControl(cmd,'RCP-A: COASTDOWN INITIATED',()=>{sim.rcpA.state='COASTDOWN';sim.rcpA.stopAt=sim.simTime})}
 if(cmd==='CONTROL RCP-A START'){if(![1,8].includes(id))return rejectControl('RCP-A MANUAL CONTROL NOT AUTHORIZED IN CURRENT STAGE');if(sim.rcpA.state==='RUNNING'||sim.rcpA.state==='STARTING')return noChange('RCP-A ALREADY RUNNING / STARTING');if(sim.rcpA.state==='COASTDOWN')return rejectControl('RCP-A COASTDOWN IN PROGRESS');if(id===1&&!sim.reactorTripped)return rejectControl('START PERMISSIVE NOT MET');return acceptControl(cmd,'RCP-A: START SEQUENCE INITIATED',()=>{sim.rcpA.state='STARTING'})}
 if(cmd==='CONTROL FRV-B OPEN'||cmd==='CONTROL FRV-B CLOSE'){if(id!==2)return rejectControl('FRV-B MANUAL CONTROL NOT AUTHORIZED IN CURRENT STAGE');const open=cmd.endsWith('OPEN');return acceptControl(cmd,open?'FRV-B COMMAND OPEN; ACTUAL RESPONSE RECOVERING':'FRV-B COMMAND CLOSE; ACTUAL POSITION DECREASING',()=>{sim.s2.frvCmd=open?'OPEN':'CLOSE';if(open)sim.s2.recoveryAt=sim.simTime})}
 if(['CONTROL AFW-A START','CONTROL AFW-B START','CONTROL AFW-C START'].includes(cmd)){if(![3,4,6].includes(id))return rejectControl('AFW START NOT DEMANDED IN CURRENT PLANT STATE');if(id===6)return noChange(cmd.includes('AFW-B')?'AFW-B PUMP ALREADY RUNNING; DELIVERY FLOW REMAINS LOW':'SELECTED AFW PUMP ALREADY RUNNING');return noChange('AFW AUTO ACTUATION ALREADY ACTIVE')}
 if(cmd==='CONTROL AFW-VALVE-B OPEN'){if(id!==6)return rejectControl('AFW-B DELIVERY VALVE MANUAL CONTROL NOT AUTHORIZED IN CURRENT STAGE');if(sim.s6.afwValveCmd==='OPEN')return noChange('AFW-B DELIVERY VALVE ALREADY COMMANDED OPEN');return acceptControl(cmd,'AFW-B DELIVERY PATH OPENING',()=>{sim.s6.afwValveCmd='OPEN'})}
 if(cmd==='CONTROL STEAM-DUMP OPEN'){if(![3,4].includes(id))return rejectControl('STEAM-DUMP MANUAL CONTROL NOT AUTHORIZED IN CURRENT STAGE');if(id===3){if(sim.s3.steamDumpCmd==='OPEN')return noChange('STEAM-DUMP ALREADY OPENING');return acceptControl(cmd,'STEAM-DUMP MANUAL OPEN REQUEST',()=>{sim.s3.steamDumpCmd='OPEN'})}if(sim.s4.steamDumpCmd==='OPEN')return noChange('STEAM-DUMP ALREADY OPENING');return acceptControl(cmd,'STEAM-DUMP OPEN REQUEST; CONDENSER ACCEPTANCE MAY LIMIT FLOW',()=>{sim.s4.steamDumpCmd='OPEN'})}
 if(cmd==='CONTROL ATM-DUMP OPEN'){if(id!==4)return rejectControl('ATMOSPHERIC DUMP NOT REQUIRED / NOT AUTHORIZED IN CURRENT STAGE');if(!sim.reactorTripped&&sim.s4.condenser<20)return rejectControl('OPEN PERMISSIVE NOT MET');if(sim.s4.atmCmd==='OPEN')return noChange('ATM-DUMP ALREADY OPENING');return acceptControl(cmd,'ATMOSPHERIC HEAT-REMOVAL PATH OPENING',()=>{sim.s4.atmCmd='OPEN'})}
 if(cmd==='CONTROL EDG-A START'||cmd==='CONTROL EDG-B START'){if(id!==5)return rejectControl('EDG START NOT DEMANDED IN CURRENT PLANT STATE');const e=cmd.includes('EDG-A')?sim.s5.edgA:sim.s5.edgB;if(e.state==='RUNNING'||e.state==='CRANKING')return noChange('EDG AUTO START SEQUENCE ALREADY ACTIVE');return acceptControl(cmd,'EDG START REQUEST',()=>{e.state='CRANKING'})}
 if(cmd==='CONTROL EDG-B-BREAKER CLOSE'){if(id!==5)return rejectControl('EDG-B BREAKER CONTROL NOT AUTHORIZED IN CURRENT STAGE');if(sim.s5.edgB.speed<95)return rejectControl('EDG-B SPEED PERMISSIVE NOT MET');if(sim.s5.edgB.breaker==='CLOSED'||sim.s5.edgB.breakerCmd==='CLOSE')return noChange('EDG-B BREAKER ALREADY CLOSED / CLOSING');return acceptControl(cmd,'EDG-B BREAKER CLOSE COMMAND; ACTUAL CLOSURE PENDING',()=>{sim.s5.edgB.breakerCmd='CLOSE';sim.s5.edgB.closeAt=sim.simTime})}
 return rejectControl('CONTROL COMMAND NOT APPLICABLE TO CURRENT PLANT STATE')}
function baseSafeState(){const id=stage.id;if(id===1)return sim.reactorTripped&&sim.rcpA.state==='STOPPED'&&sim.rcpA.speed===0&&sim.s1.thermalRisk<=.25&&sim.s1.rcsTemp<=315;
 if(id===2)return sim.s2.frvCmd==='OPEN'&&sim.s2.fw>=95&&sim.s2.fw<=105&&sim.s2.sg>=50&&sim.s2.sg<=60&&sim.s2.trend>=-.005;
 if(id===3)return sim.reactorTripped&&sim.turbineTripped&&sim.s3.sgPressure>=6.7&&sim.s3.sgPressure<=7.1&&sim.s3.sgLevel>=50&&sim.s3.sgLevel<=60&&sim.s3.afwFlow>=60&&sim.s3.rcsTemp<=315;
 if(id===4)return sim.reactorTripped&&sim.turbineTripped&&sim.s4.atmFlow>=80&&sim.s4.afwFlow>=60&&sim.s4.sgPressure>=6.7&&sim.s4.sgPressure<=7.1&&sim.s4.sgLevel>=45&&sim.s4.sgLevel<=60&&sim.s4.sgTrend>=-.01&&sim.s4.rcsTemp<=315;
 if(id===5)return sim.s5.busA>=95&&sim.s5.busB>=95&&sim.s5.edgA.breaker==='CLOSED'&&sim.s5.edgB.breaker==='CLOSED'&&sim.s5.rcsTemp<=318;
 if(id===6)return sim.s6.afwB>=80&&sim.s6.sgB>=50&&sim.s6.sgB<=60&&sim.s6.sgTrend>=0&&sim.s6.rcsTemp<=315;
 if(id===7)return sim.s7.trueLevel>=50&&sim.s7.trueLevel<=60&&Math.abs(sim.s7.ch2-sim.s7.ch3)<2;
 if(id===8)return sim.reactorTripped&&sim.rcpA.state==='RUNNING'&&sim.s8.decayHeat<5.0&&sim.s8.rcsTemp<312&&sim.s8.rcsTrend<=0;
 return false}
function failureState(){const id=stage.id;if(id===1)return sim.s1.thermalRisk>=1||sim.s1.rcsTemp>=335;if(id===2)return sim.s2.sg<=20;if(id===4)return sim.s4.sgLevel<=25||sim.s4.rcsTemp>=335;if(id===5)return sim.s5.rcsTemp>=330;if(id===6)return sim.s6.sgB<=20||sim.s6.rcsTemp>=330;if(id===8)return sim.s8.rcsTemp>=330;return false}
function stableFor(){return stableSince===null?0:Math.max(0,sim.simTime-stableSince)}
function checkClear(){if(finished)return;updateSim();const safe=baseSafeState();if(debugLogEnabled&&debugLogLastSafe!==safe){debugLogAdd(`SAFE BASE ${debugLogLastSafe?'YES':'NO'} -> ${safe?'YES':'NO'}`);debugLogLastSafe=safe}const eligible=sim.simTime>=stage.minClear&&safe;if(eligible){if(stableSince===null){stableSince=sim.simTime;debugLogAdd('STABLE TIMER START')}}else if(stableSince!==null){debugLogAdd('STABLE TIMER RESET');stableSince=null}if(stableFor()>=stage.stable)finish(true)}
function finish(clear){if(finished)return;updateSim();debugLogAdd(clear?'RESULT CLEAR':'RESULT FAIL');finishAt=Date.now();finished=true;if(timer)clearInterval(timer);p('');p(clear?'=== CLEAR ===':'=== FAIL ===',clear?'ok':'danger');rightTitle.textContent=clear?'RESULT // CLEAR':'RESULT // FAIL';right.className='right-body';right.innerHTML=`<div class="result"><h2>${clear?'STAGE CLEAR':'STAGE FAILED'}</h2><p>STAGE-${stage.id}<br>ELAPSED ${elapsed()} sec<br>CONTROL ACTIONS ${controlCount}</p><button id="retry">RETRY</button><button id="sel">STAGE SELECT</button></div>`;right.querySelector('#retry').onclick=()=>startStage(stage);right.querySelector('#sel').onclick=showSelect}
function tick(){if(!stage||finished)return;updateSim();if(failureState()){finish(false);return}checkClear();if(!finished&&elapsed()>=stage.duration)finish(false)}
function debugExtra(){const id=stage.id;if(id===1)return [`RCP-A STATE  ${sim.rcpA.state}`,`RCP-A FLOW   ${sim.rcpA.flow.toFixed(1)} %`,`THERM RISK   ${sim.s1.thermalRisk.toFixed(3)}`,`RCS HOT LEG  ${sim.s1.rcsTemp.toFixed(1)} C`];if(id===2)return [`FRV-B CMD    ${sim.s2.frvCmd}`,`FRV-B ACT    ${sim.s2.frvActual.toFixed(1)} %`,`FW-B FLOW    ${sim.s2.fw.toFixed(1)} %`,`SG-B LEVEL   ${sim.s2.sg.toFixed(1)} %`,`SG-B TREND   ${sim.s2.trend>=0?'+':''}${sim.s2.trend.toFixed(3)} %/s`];if(id===3)return [`SG PRESS     ${sim.s3.sgPressure.toFixed(2)} MPa`,`SG LEVEL     ${sim.s3.sgLevel.toFixed(1)} %`,`AFW FLOW     ${sim.s3.afwFlow.toFixed(1)} %`,`RCS HOT LEG  ${sim.s3.rcsTemp.toFixed(1)} C`];if(id===4)return [`COND PRESS   ${sim.s4.condenser.toFixed(1)} kPa`,`ATM FLOW     ${sim.s4.atmFlow.toFixed(1)} %`,`AFW FLOW     ${sim.s4.afwFlow.toFixed(1)} %`,`SG LEVEL     ${sim.s4.sgLevel.toFixed(1)} %`,`RCS HOT LEG  ${sim.s4.rcsTemp.toFixed(1)} C`];if(id===5)return [`EDG-A/B SPD  ${sim.s5.edgA.speed.toFixed(0)} / ${sim.s5.edgB.speed.toFixed(0)} %`,`BUS-A/B      ${sim.s5.busA.toFixed(0)} / ${sim.s5.busB.toFixed(0)} %`,`BRK-A/B      ${sim.s5.edgA.breaker} / ${sim.s5.edgB.breaker}`];if(id===6)return [`AFW-B VALVE  ${sim.s6.afwValveActual.toFixed(1)} %`,`AFW-B FLOW   ${sim.s6.afwB.toFixed(1)} %`,`SG-B LEVEL   ${sim.s6.sgB.toFixed(1)} %`,`SG-B TREND   ${sim.s6.sgTrend>=0?'+':''}${sim.s6.sgTrend.toFixed(3)} %/s`,`RCS HOT LEG  ${sim.s6.rcsTemp.toFixed(1)} C`];if(id===7)return [`SG-B TRUE     ${sim.s7.trueLevel.toFixed(1)} %`,`CH1/2/3      ${sim.s7.ch1.toFixed(0)} / ${sim.s7.ch2.toFixed(1)} / ${sim.s7.ch3.toFixed(1)} %`];if(id===8)return [`DECAY HEAT    ${sim.s8.decayHeat.toFixed(2)} %`,`RCS HOT LEG  ${sim.s8.rcsTemp.toFixed(1)} C`,`RCS TREND    ${sim.s8.rcsTrend>=0?'+':''}${sim.s8.rcsTrend.toFixed(3)} C/s`,`RCP-A STATE  ${sim.rcpA.state}`];return []}
function execute(raw){const text=raw.trim();if(!text)return;cmdHistory.push(text);histPos=cmdHistory.length;p('> '+text);const up=text.toUpperCase(),a=up.split(/\s+/);if(up==='DEBUG LOG ON'){debugLogEnabled=true;if(stage){debugLog=[];debugLogNextSample=Math.ceil(sim.simTime/5)*5;if(debugLogNextSample<=sim.simTime)debugLogNextSample+=5;debugLogLastSafe=baseSafeState();debugLogAdd('DEBUG LOG ON');debugSnapshot()}block(['DEBUG LOG','STATE            ON','SAMPLE INTERVAL  5 s','EVENT CAPTURE    ON']);return}if(up==='DEBUG LOG OFF'){debugLogAdd('DEBUG LOG OFF');debugLogEnabled=false;block(['DEBUG LOG','STATE            OFF']);return}if(up==='DEBUG LOG CLEAR'){debugLog=[];if(stage)debugLogAdd('DEBUG LOG CLEARED');block(['DEBUG LOG','LOG CLEARED']);return}if(up==='DEBUG LOG SHOW'){if(!debugLog.length){block(['DEBUG LOG','NO LOG DATA']);return}block(['DEBUG LOG',...debugLog,'END DEBUG LOG']);return}if(up==='DEBUG STATE'){updateSim();block(['DEBUG STATE',`STAGE         ${stage?.id??'NONE'}`,`ELAPSED       ${stage?sim.simTime.toFixed(1):'0.0'} s`,`CONTROL ACT  ${controlCount}`,`SAFE BASE     ${stage&&baseSafeState()?'YES':'NO'}`,`MIN CLEAR     ${stage?.minClear??0} s`,`STABLE FOR   ${stage?stableFor().toFixed(1):'0.0'} / ${stage?.stable??0} s`,`CLEAR READY  ${stage&&!finished&&sim.simTime>=stage.minClear&&baseSafeState()&&stableFor()>=stage.stable?'YES':'NO'}`,...(stage?debugExtra():[])]);return}
 if(up==='DEBUG TIME'){const now=elapsedPrecise();block(['DEBUG TIME',`ELAPSED          ${now.toFixed(1)} s`,`LAST COMMAND     ${lastCommand??'NONE'}`,`LAST COMMAND AT  ${fmtTime(lastCommandAt)}`,`SINCE COMMAND    ${lastCommandAt===null?'--':(now-lastCommandAt).toFixed(1)+' s'}`,`LAST CONTROL     ${lastControl??'NONE'}`,`LAST CONTROL AT  ${fmtTime(lastControlAt)}`,`SINCE CONTROL    ${lastControlAt===null?'--':(now-lastControlAt).toFixed(1)+' s'}`,`LIMIT            ${stage?.duration??0} s`,finished?'CLOCK            FROZEN':'CLOCK            RUNNING']);return}
 if(up==='DEBUG SENSORS'){if(stage?.id===7)block(['DEBUG SENSORS',`SG-B TRUE ${sim.s7.trueLevel.toFixed(1)} / CH1 ${sim.s7.ch1.toFixed(1)} / CH2 ${sim.s7.ch2.toFixed(1)} / CH3 ${sim.s7.ch3.toFixed(1)}`]);else block(['DEBUG SENSORS','NO SENSOR FAULT']);return}
 if(up==='DEBUG PROTECTION'){block(['DEBUG PROTECTION',stage&&sim.reactorTripped?'RPS TRIP COMPLETE / POST-TRIP LOGIC ACTIVE':'RPS STANDBY']);return}
 if(/^STAGE-[1-8]$/.test(up)){startStage(STAGES[Number(up.split('-')[1])-1]);return}
 if(stage){lastCommand=up;lastCommandAt=elapsedPrecise();if(a[0]==='CONTROL'){lastControl=up;lastControlAt=lastCommandAt}}
 if(up==='CLEAR'){out.innerHTML='';return}
 if(up==='HELP'){block(['COMMAND FAMILIES','STATUS [SYSTEM]','READ <DEVICE>','HISTORY <DEVICE> <PARAMETER>','ALARM [DETAIL]','CONTROL <DEVICE> <ACTION>','CLEAR']);return}
 if(!stage){p('NO ACTIVE STAGE','danger');return}
 if(a[0]==='STATUS'){status((a[1]||'').toLowerCase());return}
 if(a[0]==='READ'){read(a.slice(1).join('-'));return}
 if(a[0]==='HISTORY'){historyCmd(a[1],a[2]||'');return}
 if(a[0]==='ALARM'){alarms(a[1]==='DETAIL');return}
 if(a[0]==='CONTROL'){control(up);return}
 p('UNKNOWN COMMAND. See COMMAND REFERENCE in the manual.','danger')}
document.getElementById('executeBtn').onclick=()=>{execute(input.value);input.value=''};input.onkeydown=e=>{if(e.key==='Enter'){execute(input.value);input.value=''}else if(e.key==='ArrowUp'){if(cmdHistory.length){histPos=Math.max(0,histPos-1);input.value=cmdHistory[histPos]||'';e.preventDefault()}}else if(e.key==='ArrowDown'){histPos=Math.min(cmdHistory.length,histPos+1);input.value=cmdHistory[histPos]||'';e.preventDefault()}};returnBtn.onclick=showSelect;showSelect();
})();
