(()=>{
const out=document.getElementById('terminalOut'),input=document.getElementById('commandInput'),right=document.getElementById('rightBody'),rightTitle=document.getElementById('rightTitle'),returnBtn=document.getElementById('returnStageBtn'),timeStatus=document.getElementById('timeStatus');
let stage=null,startAt=0,finishAt=0,timer=null,controls=new Set(),controlCount=0,cmdHistory=[],histPos=0,finished=false,sim=null,lastCommand=null,lastCommandAt=null,lastControl=null,lastControlAt=null,stableSince=null;
let mode='stage',tutorialStep=0,tutorialCoach=null,tutorialHighlight=null,simulationFailureLatched=false;
let debugLogEnabled=true,debugLog=[],debugLogNextSample=5,debugLogLastSafe=null;
const isTutorial=()=>mode==='tutorial';
const isSimulation=()=>mode==='simulation';
const stageLabel=()=>isTutorial()?'TUTORIAL':isSimulation()?'SIMULATION':`STAGE-${stage?.id??'-'}`;
function logTime(){return stage&&sim?sim.simTime:0}
function fmtPlantClock(minutes,withSeconds=false){if(minutes===null||!Number.isFinite(minutes))return '--:--';const v=Math.max(0,minutes);const h=Math.floor(v/60),m=Math.floor(v%60);if(!withSeconds)return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;const sec=Math.floor((v-Math.floor(v))*60);return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
function debugLogAdd(text,t=logTime()){if(!debugLogEnabled)return;debugLog.push(`[P+${fmtPlantClock(t,true)}] ${text}`)}
function debugSnapshot(){if(!stage||!sim)return;debugLogAdd(`SNAPSHOT SAFE=${baseSafeState()?'YES':'NO'} STABLE=${stableFor().toFixed(1)}m PLANT=${fmtPlantClock(plantMarginMinutes())} LIMIT=${fmtPlantClock(timeLimitRemaining())} | ${debugExtra().join(' | ')}`)}
function debugSampleDue(){if(!debugLogEnabled||!stage||!sim)return;while(sim.simTime>=debugLogNextSample){debugLogAdd(`SNAPSHOT SAFE=${baseSafeState()?'YES':'NO'} STABLE=${stableFor().toFixed(1)}m PLANT=${fmtPlantClock(plantMarginMinutes())} LIMIT=${fmtPlantClock(timeLimitRemaining())} | ${debugExtra().join(' | ')}`,debugLogNextSample);debugLogNextSample+=5}}
const p=(t='',c='')=>{const d=document.createElement('div');d.textContent=t;if(c)d.className=c;out.appendChild(d);out.scrollTop=out.scrollHeight;if(debugLogEnabled&&stage&&t&&(t.startsWith('AUTO ACTION:')||t.startsWith('INTERLOCK:')||t.startsWith('COMMAND ACCEPTED:')||t.startsWith('COMMAND REJECTED:')||t.startsWith('RPS:')||t.startsWith('RCP-A:')||t.startsWith('INSTRUMENT DIAGNOSTIC')||t.startsWith('FAULT REPORT')))debugLogAdd(`EVENT ${t}`)};
const block=(a,c='')=>p(a.join('\n'),c);
const elapsed=()=>stage?Math.floor(((finished&&finishAt)?finishAt:Date.now())-startAt)/1000:0;
const elapsedPrecise=()=>stage?(((finished&&finishAt)?finishAt:Date.now())-startAt)/1000:0;
const fmtTime=v=>v===null?'--':fmtPlantClock(v,true);
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const approach=(v,target,rate,dt)=>v<target?Math.min(target,v+rate*dt):Math.max(target,v-rate*dt);
function timeLimitRemaining(){if(!stage||!sim||isSimulation())return null;return Math.max(0,TIME_CONFIG.timeLimitMinutes-sim.simTime)}
function plantMarginMinutes(){if(!stage||!sim)return null;const id=stage.id;
 if(id===0){const s=sim.s0;if(sim.reactorTripped){const adequate=(s.steamDumpActual>=60||s.atmActual>=60)&&s.afwBFlow>=50&&sim.rcpA.state!=='STOPPED';if(adequate)return null;const rate=Math.max(.005,s.rcsTrend||.04);return Math.max(0,(335-s.rcsTemp)/rate)}if(s.sgTrend<-.002)return Math.max(0,(s.sgB-15)/Math.max(.001,-s.sgTrend));if(sim.rcpA.state!=='RUNNING')return Math.max(0,(335-s.rcsTemp)/.08);return null}
 if(id===1){if(sim.reactorTripped)return null;const r=sim.rcpA,s=sim.s1;const forcedLoss=r.state==='RUNNING'?Math.max(0,90-r.flow)/90:1;const riskRate=.001+forcedLoss*.015;const tempRate=r.state==='RUNNING'?Math.max(.001,forcedLoss*.05):.12;return Math.max(0,Math.min((1-s.thermalRisk)/Math.max(.0001,riskRate),(335-s.rcsTemp)/Math.max(.0001,tempRate)))}
 if(id===2){if(sim.reactorTripped&&sim.s2.afwFlow>=50)return null;const rate=Math.max(.001,-sim.s2.trend);return Math.max(0,(sim.s2.sg-15)/rate)}
 if(id===3){const s=sim.s3;if(s.steamDumpActual>=70&&s.afwFlow>=60)return null;return Math.max(0,Math.min((335-s.rcsTemp)/.065,(s.sgLevel-25)/.015))}
 if(id===4){const s=sim.s4;if(sim.reactorTripped&&s.atmFlow>=60&&s.afwFlow>=50)return null;if(!sim.reactorTripped){const toTrip=Math.max(0,(25-s.condenser)/.29);return toTrip+Math.max(0,(335-s.rcsTemp)/.06)}return Math.max(0,Math.min((335-s.rcsTemp)/.06,(s.sgLevel-25)/.035))}
 if(id===5){if(sim.s5.busA>=95||sim.s5.busB>=95)return null;return Math.max(0,(330-sim.s5.rcsTemp)/.06)}
 if(id===6){const total=sim.s6.afwA+sim.s6.afwB+sim.s6.afwC;if(total>=80)return null;return Math.max(0,(330-sim.s6.rcsTemp)/.08)}
 if(id===7)return null;
 if(id===8){if(sim.rcpA.state==='RUNNING'||sim.rcpA.state==='STARTING'||sim.s8.rcsTrend<=0)return null;const rate=Math.max(.001,sim.s8.rcsTrend);return Math.max(0,(330-sim.s8.rcsTemp)/rate)}
 if(id===9){const s=sim.s9;if(s.letdownIso==='CLOSED')return null;const injection=(sim.reactorTripped?s.siFlow/100*.10:0),loss=Math.max(.001,s.leakRate-injection);return Math.max(0,(s.inventory-30)/loss)}
 if(id===10){const s=sim.s10;if(s.ccwFlow>=60&&s.ccwTrend>=0)return null;if(!sim.reactorTripped){const toTrip=Math.max(0,(s.ccwFlow-15)/.20);return toTrip+Math.max(0,(335-s.rcsTemp)/.055)}const rate=s.ccwFlow>=60?-.08:.055;if(rate<=0)return null;return Math.max(0,(335-s.rcsTemp)/rate)}
 return null}
function plantTimeDisplay(pm,tl){if(pm===null||!Number.isFinite(pm))return '--:--';if(tl!==null&&Number.isFinite(tl)&&pm>tl)return '&gt; TIME LIMIT';return fmtPlantClock(pm)}
function updateTimeStatus(){if(!timeStatus)return;if(!stage||!sim){timeStatus.innerHTML='<span>PLANT TIME&nbsp;&nbsp;--:--</span><span>TIME LIMIT&nbsp;&nbsp;--:--</span>';return}const pm=plantMarginMinutes(),tl=timeLimitRemaining(),plantText=plantTimeDisplay(pm,tl),plantCritical=pm!==null&&(tl===null||pm<=tl)&&pm<=60;timeStatus.innerHTML=`<span${plantCritical?' class="critical"':''}>PLANT TIME&nbsp;&nbsp;${plantText}</span><span${tl!==null&&tl<=60?' class="critical"':''}>TIME LIMIT&nbsp;&nbsp;${fmtPlantClock(tl)}</span>`}
function insert(cmd){input.value=cmd;input.focus();input.setSelectionRange(input.value.length,input.value.length)}
function decayHeat(seconds){const pts=[[0,6.5],[60,4.0],[300,2.8],[600,2.3],[1800,1.8]];for(let i=1;i<pts.length;i++){if(seconds<=pts[i][0]){const [t0,v0]=pts[i-1],[t1,v1]=pts[i];const q=(seconds-t0)/(t1-t0);return v0+(v1-v0)*q}}return 1.8}
function flowFromFrv(pos){if(pos<=10)return pos*2.5;if(pos<=25)return 25+(pos-10)*(35/15);if(pos<=50)return 60+(pos-25)*(40/25);return Math.min(105,100+(pos-50)*0.5)}
function initialSim(id){const tripped=[3,5,6,8].includes(id);return {
  lastTick:Date.now(),simTime:0,reactorTripped:tripped,reactorTripAt:tripped?0:null,turbineTripped:[3,5,6,8].includes(id),
  rcpA:{state:'RUNNING',speed:id===1?97:100,flow:id===1?95:100,vib:id===1?1.8:1.0,bearing:id===1?75:70,stopAt:null},
  s0:{rcsTemp:320,rcsTrend:0,sgB:55,sgTrend:0,frvCmd:'AUTO',frvActual:50,fwB:100,steam:100,afwBPump:'STANDBY',afwBFlow:0,steamDumpCmd:'AUTO',steamDumpActual:0,atmCmd:'STANDBY',atmActual:0,condenser:7,busA:100,busB:100,edgA:{state:'STANDBY',speed:0,breaker:'OPEN'},edgB:{state:'STANDBY',speed:0,breaker:'OPEN'}},
  s1:{thermalRisk:0.18,rcsTemp:320},
  s2:{frvCmd:'AUTO',frvActual:48,fw:95,sg:56,steam:100,trend:-.03,recoveryAt:null,afwFlow:0,afwPump:'STANDBY',autoTripReported:false},
  s3:{sgPressure:7.35,sgLevel:52,sgTrend:0,afwFlow:35,steamDumpCmd:'AUTO',steamDumpActual:30,rcsTemp:320},
  s4:{condenser:12,steamDumpCmd:'AUTO',steamDumpActual:0,steamDumpFlow:0,atmCmd:'STANDBY',atmActual:0,atmFlow:0,afwFlow:0,sgPressure:6.9,sgLevel:56,sgTrend:0,rcsTemp:320,tripReported:false},
  s5:{offsite:0,busA:0,busB:0,edgA:{state:'CRANKING',speed:0,breakerCmd:'AUTO',breaker:'OPEN',closeAt:null},edgB:{state:'CRANKING',speed:0,breakerCmd:'AUTO',breaker:'OPEN',closeAt:null},rcsTemp:318},
  s6:{mfw:0,afwA:100,afwB:0,afwC:100,afwAPump:'RUNNING',afwBPump:'RUNNING',afwCPump:'RUNNING',afwValveCmd:'CLOSED',afwValveActual:0,sgA:55,sgB:55,sgC:55,sgTrend:0,rcsTemp:318},
  s7:{trueLevel:54.5,ch1:18,ch2:54.8,ch3:54.1,diagState:'IDLE',diagAt:null,diagComplete:false,reported:false},
  s8:{decayHeat:6.5,rcsTemp:320,rcsTrend:0,sgLevel:55},
  s9:{pressure:15.5,pzrLevel:52,inventory:100,leakRate:.30,letdownFlow:160,letdownIso:'OPEN',siFlow:0,rcsTemp:320,autoReported:false},
  s10:{ccwA:'FAILED',ccwB:'STANDBY',ccwBSpeed:0,ccwFlow:25,ccwTrend:-.20,headerTemp:45,rcpBearing:78,afwBearing:75,edgTemp:82,rcsTemp:320,autoReported:false},
  history:{nextSample:10,data:{}}
}}
function pushHist(key,t,v){const a=sim.history.data[key]||(sim.history.data[key]=[]);a.push({t,v});if(a.length>18)a.shift()}
function seedHistory(id){const seed=(key,arr)=>arr.forEach(([t,v])=>pushHist(key,t,v));
 if(id===1){seed('RCP-A FLOW',[[-300,100],[-240,99],[-180,98],[-120,96],[-60,95]]);seed('RCP-A VIBRATION',[[-300,1.1],[-240,1.3],[-180,1.5],[-120,1.7],[-60,1.8]]);seed('RCP-A SPEED',[[-300,100],[-240,99],[-180,98],[-120,97],[-60,97]])}
 if(id===2){seed('SG-B LEVEL',[[-240,60],[-180,59],[-120,58],[-60,57],[0,56]]);seed('FRV-B POSITION',[[-240,52],[-180,51],[-120,50],[-60,49],[0,48]])}
 if(id===4)seed('CONDENSER PRESSURE',[[-180,7],[-120,9],[-60,11],[0,12]]);
 if(id===5)seed('BUS-B VOLTAGE',[[-20,100],[-10,0],[0,0]]);
 if(id===6)seed('AFW-B FLOW',[[-60,0],[-30,0],[0,0]]);
 if(id===7){seed('SG-B-LVL-CH1 LEVEL',[[-180,54],[-120,18],[-60,18],[0,18]]);seed('SG-B-LVL-CH2 LEVEL',[[-180,56],[-120,55],[-60,54.8],[0,54.8]])}
 if(id===9){seed('RCS PRESSURE',[[-180,15.5],[-120,15.5],[-60,15.5],[0,15.5]]);seed('PZR LEVEL',[[-180,52],[-120,52],[-60,52],[0,52]])}
 if(id===10)seed('CCW FLOW',[[-180,100],[-120,100],[-60,100],[0,25]]);
}
function sampleHistory(t){const id=stage.id;if(id===1){pushHist('RCP-A FLOW',t,sim.rcpA.flow);pushHist('RCP-A VIBRATION',t,sim.rcpA.vib);pushHist('RCP-A SPEED',t,sim.rcpA.speed)}
 if(id===2){pushHist('SG-B LEVEL',t,sim.s2.sg);pushHist('FRV-B POSITION',t,sim.s2.frvActual)}
 if(id===4)pushHist('CONDENSER PRESSURE',t,sim.s4.condenser);
 if(id===5)pushHist('BUS-B VOLTAGE',t,sim.s5.busB);
 if(id===6)pushHist('AFW-B FLOW',t,sim.s6.afwB);
 if(id===7){pushHist('SG-B-LVL-CH1 LEVEL',t,sim.s7.ch1);pushHist('SG-B-LVL-CH2 LEVEL',t,sim.s7.ch2)}
 if(id===9){pushHist('RCS PRESSURE',t,sim.s9.pressure);pushHist('PZR LEVEL',t,sim.s9.pzrLevel)}
 if(id===10)pushHist('CCW FLOW',t,sim.s10.ccwFlow);
}
function clearTutorialUI(){if(tutorialCoach){tutorialCoach.remove();tutorialCoach=null}if(tutorialHighlight){tutorialHighlight.classList.remove('tutorial-highlight');tutorialHighlight=null}}
function tutorialTarget(which){
 if(!which)return null;
 if(which==='time')return timeStatus;
 if(which==='terminal')return document.querySelector('.terminal-panel');
 if(which==='manual')return document.querySelector('.right-panel');
 if(which==='input')return input;
 if(which.startsWith('selector:'))return document.querySelector(which.slice(9));
 return null
}
function showTutorial(text,target=null,button=false){clearTutorialUI();const el=document.createElement('div');el.className='tutorial-coach';el.innerHTML=`<div class="tutorial-label">TUTORIAL</div><div class="tutorial-text"></div>${button?'<button type="button">次へ</button>':''}`;el.querySelector('.tutorial-text').textContent=text;document.body.appendChild(el);tutorialCoach=el;const t=tutorialTarget(target);if(t){t.classList.add('tutorial-highlight');tutorialHighlight=t;if(typeof t.scrollIntoView==='function'&&target?.startsWith?.('selector:'))t.scrollIntoView({block:'nearest',inline:'nearest'})}if(button)el.querySelector('button').onclick=()=>tutorialNext();}
function tutorialJump(nextStep){tutorialStep=nextStep-1;tutorialNext()}
function tutorialNext(){if(!isTutorial())return;tutorialStep++;
 if(tutorialStep===1)showTutorial('左がターミナル、右が運転・保守マニュアルです。異常を調査し、必要な設備だけを操作して安全側へ収束させます。','terminal',true);
 else if(tutorialStep===2)showTutorial('PLANT TIME は設備が物理的に持つ推定猶予で、状態に応じて増減します。TIME LIMIT は本編で共通8時間の復旧・解明期限です。物理的な猶予がTIME LIMITより長い場合、PLANT TIMEは「> TIME LIMIT」と表示されます。','time',true);
 else if(tutorialStep===3)showTutorial('まず全体状態を確認します。入力欄へ STATUS と入力して実行してください。','input');
 else if(tutorialStep===4)showTutorial('PRIMARY が WARNING です。今度はマニュアルを使います。右上の「索引」ボタンを押してください。','selector:[data-nav="index"]');
 else if(tutorialStep===5)showTutorial('索引から「RCP（原子炉冷却材ポンプ）」を開いてください。','selector:[data-page="rcp"]');
 else if(tutorialStep===6)showTutorial('STATUS PRIMARY を実行してください。直接入力しても、強調されたマニュアルのボタンをクリックして入力欄へ挿入しても構いません。','selector:[data-command="STATUS PRIMARY"]');
 else if(tutorialStep===7)showTutorial('次はRCP-Aを個別に調べます。READ RCP-A を実行してください。直接入力でも、マニュアルのボタンからでも進めます。','selector:[data-command="READ RCP-A"]');
 else if(tutorialStep===8)showTutorial('警報も調査材料です。ALARM を実行してみてください。','input');
 else if(tutorialStep===9)showTutorial('次の操作はCONTROL資料から探します。まず「索引」ボタンを押してください。','selector:[data-nav="index"]');
 else if(tutorialStep===10)showTutorial('索引から「コマンド — CONTROL」を開いてください。','selector:[data-page="cmd-control"]');
 else if(tutorialStep===11)showTutorial('CONTROL REACTOR TRIP を実行してください。直接入力でも、強調されたボタンをクリックして入力欄へ挿入しても構いません。','selector:[data-command="CONTROL REACTOR TRIP"]');
 else if(tutorialStep===12)showTutorial('続いて故障したRCP-Aを停止します。CONTROL RCP-A STOP を実行してください。入力方法はどちらでも構いません。','selector:[data-command="CONTROL RCP-A STOP"]');
 else if(tutorialStep===13)showTutorial('操作は完了です。設備のACTUAL状態と温度が安全側へ収束するまで、STATUS / READで確認しながら待ってください。↑キーを押すと、以前入力したコマンドを呼び出せます。','time');
}
function tutorialOnCommandExecuted(up){if(!isTutorial())return;
 if(tutorialStep===3&&up==='STATUS')tutorialJump(4);
 else if(tutorialStep===6&&up==='STATUS PRIMARY')tutorialJump(7);
 else if(tutorialStep===7&&up==='READ RCP-A')tutorialJump(8);
 else if(tutorialStep===8&&up==='ALARM')tutorialJump(9);
 else if(tutorialStep===11&&up==='CONTROL REACTOR TRIP')tutorialJump(12);
 else if(tutorialStep===12&&up==='CONTROL RCP-A STOP')tutorialJump(13)
}
function tutorialHooks(){return {
 onPage(id){if(!isTutorial())return;
   if(tutorialStep===4&&id==='index')tutorialJump(5);
   else if(tutorialStep===5&&id==='rcp')tutorialJump(6);
   else if(tutorialStep===9&&id==='index')tutorialJump(10);
   else if(tutorialStep===10&&id==='cmd-control')tutorialJump(11)
 },
 onCommand(cmd){if(!isTutorial())return;/* command buttons only insert text; execution drives progress */}
}}
function showSelect(){clearTutorialUI();mode='stage';stage=null;finished=false;finishAt=0;sim=null;stableSince=null;controlCount=0;lastCommand=null;lastCommandAt=null;lastControl=null;lastControlAt=null;if(timer)clearInterval(timer);updateTimeStatus();returnBtn.classList.add('hidden');rightTitle.textContent='STAGE SELECT';right.className='right-body';right.innerHTML='<div class="stage-select-head"><div><h1>SELECT MODE / STAGE</h1></div></div><div id="modeGrid" class="stage-grid mode-grid"></div><div id="stageGrid" class="stage-grid"></div>';const mg=right.querySelector('#modeGrid');[['TUTORIAL',()=>startTutorial()],['SIMULATION',()=>startSimulation()]].forEach(([name,fn])=>{const d=document.createElement('div');d.className='stage-card special-card';d.innerHTML=`<h3>${name}</h3><button>START</button>`;d.querySelector('button').onclick=fn;mg.appendChild(d)});const grid=right.querySelector('#stageGrid');STAGES.forEach(s=>{const d=document.createElement('div');d.className='stage-card';d.innerHTML=`<h3>STAGE-${s.id}</h3><button>START</button>`;d.querySelector('button').onclick=()=>startStage(s,'stage');grid.appendChild(d)});out.innerHTML='';p('TERMINAL READY');p('SELECT TUTORIAL / SIMULATION / STAGE FROM THE RIGHT PANEL.');}
function startStage(s,newMode='stage'){clearTutorialUI();mode=newMode;stage=s;startAt=Date.now();finishAt=0;finished=false;controls=new Set();controlCount=0;stableSince=null;lastCommand=null;lastCommandAt=null;lastControl=null;lastControlAt=null;simulationFailureLatched=false;sim=initialSim(s.id);seedHistory(s.id);debugLog=[];debugLogNextSample=5;debugLogLastSafe=baseSafeState();debugLogAdd(`${stageLabel()} START`);out.innerHTML='';returnBtn.classList.remove('hidden');rightTitle.textContent=`OPERATING & MAINTENANCE MANUAL // ${stageLabel()}`;Manual.render(right,insert,'cover',isTutorial()?tutorialHooks():null);p('!! EVENT !!','alarm');p('');p(`${stageLabel()} INITIALIZED`);p(s.brief,'alarm');p('');updateTimeStatus();if(timer)clearInterval(timer);timer=setInterval(tick,1000);if(isTutorial()){tutorialStep=0;showTutorial('このチュートリアルでは、実際の異常を解決しながらゲームの流れ・画面・マニュアルの使い方を確認します。','terminal',true)}}
function startTutorial(){startStage({...STAGES[0],brief:'PRIMARY SYSTEM WARNING'},'tutorial')}
function startSimulation(){startStage({id:0,difficulty:'TRAINING',devTitle:'正常運転シミュレーション',brief:'NORMAL OPERATION — FREE CONTROL TEST',stable:0,minClear:0},'simulation');p('SIMULATION MODE: NO CLEAR / NO TIME LIMIT');p('TYPE RESET TO RESTORE NORMAL INITIAL CONDITIONS.');}
function resetSimulation(){if(!isSimulation())return false;sim=initialSim(0);seedHistory(0);stableSince=null;simulationFailureLatched=false;debugLogAdd('SIMULATION RESET');p('SIMULATION RESET: NORMAL OPERATING STATE RESTORED','ok');updateTimeStatus();return true}
function tripReactor(){if(!sim.reactorTripped){sim.reactorTripped=true;sim.reactorTripAt=sim.simTime}}
function updateRcpA(dt,mode){const r=sim.rcpA;
 if(r.state==='RUNNING'){if(mode==='DEGRADE'){r.speed=clamp(r.speed-.06*dt,68,100);r.flow=clamp(r.flow-.17*dt,55,100);r.vib=clamp(r.vib+.007*dt,1,4.5);r.bearing=clamp(r.bearing+.045*dt,70,94)}}
 else if(r.state==='COASTDOWN'){r.speed=clamp(r.speed-7*dt,0,100);r.flow=clamp(Math.max(8,r.speed),8,100);r.vib=clamp(r.vib-.08*dt,1.0,4.5);r.bearing=clamp(r.bearing-.10*dt,68,94);if(r.speed<=1){r.speed=0;r.flow=8;r.state='STOPPED'}}
 else if(r.state==='STOPPED'){r.vib=clamp(r.vib-.03*dt,1.0,4.5);r.bearing=clamp(r.bearing-.08*dt,68,94)}
 else if(r.state==='STARTING'){r.speed=clamp(r.speed+10*dt,0,100);r.flow=clamp(Math.max(8,r.speed),8,100);r.vib=approach(r.vib,1.0,.08,dt);r.bearing=approach(r.bearing,70,.08,dt);if(r.speed>=99){r.speed=100;r.flow=100;r.state='RUNNING'}}
}
function advanceStep(dt){sim.simTime+=dt;const t=sim.simTime;
 if(stage.id===0){const s=sim.s0;updateRcpA(dt,'NORMAL');if(s.frvCmd==='OPEN')s.frvActual=approach(s.frvActual,60,1.4,dt);else if(s.frvCmd==='CLOSE')s.frvActual=approach(s.frvActual,0,1.8,dt);else s.frvActual=approach(s.frvActual,50,.5,dt);s.fwB=approach(s.fwB,flowFromFrv(s.frvActual),3,dt);const oldSg=s.sgB;if(!sim.reactorTripped){s.sgTrend=(s.fwB-s.steam)*.006;s.sgB=clamp(s.sgB+s.sgTrend*dt,0,100);if((sim.rcpA.flow<75||s.sgB<=50)){tripReactor();sim.turbineTripped=true;s.afwBPump='RUNNING';p('AUTO ACTION: REACTOR TRIP / PROTECTION ACTUATION','alarm')}}else{s.afwBFlow=approach(s.afwBFlow,s.afwBPump==='RUNNING'?80:0,2,dt);s.steamDumpActual=approach(s.steamDumpActual,s.steamDumpCmd==='OPEN'?100:0,3,dt);s.atmActual=approach(s.atmActual,s.atmCmd==='OPEN'?100:0,3,dt);const adequate=(s.steamDumpActual>=60||s.atmActual>=60)&&s.afwBFlow>=50&&sim.rcpA.state!=='STOPPED';const old=s.rcsTemp;s.rcsTemp=clamp(s.rcsTemp+(adequate?-.07:.05)*dt,295,340);s.rcsTrend=(s.rcsTemp-old)/dt;s.sgTrend=(s.afwBFlow-60)*.002;s.sgB=clamp(s.sgB+s.sgTrend*dt,0,100)}if(!sim.reactorTripped&&sim.rcpA.state!=='RUNNING')s.rcsTemp=clamp(s.rcsTemp+.08*dt,295,340);if(sim.reactorTripped&&s.afwBPump!=='RUNNING')s.afwBFlow=approach(s.afwBFlow,0,3,dt);}
 if(stage.id===1){const td=isTutorial()?dt*.25:dt;updateRcpA(td,'DEGRADE');const r=sim.rcpA,s=sim.s1;if(!sim.reactorTripped&&r.flow<75){tripReactor();sim.turbineTripped=true;p('AUTO ACTION: RPS REACTOR TRIP — PRIMARY FLOW VERY LOW','alarm')}
   if(!sim.reactorTripped){const forcedLoss=r.state==='RUNNING'?Math.max(0,90-r.flow)/90:1;s.thermalRisk=clamp(s.thermalRisk+(0.001+forcedLoss*.015)*td,0,1.2);s.rcsTemp=clamp(s.rcsTemp+(r.state==='RUNNING'?forcedLoss*.05:.12)*td,300,340)}
   else{const secured=r.state==='STOPPED';s.thermalRisk=clamp(s.thermalRisk-(secured?.010:.004)*dt,0,1.2);s.rcsTemp=clamp(s.rcsTemp-(secured?.09:.04)*dt,300,340)}}
 if(stage.id===2){const s=sim.s2;if(s.frvCmd==='OPEN')s.frvActual=approach(s.frvActual,60,1.4,dt);else if(s.frvCmd==='CLOSE')s.frvActual=approach(s.frvActual,0,1.8,dt);else s.frvActual=clamp(s.frvActual-.11*dt,0,100);const target=flowFromFrv(s.frvActual);s.fw+=(target-s.fw)*Math.min(1,.35*dt);s.fw=clamp(s.fw,0,105);
   if(!sim.reactorTripped){s.trend=(s.fw-s.steam)*.006;s.sg=clamp(s.sg+s.trend*dt,0,100);if(s.sg<=50){tripReactor();sim.turbineTripped=true;s.autoTripReported=true;s.afwPump='RUNNING';p('AUTO ACTION: REACTOR TRIP / AFW START — SG-B LEVEL LOW-LOW','alarm')}}
   if(sim.reactorTripped){s.afwFlow=approach(s.afwFlow,s.afwPump==='RUNNING'?80:0,1.5,dt);s.steam=approach(s.steam,40,1.5,dt);if(s.afwFlow<10&&s.frvCmd!=='OPEN')s.trend=-.16;else{s.trend=(s.afwFlow-80)*.003+(55-s.sg)*.015;if(s.frvCmd==='OPEN')s.trend+=Math.max(0,s.fw-60)*.0005}s.sg=clamp(s.sg+s.trend*dt,0,100)}}
 if(stage.id===3){const s=sim.s3;s.afwFlow=approach(s.afwFlow,80,1.2,dt);s.steamDumpActual=approach(s.steamDumpActual,s.steamDumpCmd==='OPEN'?100:s.steamDumpCmd==='CLOSE'?0:30,2,dt);const adequate=s.steamDumpActual>=70&&s.afwFlow>=60;const old=s.sgLevel;if(adequate){s.sgPressure=approach(s.sgPressure,6.9,.02,dt);s.sgLevel+=(55-s.sgLevel)*.012*dt;s.rcsTemp+=(309-s.rcsTemp)*.012*dt}else{s.sgPressure=clamp(s.sgPressure+.004*dt,6.7,7.8);s.sgLevel=clamp(s.sgLevel-.015*dt,0,100);s.rcsTemp=clamp(s.rcsTemp+.065*dt,300,340)}s.sgTrend=(s.sgLevel-old)/dt}
 if(stage.id===4){const s=sim.s4;s.condenser=clamp(s.condenser+.29*dt,0,40);if(!sim.turbineTripped&&s.condenser>=25){sim.turbineTripped=true;tripReactor();s.tripReported=true;p('AUTO ACTION: TURBINE TRIP / REACTOR TRIP — CONDENSER VACUUM LOW','alarm')}
   s.steamDumpActual=approach(s.steamDumpActual,s.steamDumpCmd==='OPEN'?100:s.steamDumpCmd==='CLOSE'?0:0,4,dt);const condenserAvail=clamp((25-s.condenser)/15,0,1);s.steamDumpFlow=s.steamDumpActual*condenserAvail;
   s.atmActual=approach(s.atmActual,s.atmCmd==='OPEN'?100:0,4,dt);s.atmFlow=s.atmActual;
   if(sim.reactorTripped)s.afwFlow=approach(s.afwFlow,80,1.5,dt);const adequate=sim.reactorTripped&&s.atmFlow>=60&&s.afwFlow>=50;const old=s.sgLevel;if(sim.reactorTripped){if(adequate){s.sgPressure=approach(s.sgPressure,6.9,.02,dt);s.sgLevel+=(55-s.sgLevel)*.012*dt;s.rcsTemp+=(309-s.rcsTemp)*.012*dt}else{s.sgPressure=clamp(s.sgPressure+.012*dt,6.7,7.8);s.sgLevel=clamp(s.sgLevel-.035*dt,0,100);s.rcsTemp=clamp(s.rcsTemp+.06*dt,300,340)}}s.sgTrend=(s.sgLevel-old)/dt}
 if(stage.id===5){const s=sim.s5;s.edgA.speed=clamp(s.edgA.speed+10*dt,0,100);s.edgB.speed=clamp(s.edgB.speed+10*dt,0,100);if(s.edgA.speed>=100)s.edgA.state='RUNNING';if(s.edgB.speed>=100)s.edgB.state='RUNNING';if(t>=15&&s.edgA.breaker==='OPEN'&&s.edgA.breakerCmd==='AUTO'){s.edgA.breaker='CLOSED'}if(s.edgA.breakerCmd==='CLOSE'&&s.edgA.closeAt!==null&&t-s.edgA.closeAt>=2)s.edgA.breaker='CLOSED';if(s.edgB.breakerCmd==='CLOSE'&&s.edgB.closeAt!==null&&t-s.edgB.closeAt>=2)s.edgB.breaker='CLOSED';s.busA=approach(s.busA,s.edgA.breaker==='CLOSED'?100:0,25,dt);s.busB=approach(s.busB,s.edgB.breaker==='CLOSED'?100:0,25,dt);const anySafetyBus=s.busA>=95||s.busB>=95;s.rcsTemp=clamp(s.rcsTemp+(anySafetyBus?-.02:.06)*dt,300,335)}
 if(stage.id===6){const s=sim.s6;s.afwA=approach(s.afwA,s.afwAPump==='RUNNING'?100:0,5,dt);s.afwC=approach(s.afwC,s.afwCPump==='RUNNING'?100:0,5,dt);s.afwValveActual=approach(s.afwValveActual,s.afwValveCmd==='OPEN'?100:0,5,dt);s.afwB=approach(s.afwB,s.afwBPump==='RUNNING'?s.afwValveActual:0,5,dt);s.sgA=approach(s.sgA,s.afwA>=60?52:35,.03,dt);s.sgC=approach(s.sgC,s.afwC>=60?52:35,.03,dt);s.sgTrend=(s.afwB>=60?.08:-.12);s.sgB=clamp(s.sgB+s.sgTrend*dt,0,100);const total=s.afwA+s.afwB+s.afwC;const tempRate=total>=160?-.025:total>=80?.005:.08;s.rcsTemp=clamp(s.rcsTemp+tempRate*dt,300,335)}
 if(stage.id===7){const s=sim.s7;s.trueLevel=clamp(s.trueLevel-.003*dt,53,55);s.ch1=18;s.ch2=s.trueLevel+.3;s.ch3=s.trueLevel-.4;if(s.diagState==='RUNNING'&&s.diagAt!==null&&t-s.diagAt>=20&&!s.diagComplete){s.diagState='COMPLETE';s.diagComplete=true;p('INSTRUMENT DIAGNOSTIC COMPLETE','ok');block(['','SG-B-LVL-CH1   FAILED — STUCK LOW','SG-B-LVL-CH2   NORMAL','SG-B-LVL-CH3   NORMAL','','MAINTENANCE NOTIFICATION REQUIRED','TYPE: REPORT <DEVICE>'],'alarm')}}
 if(stage.id===8){updateRcpA(dt,'NORMAL');const s=sim.s8,old=s.rcsTemp;s.decayHeat=decayHeat(t);if(sim.rcpA.state==='RUNNING')s.rcsTemp=clamp(s.rcsTemp-.07*dt,295,330);else if(sim.rcpA.state==='STARTING')s.rcsTemp=clamp(s.rcsTemp-.025*dt,295,330);else if(sim.rcpA.state==='COASTDOWN')s.rcsTemp=clamp(s.rcsTemp+.015*dt,295,330);else s.rcsTemp=clamp(s.rcsTemp+(s.decayHeat>4.5?.03:-.01)*dt,295,330);s.rcsTrend=(s.rcsTemp-old)/dt;s.sgLevel=clamp(s.sgLevel-.003*dt,53,55)}
 if(stage.id===9){const s=sim.s9;if(s.letdownIso==='OPEN'){s.pressure=clamp(s.pressure-(sim.reactorTripped?.004:.015)*dt,10,16);const inj=sim.reactorTripped?s.siFlow/100*.10:0;s.inventory=clamp(s.inventory-(s.leakRate-inj)*dt,0,110);s.pzrLevel=clamp(s.pzrLevel-(sim.reactorTripped?.08:.18)*dt,0,100);s.letdownFlow=160}else{s.leakRate=0;s.letdownFlow=0;if(sim.reactorTripped){s.inventory=approach(s.inventory,85,.16,dt);s.pzrLevel=approach(s.pzrLevel,50,.14,dt);s.pressure=approach(s.pressure,15.2,.025,dt)}}if(!sim.reactorTripped&&s.pressure<=14.8){tripReactor();sim.turbineTripped=true;s.autoReported=true;p('AUTO ACTION: REACTOR TRIP / SAFETY INJECTION — RCS PRESSURE LOW','alarm')}if(sim.reactorTripped)s.siFlow=approach(s.siFlow,100,2,dt);if(sim.reactorTripped)s.rcsTemp=clamp(s.rcsTemp+(s.letdownIso==='CLOSED'?-.08:.015)*dt,300,340);else s.rcsTemp=approach(s.rcsTemp,320,.02,dt)}
 if(stage.id===10){const s=sim.s10;if(s.ccwB==='STARTING'){s.ccwBSpeed=clamp(s.ccwBSpeed+5*dt,0,100);if(s.ccwBSpeed>=100)s.ccwB='RUNNING'}const target=s.ccwB==='RUNNING'?100:0;const oldFlow=s.ccwFlow;s.ccwFlow=approach(s.ccwFlow,target,s.ccwB==='RUNNING'?2.5:.20,dt);s.ccwTrend=(s.ccwFlow-oldFlow)/dt;const deficit=Math.max(0,100-s.ccwFlow)/100;s.headerTemp=clamp(s.headerTemp+(s.ccwFlow>=60?-.10:.06+deficit*.04)*dt,30,100);s.rcpBearing=clamp(s.rcpBearing+(s.ccwFlow>=60?-.10:.04+deficit*.06)*dt,65,140);s.afwBearing=clamp(s.afwBearing+(s.ccwFlow>=60?-.08:.035+deficit*.055)*dt,65,140);s.edgTemp=clamp(s.edgTemp+(s.ccwFlow>=60?-.12:.05+deficit*.07)*dt,60,150);if(!sim.reactorTripped&&s.ccwFlow<=15){tripReactor();sim.turbineTripped=true;s.autoReported=true;p('AUTO ACTION: REACTOR TRIP — SUPPORT COOLING LOW','alarm')}if(sim.reactorTripped)s.rcsTemp=clamp(s.rcsTemp+(s.ccwFlow>=60?-.08:.055)*dt,300,340)}
 while(sim.history.nextSample<=sim.simTime){sampleHistory(sim.history.nextSample);sim.history.nextSample+=10}
}
function updateSim(){if(!stage||finished||!sim)return;const now=Date.now();let dt=(now-sim.lastTick)/1000/(TIME_CONFIG?.realSecondsPerPlantMinute??1);if(dt<=0)return;sim.lastTick=now;while(dt>0){const step=Math.min(.5,dt);advanceStep(step);dt-=step}debugSampleDue();updateTimeStatus()}
function currentFissionPower(){if(!sim.reactorTripped)return 100;const x=Math.max(0,sim.simTime-(sim.reactorTripAt??0));if(x<2)return Math.max(5,100-47.5*x);if(x<5)return Math.max(.8,5-(x-2)*1.4);return 0}
function currentDecay(){if(!sim.reactorTripped)return null;return decayHeat(Math.max(0,sim.simTime-(sim.reactorTripAt??0)))}
function rcsTemp(){const id=stage.id;if(id===0)return sim.s0.rcsTemp;if(id===1)return sim.s1.rcsTemp;if(id===3)return sim.s3.rcsTemp;if(id===4)return sim.s4.rcsTemp;if(id===5)return sim.s5.rcsTemp;if(id===6)return sim.s6.rcsTemp;if(id===8)return sim.s8.rcsTemp;if(id===9)return sim.s9.rcsTemp;if(id===10)return sim.s10.rcsTemp;return 320}
function sgData(which){const d={level:56,pressure:6.9,mfw:100,afw:0,steam:100};const id=stage.id;if(id===0&&which==='B'){d.level=sim.s0.sgB;d.mfw=sim.s0.fwB;d.afw=sim.s0.afwBFlow;d.steam=sim.s0.steam}if(id===2&&which==='B'){d.level=sim.s2.sg;d.mfw=sim.s2.fw;d.afw=sim.s2.afwFlow;d.steam=sim.s2.steam}if(id===3){d.level=sim.s3.sgLevel;d.pressure=sim.s3.sgPressure;d.mfw=0;d.afw=sim.s3.afwFlow}if(id===4){d.level=sim.s4.sgLevel;d.pressure=sim.s4.sgPressure;d.mfw=0;d.afw=sim.s4.afwFlow}if(id===6){d.level=which==='A'?sim.s6.sgA:which==='B'?sim.s6.sgB:sim.s6.sgC;d.mfw=0;d.afw=which==='A'?sim.s6.afwA:which==='B'?sim.s6.afwB:sim.s6.afwC}if(id===7&&which==='B')d.level=sim.s7.trueLevel;if(id===8&&which==='B')d.level=sim.s8.sgLevel;return d}
function systemStates(){const id=stage.id;const sA=sgData('A'),sB=sgData('B'),sC=sgData('C');const steamWarn=[sA,sB,sC].some(s=>s.level<50||s.level>60||s.pressure<6.7||s.pressure>7.1)||id===7;let primary='NORMAL';if(id===0&&(sim.rcpA.state!=='RUNNING'||sim.s0.rcsTemp>325))primary='WARNING';if(id===1&&(sim.rcpA.speed<98||sim.rcpA.flow<95||sim.rcpA.vib>1.4))primary='WARNING';if(id===8&&sim.rcpA.state!=='RUNNING')primary='WARNING';if(id===9&&(sim.s9.pressure<15.2||sim.s9.inventory<95))primary='WARNING';let fw='NORMAL';if(id===0&&(Math.abs(sim.s0.fwB-100)>5||sim.s0.afwBFlow>0))fw='WARNING';if(id===2&&(Math.abs(sim.s2.fw-100)>5||sim.reactorTripped))fw='WARNING';if([3,4,6].includes(id))fw='WARNING';let elec='NORMAL';if(id===5&&(sim.s5.offsite<95||sim.s5.busA<95||sim.s5.busB<95))elec='WARNING';let instrument='NORMAL';if(id===7)instrument=sim.s7.reported?'CH1 OUT OF SERVICE':sim.s7.diagComplete?'FAULT CONFIRMED':'DISAGREEMENT';let support='NORMAL';if(id===10&&sim.s10.ccwFlow<90)support='WARNING';return {reactor:sim.reactorTripped?'TRIPPED':'NORMAL',primary,steam:steamWarn?'WARNING':'NORMAL',feedwater:fw,electrical:elec,safety:sim.reactorTripped?'ACTIVE':'STANDBY',instrument,support}}
function status(name){updateSim();const st=systemStates(),id=stage.id;if(!name){block([`REACTOR       ${st.reactor}`,`PRIMARY       ${st.primary}`,`STEAM         ${st.steam}`,`FEEDWATER     ${st.feedwater}`,`ELECTRICAL    ${st.electrical}`,`SAFETY        ${st.safety}`,`INSTRUMENT    ${st.instrument}`,`SUPPORT       ${st.support}`]);return}
 if(name==='reactor')block(['REACTOR',`STATE        ${sim.reactorTripped?'TRIPPED':'RUNNING'}`,`POWER        ${currentFissionPower().toFixed(currentFissionPower()<10?1:0)} %`,`DECAY HEAT   ${sim.reactorTripped?currentDecay().toFixed(1)+' %':'--'}`]);
 else if(name==='primary'){const press=id===9?sim.s9.pressure:15.5;block(['PRIMARY SYSTEM',`LOOP-A       ${(id===1||(id===8||id===0)&&sim.rcpA.state!=='RUNNING')?'WARNING':'NORMAL'}`,`LOOP-B       NORMAL`,`LOOP-C       NORMAL`,`RCS PRESS    ${press.toFixed(1)} MPa`,`HOT LEG      ${rcsTemp().toFixed(0)} C`])}
 else if(name==='steam'){const a=sgData('A'),b=sgData('B'),c=sgData('C');block(['STEAM / SG',`SG-A LEVEL   ${a.level.toFixed(0)} %`,`SG-B LEVEL   ${id===7?`${sim.s7.ch1.toFixed(0)} / ${sim.s7.ch2.toFixed(0)} / ${sim.s7.ch3.toFixed(0)}`:b.level.toFixed(0)} %`,`SG-C LEVEL   ${c.level.toFixed(0)} %`,`SG PRESS     ${b.pressure.toFixed(2)} MPa`])}
 else if(name==='feedwater'){if(id===0)block(['FEEDWATER',`MFW-B FLOW   ${sim.s0.fwB.toFixed(0)} %`,`AFW-B FLOW   ${sim.s0.afwBFlow.toFixed(0)} % AFW-RATED`,`AFW DEMAND   ${sim.reactorTripped?'YES':'NO'}`]);else if(id===2&&sim.reactorTripped)block(['FEEDWATER',`MFW-B FLOW   ${sim.s2.fw.toFixed(0)} %`,`AFW FLOW     ${sim.s2.afwFlow.toFixed(0)} % AFW-RATED`,'AFW DEMAND   YES']);else if(id===6)block(['FEEDWATER','MFW-A FLOW   0 %','MFW-B FLOW   0 %','MFW-C FLOW   0 %',`AFW-A FLOW   ${sim.s6.afwA.toFixed(0)} % AFW-RATED`,`AFW-B FLOW   ${sim.s6.afwB.toFixed(0)} % AFW-RATED`,`AFW-C FLOW   ${sim.s6.afwC.toFixed(0)} % AFW-RATED`]);else if(id===3)block(['FEEDWATER','MFW FLOW     0 %',`AFW FLOW     ${sim.s3.afwFlow.toFixed(0)} % AFW-RATED`,'AFW DEMAND   YES']);else if(id===4)block(['FEEDWATER','MFW FLOW     0 %',`AFW FLOW     ${sim.s4.afwFlow.toFixed(0)} % AFW-RATED`,`AFW DEMAND   ${sim.reactorTripped?'YES':'NO'}`]);else block(['FEEDWATER','MFW-A FLOW   100 %',`MFW-B FLOW   ${id===2?sim.s2.fw.toFixed(0):100} %`,'MFW-C FLOW   100 %','AFW DEMAND   NO'])}
 else if(name==='turbine')block(['TURBINE / GENERATOR',`TURBINE      ${sim.turbineTripped?'TRIPPED':'RUNNING'}`,`GENERATOR    ${sim.turbineTripped?'OFFLINE':'ONLINE'}`]);
 else if(name==='condenser')block(['CONDENSER',`PRESSURE     ${id===4?sim.s4.condenser.toFixed(1):id===0?sim.s0.condenser.toFixed(1):'7.0'} kPa(abs)`,`AVAILABLE    ${id===4&&sim.s4.condenser>=25?'NO':'YES'}`]);
 else if(name==='electrical'){if(id===5)block(['ELECTRICAL','OFFSITE      LOST',`BUS-A        ${sim.s5.busA.toFixed(0)} %`,`BUS-B        ${sim.s5.busB.toFixed(0)} %`,`EDG-A        ${sim.s5.edgA.state}`,`EDG-B        ${sim.s5.edgB.state}`]);else block(['ELECTRICAL','OFFSITE      AVAILABLE','BUS-A        100 %','BUS-B        100 %','EDG-A        STANDBY','EDG-B        STANDBY'])}
 else if(name==='safety')block(['SAFETY / PROTECTION',`RPS          ${sim.reactorTripped?'TRIP COMPLETE':'STANDBY'}`,`AFW          ${(id===0&&sim.reactorTripped)||(id===2&&sim.reactorTripped)||[3,4,6].includes(id)?'DEMAND / ACTIVE':'STANDBY'}`,`SI           ${id===9&&sim.reactorTripped?'DEMAND / ACTIVE':'STANDBY'}`,`INTERLOCKS   NORMAL`]);
 else if(name==='instrumentation')block(['INSTRUMENTATION',`SG-B LVL CH1 ${id===7?sim.s7.ch1.toFixed(0)+' % '+(sim.s7.reported?'OUT OF SERVICE':sim.s7.diagComplete?'FAILED':'STABLE'):'VALID'}`,`SG-B LVL CH2 ${id===7?sim.s7.ch2.toFixed(0)+' %':'VALID'}`,`SG-B LVL CH3 ${id===7?sim.s7.ch3.toFixed(0)+' %':'VALID'}`,`DIAGNOSTIC   ${id===7?sim.s7.diagState:'IDLE'}`]);
 else if(name==='support'){if(id===10)block(['SUPPORT / CCW',`CCW-A        ${sim.s10.ccwA}`,`CCW-B        ${sim.s10.ccwB}`,`HEADER FLOW  ${sim.s10.ccwFlow.toFixed(0)} %`,`HEADER TEMP  ${sim.s10.headerTemp.toFixed(0)} C`]);else block(['SUPPORT / CCW','CCW-A        RUNNING','CCW-B        STANDBY','HEADER FLOW  100 %','HEADER TEMP  35 C'])}
 else p('UNKNOWN STATUS SYSTEM','danger')}
function read(dev){updateSim();const id=stage.id;const normalRcp=n=>block([n,'STATE        RUNNING','SPEED        100 %','FLOW         100 %','VIBRATION    1.0 INDEX','BEARING      70 C']);
 if(dev==='RCP-A'){if([0,1,8].includes(id))block(['RCP-A',`STATE        ${sim.rcpA.state}`,`SPEED        ${sim.rcpA.speed.toFixed(0)} %`,`FLOW         ${sim.rcpA.flow.toFixed(0)} %`,`VIBRATION    ${sim.rcpA.vib.toFixed(1)} INDEX`,`BEARING      ${id===10?sim.s10.rcpBearing.toFixed(0):sim.rcpA.bearing.toFixed(0)} C`]);else if(id===10)block(['RCP-A','STATE        RUNNING','SPEED        100 %','FLOW         100 %','VIBRATION    1.0 INDEX',`BEARING      ${sim.s10.rcpBearing.toFixed(0)} C`]);else normalRcp(dev)}
 else if(['RCP-B','RCP-C'].includes(dev))normalRcp(dev);
 else if(/^SG-[ABC]$/.test(dev)){const which=dev.at(-1),d=sgData(which);if(id===7&&which==='B'){block(['SG-B','LEVEL CH1    '+sim.s7.ch1.toFixed(0)+' %','LEVEL CH2    '+sim.s7.ch2.toFixed(0)+' %','LEVEL CH3    '+sim.s7.ch3.toFixed(0)+' %','PRESSURE     6.90 MPa','STEAM FLOW   100 %']);return}const lines=[dev,`LEVEL        ${d.level.toFixed(0)} %`,`PRESSURE     ${d.pressure.toFixed(2)} MPa`,`STEAM FLOW   ${d.steam.toFixed(0)} %`];if([0,3,4,6].includes(id)){lines.push(`MFW FLOW     ${d.mfw.toFixed(0)} %`);lines.push(`AFW FLOW     ${d.afw.toFixed(0)} % AFW-RATED`)}else lines.push(`FEEDWATER    ${d.mfw.toFixed(0)} %`);block(lines)}
 else if(/^FRV-[ABC]$/.test(dev)){const b=dev==='FRV-B'&&(id===2||id===0),ss=id===0?sim.s0:sim.s2;block([dev,`COMMAND      ${b?ss.frvCmd:'AUTO'}`,`ACTUAL       ${b?ss.frvActual.toFixed(0):'50'} %`,`FLOW         ${b?(id===0?ss.fwB:ss.fw).toFixed(0):'100'} %`,id===2&&b?'FAULT FLAG   NOT AVAILABLE TO OPERATOR':'STATE        NORMAL'])}
 else if(dev==='CONDENSER')status('condenser');
 else if(dev==='EDG-A'){if(id===5)block(['EDG-A','DEMAND       YES',`ENGINE       ${sim.s5.edgA.state}`,`SPEED        ${sim.s5.edgA.speed.toFixed(0)} %`,`BREAKER CMD ${sim.s5.edgA.breakerCmd}`,`BREAKER      ${sim.s5.edgA.breaker}`]);else if(id===10)block(['EDG-A','DEMAND       NO','ENGINE       STANDBY','SPEED        0 %',`COOLING TEMP ${sim.s10.edgTemp.toFixed(0)} C`,'BREAKER      OPEN']);else block(['EDG-A','DEMAND       NO','ENGINE       STANDBY','SPEED        0 %','BREAKER      OPEN'])}
 else if(dev==='EDG-B'){if(id===5)block(['EDG-B','DEMAND       YES',`ENGINE       ${sim.s5.edgB.state}`,`SPEED        ${sim.s5.edgB.speed.toFixed(0)} %`,`BREAKER CMD ${sim.s5.edgB.breakerCmd}`,`BREAKER      ${sim.s5.edgB.breaker}`]);else block(['EDG-B','DEMAND       NO','ENGINE       STANDBY','SPEED        0 %','BREAKER      OPEN'])}
 else if(dev==='EDG-A-BREAKER')block(['EDG-A BREAKER',`COMMAND      ${id===5?sim.s5.edgA.breakerCmd:'AUTO'}`,`POSITION     ${id===5?sim.s5.edgA.breaker:'OPEN'}`,`BUS-A        ${id===5&&sim.s5.busA<10?'DEAD':'ENERGIZED'}`]);
 else if(dev==='EDG-B-BREAKER')block(['EDG-B BREAKER',`COMMAND      ${id===5?sim.s5.edgB.breakerCmd:'AUTO'}`,`POSITION     ${id===5?sim.s5.edgB.breaker:'OPEN'}`,`BUS-B        ${id===5&&sim.s5.busB<10?'DEAD':'ENERGIZED'}`]);
 else if(dev==='BUS-A')block(['BUS-A',`VOLTAGE      ${id===5?sim.s5.busA.toFixed(0):'100'} %`]);
 else if(dev==='BUS-B')block(['BUS-B',`VOLTAGE      ${id===5?sim.s5.busB.toFixed(0):'100'} %`]);
 else if(dev==='OFFSITE')block(['OFFSITE POWER',`STATE        ${id===5?'LOST':'AVAILABLE'}`,`VOLTAGE      ${id===5?'0':'100'} %`]);
 else if(/^AFW-[ABC]$/.test(dev)){const w=dev.at(-1);let demand=[3,4,6].includes(id)||(id===0&&sim.reactorTripped)||(id===2&&sim.reactorTripped),pump='STANDBY',flow=0;if(id===0){if(w==='B'){pump=sim.s0.afwBPump;flow=sim.s0.afwBFlow}}else if(id===2&&sim.reactorTripped){pump=w==='B'?sim.s2.afwPump:'STANDBY';flow=w==='B'?sim.s2.afwFlow:0}else if(id===3){pump='RUNNING';flow=sim.s3.afwFlow}else if(id===4){pump=sim.reactorTripped?'RUNNING':'STANDBY';flow=sim.s4.afwFlow}else if(id===6){pump=w==='A'?sim.s6.afwAPump:w==='B'?sim.s6.afwBPump:sim.s6.afwCPump;flow=w==='A'?sim.s6.afwA:w==='B'?sim.s6.afwB:sim.s6.afwC}else if(id===10){pump='RUNNING';flow=100}const lines=[dev,`DEMAND       ${demand?'YES':'NO'}`,`PUMP         ${pump}`,`FLOW         ${flow.toFixed(0)} % AFW-RATED`];if(id===10)lines.push(`BEARING      ${sim.s10.afwBearing.toFixed(0)} C`);block(lines)}
 else if(/^AFW-VALVE-[ABC]$/.test(dev)){const w=dev.at(-1);if(id===6&&w==='B')block(['AFW-B DELIVERY VALVE',`COMMAND      ${sim.s6.afwValveCmd}`,`ACTUAL       ${sim.s6.afwValveActual.toFixed(0)} %`]);else block([dev,'COMMAND      AUTO','ACTUAL       OPEN'])}
 else if(dev.startsWith('SG-B-LVL-CH')){const n=dev.slice(-1),v=id===7?(n==='1'?sim.s7.ch1:n==='2'?sim.s7.ch2:sim.s7.ch3):55;let quality='VALID';if(id===7&&n==='1'&&sim.s7.diagComplete)quality=sim.s7.reported?'OUT OF SERVICE':'FAILED — STUCK LOW';block([dev,`VALUE        ${Number(v).toFixed(0)} %`,`QUALITY      ${quality}`])}
 else if(dev==='REACTOR')status('reactor');
 else if(dev==='RCS'){const press=id===9?sim.s9.pressure:15.5;const lines=['RCS',`PRESSURE     ${press.toFixed(1)} MPa`,`HOT LEG      ${rcsTemp().toFixed(0)} C`,`COLD LEG     ${(rcsTemp()-30).toFixed(0)} C`,`DELTA-T      30 C`];if(id===9)lines.push(`INVENTORY     ${sim.s9.inventory.toFixed(0)} %`);block(lines)}
 else if(dev==='PZR'){if(id===9)block(['PZR',`PRESSURE     ${sim.s9.pressure.toFixed(1)} MPa`,`LEVEL        ${sim.s9.pzrLevel.toFixed(0)} %`,'HEATER       AUTO','SPRAY        AUTO']);else block(['PZR','PRESSURE     15.5 MPa','LEVEL        52 %','HEATER       AUTO','SPRAY        AUTO'])}
 else if(dev==='RCS-LETDOWN'){if(id===9)block(['RCS LETDOWN',`FLOW         ${sim.s9.letdownFlow.toFixed(0)} %`,`ISOLATION    ${sim.s9.letdownIso}`,'DOWNSTREAM   LEAK INDICATION']);else block(['RCS LETDOWN','FLOW         100 %','ISOLATION    OPEN','DOWNSTREAM   NORMAL'])}
 else if(dev==='RCS-LETDOWN-ISO'){block(['RCS LETDOWN ISOLATION',`COMMAND      ${id===9?sim.s9.letdownIso:'OPEN'}`,`POSITION     ${id===9?sim.s9.letdownIso:'OPEN'}`])}
 else if(dev==='SI'){block(['SAFETY INJECTION',`DEMAND       ${id===9&&sim.reactorTripped?'YES':'NO'}`,`FLOW         ${id===9?sim.s9.siFlow.toFixed(0):'0'} % SI-RATED`])}
 else if(dev==='CCW-A'){if(id===10)block(['CCW-A',`STATE        ${sim.s10.ccwA}`,'SPEED        0 %','FLOW         0 %']);else block(['CCW-A','STATE        RUNNING','SPEED        100 %','FLOW         100 %'])}
 else if(dev==='CCW-B'){if(id===10)block(['CCW-B',`STATE        ${sim.s10.ccwB}`,`SPEED        ${sim.s10.ccwBSpeed.toFixed(0)} %`,`HEADER FLOW  ${sim.s10.ccwFlow.toFixed(0)} %`]);else block(['CCW-B','STATE        STANDBY','SPEED        0 %','HEADER FLOW  100 %'])}
 else if(dev==='CCW-HEADER'){if(id===10)block(['CCW HEADER',`FLOW         ${sim.s10.ccwFlow.toFixed(0)} %`,`TEMP         ${sim.s10.headerTemp.toFixed(0)} C`,`TREND        ${sim.s10.ccwTrend>=0?'+':''}${sim.s10.ccwTrend.toFixed(2)} %/m`]);else block(['CCW HEADER','FLOW         100 %','TEMP         35 C','TREND        0.00 %/m'])}
 else if(dev==='RPS')status('safety');
 else if(dev==='TURBINE'||dev==='GENERATOR')status('turbine');
 else if(dev==='STEAM-DUMP'){if(id===0)block(['STEAM-DUMP',`COMMAND      ${sim.s0.steamDumpCmd}`,`ACTUAL       ${sim.s0.steamDumpActual.toFixed(0)} %`,'HEAT SINK    CONDENSER','AVAILABLE    YES']);else if(id===3)block(['STEAM-DUMP',`COMMAND      ${sim.s3.steamDumpCmd}`,`ACTUAL       ${sim.s3.steamDumpActual.toFixed(0)} %`,'HEAT SINK    CONDENSER','AVAILABLE    YES']);else if(id===4)block(['STEAM-DUMP',`COMMAND      ${sim.s4.steamDumpCmd}`,`ACTUAL       ${sim.s4.steamDumpActual.toFixed(0)} %`,`FLOW         ${sim.s4.steamDumpFlow.toFixed(0)} %`,`CONDENSER    ${sim.s4.condenser>=25?'UNAVAILABLE':'DEGRADED'}`]);else block(['STEAM-DUMP','COMMAND      AUTO','ACTUAL       0 %','AVAILABLE    YES'])}
 else if(dev==='ATM-DUMP'){if(id===0)block(['ATM-DUMP',`COMMAND      ${sim.s0.atmCmd}`,`ACTUAL       ${sim.s0.atmActual.toFixed(0)} %`]);else if(id===4)block(['ATM-DUMP',`COMMAND      ${sim.s4.atmCmd}`,`ACTUAL       ${sim.s4.atmActual.toFixed(0)} %`,`FLOW         ${sim.s4.atmFlow.toFixed(0)} %`]);else block(['ATM-DUMP','COMMAND      STANDBY','ACTUAL       0 %'])}
 else p('UNKNOWN DEVICE','danger')}
function histLabel(t){if(t<0){const sec=Math.abs(Math.round(t));return `T-${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}const sec=Math.round(t);return `T+${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function historyCmd(dev,param){updateSim();const key=`${dev} ${param}`.trim(),data=sim.history.data[key];if(!data||!data.length){p('NO HISTORY DATA','danger');return}const unit=key.includes('VIBRATION')?'':key.includes('POSITION')||key.includes('FLOW')||key.includes('LEVEL')||key.includes('VOLTAGE')||key.includes('SPEED')?' %':key.includes('PRESSURE')?' MPa':'';const lines=[`${key} HISTORY`];data.slice(-8).forEach(x=>lines.push(`${histLabel(x.t).padEnd(10)} ${Number(x.v).toFixed(key.includes('VIBRATION')||key.includes('PRESSURE')?1:0)}${unit}`));let nowVal=null;if(key==='RCP-A FLOW')nowVal=sim.rcpA.flow;if(key==='RCP-A VIBRATION')nowVal=sim.rcpA.vib;if(key==='RCP-A SPEED')nowVal=sim.rcpA.speed;if(key==='SG-B LEVEL')nowVal=stage.id===0?sim.s0.sgB:sim.s2.sg;if(key==='FRV-B POSITION')nowVal=stage.id===0?sim.s0.frvActual:sim.s2.frvActual;if(key==='CONDENSER PRESSURE')nowVal=sim.s4.condenser;if(key==='BUS-B VOLTAGE')nowVal=sim.s5.busB;if(key==='AFW-B FLOW')nowVal=sim.s6.afwB;if(key==='SG-B-LVL-CH1 LEVEL')nowVal=sim.s7.ch1;if(key==='SG-B-LVL-CH2 LEVEL')nowVal=sim.s7.ch2;if(key==='RCS PRESSURE')nowVal=sim.s9.pressure;if(key==='PZR LEVEL')nowVal=sim.s9.pzrLevel;if(key==='CCW FLOW')nowVal=sim.s10.ccwFlow;if(nowVal!==null)lines.push(`NOW        ${Number(nowVal).toFixed(key.includes('VIBRATION')||key.includes('PRESSURE')?1:0)}${unit}`);block(lines)}
function activeAlarms(){const id=stage.id,a=[];const add=(code,msg)=>a.push([code,msg]);if(id===0){if(sim.rcpA.state!=='RUNNING')add('S-001','RCP-A NOT RUNNING');if(sim.s0.sgB<50)add('S-002','SG-B LEVEL LOW');if(sim.reactorTripped)add('S-003','REACTOR TRIP');if(sim.s0.rcsTemp>325)add('S-004','RCS TEMPERATURE HIGH')}
 if(id===1){if(sim.rcpA.speed<95)add('A-110','RCP-A SPEED LOW');if(sim.rcpA.flow<90)add('A-111','PRIMARY LOOP-A FLOW LOW');if(sim.rcpA.vib>2)add('A-112','RCP-A VIBRATION HIGH');if(sim.rcpA.bearing>80)add('A-113','RCP-A BEARING TEMP HIGH');if(sim.reactorTripped)add('A-114','REACTOR TRIP')}
 if(id===2){if(Math.abs(sim.s2.fw-sim.s2.steam)>20)add('A-120','FW-B / STEAM FLOW MISMATCH');if(sim.s2.sg<52)add('A-121','SG-B LEVEL LOW');if(sim.s2.sg<=50)add('A-122','SG-B LEVEL LOW-LOW');if(sim.reactorTripped)add('A-123','REACTOR TRIP / AFW DEMAND');if(sim.reactorTripped&&sim.s2.afwPump!=='RUNNING')add('A-124','AFW-B NOT RUNNING')}
 if(id===3){add('A-130','TURBINE TRIP');add('A-131','REACTOR TRIP');if(sim.s3.sgPressure>7.3)add('A-132','SG PRESSURE HIGH');if(sim.s3.sgLevel<45)add('A-133','SG LEVEL LOW');if(sim.s3.steamDumpActual<70)add('A-134','STEAM-DUMP FLOW INSUFFICIENT')}
 if(id===4){if(sim.s4.condenser>15)add('A-140','CONDENSER VACUUM DEGRADED');if(sim.s4.condenser>25)add('A-141','CONDENSER VACUUM LOW');if(sim.turbineTripped)add('A-142','TURBINE TRIP');if(sim.reactorTripped)add('A-143','REACTOR TRIP');if(sim.reactorTripped&&sim.s4.atmFlow<60)add('A-144','ALTERNATE HEAT REMOVAL INSUFFICIENT')}
 if(id===5){add('A-150','OFFSITE POWER LOST');if(sim.s5.busA<90)add('A-151','BUS-A UNDERVOLTAGE');if(sim.s5.busB<90)add('A-152','BUS-B UNDERVOLTAGE');if(sim.simTime>15&&sim.s5.edgB.state==='RUNNING'&&sim.s5.busB<10)add('A-153','EDG-B OUTPUT NOT CONNECTED');if(sim.s5.busA<10&&sim.s5.busB<10)add('A-154','ALL SAFETY BUSES DEENERGIZED')}
 if(id===6){add('A-160','MAIN FEEDWATER LOST');if(sim.s6.afwBPump==='RUNNING'&&sim.s6.afwB<40)add('A-161','AFW-B DELIVERY LOW');if(sim.s6.sgB<40)add('A-162','SG-B LEVEL LOW');if(sim.s6.sgB<25)add('A-163','SG-B LEVEL VERY LOW');if(sim.s6.afwA+sim.s6.afwB+sim.s6.afwC<80)add('A-164','TOTAL AFW CAPACITY LOW')}
 if(id===7){if(!sim.s7.reported&&sim.s7.ch1<40)add('A-170','SG-B LEVEL LOW CH-1');if(!sim.s7.reported&&Math.max(sim.s7.ch1,sim.s7.ch2,sim.s7.ch3)-Math.min(sim.s7.ch1,sim.s7.ch2,sim.s7.ch3)>10)add('A-171','SG-B LEVEL CHANNEL DISAGREEMENT');if(sim.s7.reported)add('A-172','SG-B LVL CH-1 OUT OF SERVICE')}
 if(id===8){add('A-180','REACTOR TRIP / PROTECTION ACTUATION');if(sim.rcpA.state!=='RUNNING')add('A-181','PRIMARY FORCED CIRCULATION DEGRADED')}
 if(id===9){if(sim.s9.pressure<15.2)add('A-190','RCS PRESSURE LOW');if(sim.s9.pzrLevel<45)add('A-191','PZR LEVEL LOW');if(sim.s9.letdownFlow>130)add('A-192','RCS LETDOWN FLOW HIGH');if(sim.reactorTripped)add('A-193','REACTOR TRIP / SAFETY INJECTION');if(sim.s9.inventory<50)add('A-194','RCS INVENTORY LOW')}
 if(id===10){add('A-200','CCW-A UNAVAILABLE');if(sim.s10.ccwFlow<70)add('A-201','CCW HEADER FLOW LOW');if(sim.s10.rcpBearing>85)add('A-202','RCP AUX BEARING TEMP HIGH');if(sim.s10.afwBearing>85)add('A-203','AFW AUX BEARING TEMP HIGH');if(sim.s10.edgTemp>95)add('A-204','EDG AUX COOLING TEMP HIGH');if(sim.reactorTripped)add('A-205','REACTOR TRIP — SUPPORT COOLING LOW')}
 return a}
function alarms(detail=false){updateSim();const a=activeAlarms();if(!a.length){block(['ACTIVE ALARMS','','NONE']);return}block(['ACTIVE ALARMS','',...a.map(x=>`${x[0]}   ${x[1]}`),detail?'\nNOTE: Alarm source is not necessarily root cause.':''])}
function acceptControl(cmd,msg,fn){if(fn)fn();controls.add(cmd);controlCount++;p('COMMAND ACCEPTED: '+cmd.replace('CONTROL ','').toUpperCase(),'ok');if(msg)p(msg,'alarm');stableSince=null;return true}
function rejectControl(msg){p('COMMAND REJECTED: '+msg,'danger');return false}
function noChange(msg){p('COMMAND ACKNOWLEDGED: '+msg,'alarm');return false}
function control(cmd){if(finished&&!isSimulation()){p('STAGE COMPLETE: CONTROL DISABLED','danger');return false}updateSim();const id=stage.id;
 if(cmd==='CONTROL REACTOR TRIP'){if(sim.reactorTripped)return noChange('REACTOR ALREADY TRIPPED');return acceptControl(cmd,'RPS: REACTOR TRIP COMPLETE',()=>{tripReactor();if(id===0){sim.turbineTripped=true;sim.s0.afwBPump='RUNNING'}})}
 if(cmd==='CONTROL RCP-A STOP'){if(![0,1,8].includes(id))return rejectControl('RCP-A MANUAL CONTROL NOT AUTHORIZED IN CURRENT STAGE');if(sim.rcpA.state==='STOPPED'||sim.rcpA.state==='COASTDOWN')return noChange('RCP-A ALREADY STOPPING / STOPPED');return acceptControl(cmd,'RCP-A: COASTDOWN INITIATED',()=>{sim.rcpA.state='COASTDOWN';sim.rcpA.stopAt=sim.simTime})}
 if(cmd==='CONTROL RCP-A START'){if(![0,1,8].includes(id))return rejectControl('RCP-A MANUAL CONTROL NOT AUTHORIZED IN CURRENT STAGE');if(sim.rcpA.state==='RUNNING'||sim.rcpA.state==='STARTING')return noChange('RCP-A ALREADY RUNNING / STARTING');if(sim.rcpA.state==='COASTDOWN')return rejectControl('RCP-A COASTDOWN IN PROGRESS');if(id===1&&!sim.reactorTripped)return rejectControl('START PERMISSIVE NOT MET');return acceptControl(cmd,'RCP-A: START SEQUENCE INITIATED',()=>{sim.rcpA.state='STARTING'})}
 if(cmd==='CONTROL FRV-B OPEN'||cmd==='CONTROL FRV-B CLOSE'){if(![0,2].includes(id))return rejectControl('FRV-B MANUAL CONTROL NOT AUTHORIZED IN CURRENT STAGE');const open=cmd.endsWith('OPEN'),ss=id===0?sim.s0:sim.s2;return acceptControl(cmd,open?'FRV-B COMMAND OPEN; ACTUAL RESPONSE RECOVERING':'FRV-B COMMAND CLOSE; ACTUAL POSITION DECREASING',()=>{ss.frvCmd=open?'OPEN':'CLOSE';if(id===2&&open)ss.recoveryAt=sim.simTime})}
 if(['CONTROL AFW-A START','CONTROL AFW-B START','CONTROL AFW-C START','CONTROL AFW-A STOP','CONTROL AFW-B STOP','CONTROL AFW-C STOP'].includes(cmd)){const w=cmd.match(/AFW-([ABC])/)[1],start=cmd.endsWith('START');if(id===0){if(w!=='B')return rejectControl('SELECTED AFW TRAIN NOT AVAILABLE IN SIMULATION MODEL');if(!sim.reactorTripped)return rejectControl('AFW START/STOP NOT DEMANDED IN CURRENT PLANT STATE');if(start)return acceptControl(cmd,'AFW-B START REQUEST',()=>{sim.s0.afwBPump='RUNNING'});return acceptControl(cmd,'AFW-B STOP REQUEST',()=>{sim.s0.afwBPump='STOPPED'})}
   if(id===2){if(w!=='B'||!sim.reactorTripped)return rejectControl('AFW MANUAL CONTROL NOT AUTHORIZED IN CURRENT PLANT STATE');if(start){if(sim.s2.afwPump==='RUNNING')return noChange('AFW-B ALREADY RUNNING');return acceptControl(cmd,'AFW-B START REQUEST',()=>{sim.s2.afwPump='RUNNING'})}if(sim.s2.afwPump==='STOPPED')return noChange('AFW-B ALREADY STOPPED');return acceptControl(cmd,'AFW-B STOP REQUEST',()=>{sim.s2.afwPump='STOPPED'})}
   if(id===6){const key=w==='A'?'afwAPump':w==='B'?'afwBPump':'afwCPump';if(start){if(sim.s6[key]==='RUNNING')return noChange(`AFW-${w} ALREADY RUNNING`);return acceptControl(cmd,`AFW-${w} START REQUEST`,()=>{sim.s6[key]='RUNNING'})}if(sim.s6[key]==='STOPPED')return noChange(`AFW-${w} ALREADY STOPPED`);return acceptControl(cmd,`AFW-${w} STOP REQUEST`,()=>{sim.s6[key]='STOPPED'})}
   if([3,4].includes(id))return noChange('AFW AUTO ACTUATION ALREADY ACTIVE');return rejectControl('AFW START/STOP NOT DEMANDED IN CURRENT PLANT STATE')}
 if(cmd==='CONTROL AFW-VALVE-B OPEN'||cmd==='CONTROL AFW-VALVE-B CLOSE'){if(id!==6)return rejectControl('AFW-B DELIVERY VALVE MANUAL CONTROL NOT AUTHORIZED IN CURRENT STAGE');const open=cmd.endsWith('OPEN');if((open&&sim.s6.afwValveCmd==='OPEN')||(!open&&sim.s6.afwValveCmd==='CLOSED'))return noChange(`AFW-B DELIVERY VALVE ALREADY ${open?'OPENING':'CLOSING / CLOSED'}`);return acceptControl(cmd,open?'AFW-B DELIVERY PATH OPENING':'AFW-B DELIVERY PATH CLOSING',()=>{sim.s6.afwValveCmd=open?'OPEN':'CLOSED'})}
 if(cmd==='CONTROL STEAM-DUMP OPEN'||cmd==='CONTROL STEAM-DUMP CLOSE'){if(![0,3,4].includes(id))return rejectControl('STEAM-DUMP MANUAL CONTROL NOT AUTHORIZED IN CURRENT STAGE');const open=cmd.endsWith('OPEN');if(id===0&&!sim.reactorTripped&&open)return rejectControl('OPEN PERMISSIVE NOT MET');const ss=id===0?sim.s0:id===3?sim.s3:sim.s4;if((open&&ss.steamDumpCmd==='OPEN')||(!open&&ss.steamDumpCmd==='CLOSE'))return noChange(`STEAM-DUMP ALREADY ${open?'OPENING':'CLOSING'}`);return acceptControl(cmd,open?(id===4?'STEAM-DUMP OPEN REQUEST; CONDENSER ACCEPTANCE MAY LIMIT FLOW':'STEAM-DUMP MANUAL OPEN REQUEST'):'STEAM-DUMP MANUAL CLOSE REQUEST',()=>{ss.steamDumpCmd=open?'OPEN':'CLOSE'})}
 if(cmd==='CONTROL ATM-DUMP OPEN'||cmd==='CONTROL ATM-DUMP CLOSE'){if(![0,4].includes(id))return rejectControl('ATMOSPHERIC DUMP NOT AUTHORIZED IN CURRENT STAGE');const open=cmd.endsWith('OPEN'),ss=id===0?sim.s0:sim.s4;if(open&&id===4&&!sim.reactorTripped&&sim.s4.condenser<20)return rejectControl('OPEN PERMISSIVE NOT MET');if(open&&id===0&&!sim.reactorTripped)return rejectControl('OPEN PERMISSIVE NOT MET');if((open&&ss.atmCmd==='OPEN')||(!open&&ss.atmCmd==='CLOSE'))return noChange(`ATM-DUMP ALREADY ${open?'OPENING':'CLOSING'}`);return acceptControl(cmd,open?'ATMOSPHERIC HEAT-REMOVAL PATH OPENING':'ATMOSPHERIC HEAT-REMOVAL PATH CLOSING',()=>{ss.atmCmd=open?'OPEN':'CLOSE'})}
 if(cmd==='CONTROL EDG-A START'||cmd==='CONTROL EDG-B START'){if(id===0)return rejectControl('EDG START NOT DEMANDED — OFFSITE POWER AVAILABLE');if(id!==5)return rejectControl('EDG START NOT DEMANDED IN CURRENT PLANT STATE');const e=cmd.includes('EDG-A')?sim.s5.edgA:sim.s5.edgB;if(e.state==='RUNNING'||e.state==='CRANKING')return noChange('EDG AUTO START SEQUENCE ALREADY ACTIVE');return acceptControl(cmd,'EDG START REQUEST',()=>{e.state='CRANKING'})}
 if(/^CONTROL EDG-[AB]-BREAKER (OPEN|CLOSE)$/.test(cmd)){if(id!==5)return rejectControl('EDG BREAKER CONTROL NOT AUTHORIZED IN CURRENT STAGE');const w=cmd.includes('EDG-A')?'A':'B',e=w==='A'?sim.s5.edgA:sim.s5.edgB,close=cmd.endsWith('CLOSE');if(!close){if(e.breaker==='OPEN')return noChange(`EDG-${w} BREAKER ALREADY OPEN`);return acceptControl(cmd,`EDG-${w} BREAKER OPEN COMMAND`,()=>{e.breakerCmd='OPEN';e.breaker='OPEN';e.closeAt=null})}if(e.speed<95)return rejectControl(`EDG-${w} SPEED PERMISSIVE NOT MET`);if(e.breaker==='CLOSED'||e.breakerCmd==='CLOSE')return noChange(`EDG-${w} BREAKER ALREADY CLOSED / CLOSING`);return acceptControl(cmd,`EDG-${w} BREAKER CLOSE COMMAND; ACTUAL CLOSURE PENDING`,()=>{e.breakerCmd='CLOSE';e.closeAt=sim.simTime})}
 if(cmd==='CONTROL SG-B-LVL DIAG'){if(id!==7)return rejectControl('INSTRUMENT DIAGNOSTIC NOT AUTHORIZED IN CURRENT STAGE');if(sim.s7.diagComplete)return noChange('SG-B LEVEL DIAGNOSTIC ALREADY COMPLETE');if(sim.s7.diagState==='RUNNING')return noChange('SG-B LEVEL DIAGNOSTIC ALREADY RUNNING');return acceptControl(cmd,'SG-B LEVEL CHANNEL DIAGNOSTIC STARTED',()=>{sim.s7.diagState='RUNNING';sim.s7.diagAt=sim.simTime})}
 if(cmd==='CONTROL RCS-LETDOWN-ISO CLOSE'||cmd==='CONTROL RCS-LETDOWN-ISO OPEN'){if(id!==9)return rejectControl('RCS LETDOWN ISOLATION CONTROL NOT AUTHORIZED IN CURRENT STAGE');const close=cmd.endsWith('CLOSE');if((close&&sim.s9.letdownIso==='CLOSED')||(!close&&sim.s9.letdownIso==='OPEN'))return noChange(`RCS LETDOWN ISOLATION ALREADY ${close?'CLOSED':'OPEN'}`);return acceptControl(cmd,close?'RCS LETDOWN PATH ISOLATED':'RCS LETDOWN PATH REOPENED',()=>{sim.s9.letdownIso=close?'CLOSED':'OPEN';sim.s9.leakRate=close?0:.30})}
 if(cmd==='CONTROL CCW-B START'||cmd==='CONTROL CCW-B STOP'){if(id!==10){if(id===0)return rejectControl('CCW-B START NOT REQUIRED — CCW-A NORMAL');return rejectControl('CCW-B MANUAL CONTROL NOT AUTHORIZED IN CURRENT STAGE')}const start=cmd.endsWith('START');if(start){if(['STARTING','RUNNING'].includes(sim.s10.ccwB))return noChange('CCW-B ALREADY STARTING / RUNNING');return acceptControl(cmd,'CCW-B START SEQUENCE INITIATED',()=>{sim.s10.ccwB='STARTING'})}if(sim.s10.ccwB==='STANDBY')return noChange('CCW-B ALREADY STOPPED / STANDBY');return acceptControl(cmd,'CCW-B STOP REQUEST',()=>{sim.s10.ccwB='STANDBY';sim.s10.ccwBSpeed=0})}
 return rejectControl('CONTROL COMMAND NOT APPLICABLE TO CURRENT PLANT STATE')}
function baseSafeState(){const id=stage.id;if(id===0)return false;if(id===1)return sim.reactorTripped&&sim.rcpA.state==='STOPPED'&&sim.rcpA.speed===0&&sim.s1.thermalRisk<=.25&&sim.s1.rcsTemp<=315;
 if(id===2){if(sim.reactorTripped)return sim.s2.frvCmd==='OPEN'&&sim.s2.afwFlow>=60&&sim.s2.sg>=45&&sim.s2.sg<=60&&sim.s2.trend>=-.005;return sim.s2.frvCmd==='OPEN'&&sim.s2.fw>=95&&sim.s2.fw<=105&&sim.s2.sg>=50&&sim.s2.sg<=60&&sim.s2.trend>=-.005}
 if(id===3)return sim.reactorTripped&&sim.turbineTripped&&sim.s3.steamDumpActual>=80&&sim.s3.sgPressure>=6.7&&sim.s3.sgPressure<=7.1&&sim.s3.sgLevel>=45&&sim.s3.sgLevel<=60&&sim.s3.afwFlow>=60&&sim.s3.rcsTemp<=315;
 if(id===4)return sim.reactorTripped&&sim.turbineTripped&&sim.s4.atmFlow>=80&&sim.s4.afwFlow>=60&&sim.s4.sgPressure>=6.7&&sim.s4.sgPressure<=7.1&&sim.s4.sgLevel>=45&&sim.s4.sgLevel<=60&&sim.s4.sgTrend>=-.01&&sim.s4.rcsTemp<=315;
 if(id===5)return sim.s5.busA>=95&&sim.s5.busB>=95&&sim.s5.edgA.breaker==='CLOSED'&&sim.s5.edgB.breaker==='CLOSED'&&sim.s5.rcsTemp<=318;
 if(id===6)return sim.s6.afwB>=80&&(sim.s6.afwA+sim.s6.afwB+sim.s6.afwC)>=200&&sim.s6.sgB>=50&&sim.s6.sgB<=60&&sim.s6.sgTrend>=0&&sim.s6.rcsTemp<=315;
 if(id===7)return sim.s7.reported&&sim.s7.trueLevel>=50&&sim.s7.trueLevel<=60&&Math.abs(sim.s7.ch2-sim.s7.ch3)<2;
 if(id===8)return sim.reactorTripped&&sim.rcpA.state==='RUNNING'&&sim.s8.decayHeat<5.0&&sim.s8.rcsTemp<312&&sim.s8.rcsTrend<=0;
 if(id===9)return sim.s9.letdownIso==='CLOSED'&&sim.s9.inventory>=70&&sim.s9.pressure>=14.5&&sim.s9.pzrLevel>=40&&sim.s9.rcsTemp<=(sim.reactorTripped?315:322);
 if(id===10)return sim.s10.ccwB==='RUNNING'&&sim.s10.ccwFlow>=90&&sim.s10.headerTemp<=40&&sim.s10.rcpBearing<=85&&sim.s10.afwBearing<=85&&(!sim.reactorTripped||sim.s10.rcsTemp<=315);
 return false}
function failureState(){const id=stage.id;if(id===0)return sim.s0.rcsTemp>=335||sim.s0.sgB<=15;if(id===1)return sim.s1.thermalRisk>=1||sim.s1.rcsTemp>=335;if(id===2)return sim.reactorTripped&&sim.s2.afwFlow<10&&sim.s2.sg<=15;if(id===3)return sim.s3.sgLevel<=25||sim.s3.rcsTemp>=335;if(id===4)return sim.s4.sgLevel<=25||sim.s4.rcsTemp>=335;if(id===5)return sim.s5.busA<10&&sim.s5.busB<10&&sim.s5.rcsTemp>=330;if(id===6)return sim.s6.rcsTemp>=330;if(id===8)return sim.s8.rcsTemp>=330;if(id===9)return sim.s9.inventory<=30||sim.s9.pressure<=11.5||sim.s9.rcsTemp>=335;if(id===10)return sim.s10.rcsTemp>=335||sim.s10.afwBearing>=120||sim.s10.rcpBearing>=125;return false}
function failureCause(){const id=stage.id;if(id===0)return sim.s0.sgB<=15?'SG-B INVENTORY DEPLETED':'INADEQUATE HEAT REMOVAL';if(id===1)return 'PRIMARY COOLING / THERMAL LIMIT';if(id===2)return 'SG-B INVENTORY / FEEDWATER LOST';if(id===3)return 'INADEQUATE SECONDARY HEAT REMOVAL';if(id===4)return 'ALTERNATE HEAT REMOVAL NOT ESTABLISHED';if(id===5)return 'SAFETY BUS POWER LOST';if(id===6)return 'AUXILIARY FEEDWATER CAPACITY LOST';if(id===8)return 'PRIMARY COOLING LIMIT';if(id===9)return 'RCS INVENTORY LOST';if(id===10)return 'SUPPORT COOLING LOST';return 'PLANT SAFETY LIMIT EXCEEDED'}
function stableFor(){return stableSince===null?0:Math.max(0,sim.simTime-stableSince)}
function checkClear(){if(finished)return;updateSim();const safe=baseSafeState();if(debugLogEnabled&&debugLogLastSafe!==safe){debugLogAdd(`SAFE BASE ${debugLogLastSafe?'YES':'NO'} -> ${safe?'YES':'NO'}`);debugLogLastSafe=safe}const eligible=sim.simTime>=stage.minClear&&safe;if(eligible){if(stableSince===null){stableSince=sim.simTime;debugLogAdd('STABLE TIMER START')}}else if(stableSince!==null){debugLogAdd('STABLE TIMER RESET');stableSince=null}if(stableFor()>=stage.stable)finish('clear')}
function finish(reason){if(finished)return;updateSim();const clear=reason==='clear',timeout=reason==='timeout';debugLogAdd(clear?'RESULT CLEAR':timeout?'RESULT TIME LIMIT EXCEEDED':`RESULT PLANT FAILURE: ${failureCause()}`);finishAt=Date.now();finished=true;if(timer)clearInterval(timer);updateTimeStatus();clearTutorialUI();const banner=clear?'=== CLEAR ===':timeout?'=== TIME LIMIT EXCEEDED ===':'=== PLANT FAILURE ===';p('');p(banner,clear?'ok':'danger');if(!clear&&!timeout)p(`CAUSE: ${failureCause()}`,'danger');rightTitle.textContent=clear?'RESULT // CLEAR':timeout?'RESULT // TIME LIMIT':'RESULT // PLANT FAILURE';right.className='right-body';const tutorialDone=isTutorial()&&clear;const title=tutorialDone?'TUTORIAL COMPLETE':clear?'STAGE CLEAR':timeout?'TIME LIMIT EXCEEDED':'PLANT FAILURE';const note=timeout?'PLANT NOT RESTORED WITHIN ALLOWABLE TIME':tutorialDone?'BASIC OPERATION / MANUAL WORKFLOW COMPLETE':clear?'PLANT RESTORED / CONDITION RESOLVED':`PLANT SAFETY LIMIT EXCEEDED<br>CAUSE: ${failureCause()}`;right.innerHTML=`<div class="result"><h2>${title}</h2><p>${note}<br>${stageLabel()}<br>PLANT ELAPSED ${fmtPlantClock(sim.simTime)}<br>CONTROL ACTIONS ${controlCount}</p><button id="retry">RETRY</button><button id="sel">STAGE SELECT</button></div>`;right.querySelector('#retry').onclick=()=>isTutorial()?startTutorial():startStage(stage,mode);right.querySelector('#sel').onclick=showSelect}
function tick(){if(!stage||finished)return;updateSim();if(isSimulation()){if(failureState()&&!simulationFailureLatched){simulationFailureLatched=true;p('','danger');p('=== PLANT FAILURE CONDITION ===','danger');p(`CAUSE: ${failureCause()}`,'danger');p('SIMULATION CONTINUES — TYPE RESET TO RESTORE NORMAL STATE','alarm');debugLogAdd(`SIMULATION FAILURE CONDITION: ${failureCause()}`)}return}if(failureState()){finish('failure');return}if(!isTutorial()&&timeLimitRemaining()<=0){finish('timeout');return}checkClear()}
function debugExtra(){const id=stage.id;if(id===0)return [`RCP-A STATE  ${sim.rcpA.state}`,`FRV-B ACT    ${sim.s0.frvActual.toFixed(1)} %`,`SG-B LEVEL   ${sim.s0.sgB.toFixed(1)} %`,`AFW-B FLOW   ${sim.s0.afwBFlow.toFixed(1)} %`,`RCS HOT LEG  ${sim.s0.rcsTemp.toFixed(1)} C`];if(id===1)return [`RCP-A STATE  ${sim.rcpA.state}`,`RCP-A FLOW   ${sim.rcpA.flow.toFixed(1)} %`,`THERM RISK   ${sim.s1.thermalRisk.toFixed(3)}`,`RCS HOT LEG  ${sim.s1.rcsTemp.toFixed(1)} C`];if(id===2)return [`FRV-B CMD    ${sim.s2.frvCmd}`,`FRV-B ACT    ${sim.s2.frvActual.toFixed(1)} %`,`FW-B FLOW    ${sim.s2.fw.toFixed(1)} %`,`AFW FLOW     ${sim.s2.afwFlow.toFixed(1)} %`,`SG-B LEVEL   ${sim.s2.sg.toFixed(1)} %`,`SG-B TREND   ${sim.s2.trend>=0?'+':''}${sim.s2.trend.toFixed(3)} %/m`];if(id===3)return [`SG PRESS     ${sim.s3.sgPressure.toFixed(2)} MPa`,`SG LEVEL     ${sim.s3.sgLevel.toFixed(1)} %`,`STEAM DUMP   ${sim.s3.steamDumpActual.toFixed(1)} %`,`AFW FLOW     ${sim.s3.afwFlow.toFixed(1)} %`,`RCS HOT LEG  ${sim.s3.rcsTemp.toFixed(1)} C`];if(id===4)return [`COND PRESS   ${sim.s4.condenser.toFixed(1)} kPa`,`ATM FLOW     ${sim.s4.atmFlow.toFixed(1)} %`,`AFW FLOW     ${sim.s4.afwFlow.toFixed(1)} %`,`SG LEVEL     ${sim.s4.sgLevel.toFixed(1)} %`,`RCS HOT LEG  ${sim.s4.rcsTemp.toFixed(1)} C`];if(id===5)return [`EDG-A/B SPD  ${sim.s5.edgA.speed.toFixed(0)} / ${sim.s5.edgB.speed.toFixed(0)} %`,`BUS-A/B      ${sim.s5.busA.toFixed(0)} / ${sim.s5.busB.toFixed(0)} %`,`BRK-A/B      ${sim.s5.edgA.breaker} / ${sim.s5.edgB.breaker}`];if(id===6)return [`AFW-A/B/C    ${sim.s6.afwA.toFixed(0)} / ${sim.s6.afwB.toFixed(0)} / ${sim.s6.afwC.toFixed(0)} %`,`AFW-B VALVE  ${sim.s6.afwValveActual.toFixed(1)} %`,`SG-B LEVEL   ${sim.s6.sgB.toFixed(1)} %`,`RCS HOT LEG  ${sim.s6.rcsTemp.toFixed(1)} C`];if(id===7)return [`CH1/2/3      ${sim.s7.ch1.toFixed(0)} / ${sim.s7.ch2.toFixed(1)} / ${sim.s7.ch3.toFixed(1)} %`,`DIAG          ${sim.s7.diagState}`,`REPORTED      ${sim.s7.reported?'YES':'NO'}`];if(id===8)return [`DECAY HEAT    ${sim.s8.decayHeat.toFixed(2)} %`,`RCS HOT LEG  ${sim.s8.rcsTemp.toFixed(1)} C`,`RCS TREND    ${sim.s8.rcsTrend>=0?'+':''}${sim.s8.rcsTrend.toFixed(3)} C/m`,`RCP-A STATE  ${sim.rcpA.state}`];if(id===9)return [`RCS PRESS     ${sim.s9.pressure.toFixed(2)} MPa`,`PZR LEVEL     ${sim.s9.pzrLevel.toFixed(1)} %`,`INVENTORY     ${sim.s9.inventory.toFixed(1)} %`,`SI FLOW       ${sim.s9.siFlow.toFixed(1)} %`,`LETDOWN ISO    ${sim.s9.letdownIso}`];if(id===10)return [`CCW-B STATE   ${sim.s10.ccwB}`,`CCW FLOW      ${sim.s10.ccwFlow.toFixed(1)} %`,`CCW TEMP      ${sim.s10.headerTemp.toFixed(1)} C`,`RCP BRG       ${sim.s10.rcpBearing.toFixed(1)} C`,`AFW BRG       ${sim.s10.afwBearing.toFixed(1)} C`,`RCS HOT LEG   ${sim.s10.rcsTemp.toFixed(1)} C`];return []}
function execute(raw){const text=raw.trim();if(!text)return;cmdHistory.push(text);histPos=cmdHistory.length;p('> '+text);const up=text.toUpperCase(),a=up.split(/\s+/);if(up==='DEBUG LOG ON'){debugLogEnabled=true;if(stage){debugLog=[];debugLogNextSample=Math.ceil(sim.simTime/5)*5;if(debugLogNextSample<=sim.simTime)debugLogNextSample+=5;debugLogLastSafe=baseSafeState();debugLogAdd('DEBUG LOG ON');debugSnapshot()}block(['DEBUG LOG','STATE            ON','SAMPLE INTERVAL  5 plant min','EVENT CAPTURE    ON']);return}if(up==='DEBUG LOG OFF'){debugLogAdd('DEBUG LOG OFF');debugLogEnabled=false;block(['DEBUG LOG','STATE            OFF']);return}if(up==='DEBUG LOG CLEAR'){debugLog=[];if(stage)debugLogAdd('DEBUG LOG CLEARED');block(['DEBUG LOG','LOG CLEARED']);return}if(up==='DEBUG LOG SHOW'){if(!debugLog.length){block(['DEBUG LOG','NO LOG DATA']);return}block(['DEBUG LOG',...debugLog,'END DEBUG LOG']);return}if(up==='DEBUG STATE'){updateSim();block(['DEBUG STATE',`STAGE         ${stage?.id??'NONE'}`,`PLANT ELAPSED ${stage?fmtPlantClock(sim.simTime,true):'00:00:00'}`,`PLANT TIME    ${stage?fmtPlantClock(plantMarginMinutes()):'--:--'}`,`TIME LIMIT    ${stage?fmtPlantClock(timeLimitRemaining()):'--:--'}`,`CONTROL ACT   ${controlCount}`,`SAFE BASE     ${stage&&baseSafeState()?'YES':'NO'}`,`MIN CLEAR     ${stage?.minClear??0} plant min`,`STABLE FOR   ${stage?stableFor().toFixed(1):'0.0'} / ${stage?.stable??0} plant min`,`CLEAR READY  ${stage&&!finished&&sim.simTime>=stage.minClear&&baseSafeState()&&stableFor()>=stage.stable?'YES':'NO'}`,...(stage?debugExtra():[])]);return}
 if(up==='DEBUG TIME'){const now=stage&&sim?sim.simTime:0;block(['DEBUG TIME',`PLANT ELAPSED   ${fmtPlantClock(now,true)}`,`PLANT TIME      ${stage?fmtPlantClock(plantMarginMinutes()):'--:--'}`,`TIME LIMIT      ${stage?fmtPlantClock(timeLimitRemaining()):'--:--'}`,`LAST COMMAND    ${lastCommand??'NONE'}`,`LAST COMMAND AT ${fmtTime(lastCommandAt)}`,`SINCE COMMAND   ${lastCommandAt===null?'--':fmtPlantClock(now-lastCommandAt,true)}`,`LAST CONTROL    ${lastControl??'NONE'}`,`LAST CONTROL AT ${fmtTime(lastControlAt)}`,`SINCE CONTROL   ${lastControlAt===null?'--':fmtPlantClock(now-lastControlAt,true)}`,finished?'CLOCK           FROZEN':'CLOCK           RUNNING']);return}
 if(up==='DEBUG SENSORS'){if(stage?.id===7)block(['DEBUG SENSORS',`SG-B TRUE ${sim.s7.trueLevel.toFixed(1)} / CH1 ${sim.s7.ch1.toFixed(1)} / CH2 ${sim.s7.ch2.toFixed(1)} / CH3 ${sim.s7.ch3.toFixed(1)}`]);else block(['DEBUG SENSORS','NO SENSOR FAULT']);return}
 if(up==='DEBUG PROTECTION'){block(['DEBUG PROTECTION',stage&&sim.reactorTripped?'RPS TRIP COMPLETE / POST-TRIP LOGIC ACTIVE':'RPS STANDBY']);return}
 if(/^STAGE-(?:[1-9]|10)$/.test(up)){startStage(STAGES[Number(up.split('-')[1])-1],'stage');return}if(up==='TUTORIAL'){startTutorial();return}if(up==='SIMULATION'){startSimulation();return}
 if(stage){updateSim();lastCommand=up;lastCommandAt=sim.simTime;if(a[0]==='CONTROL'){lastControl=up;lastControlAt=lastCommandAt}tutorialOnCommandExecuted(up)}
 if(a[0]==='REPORT'){if(!stage||stage.id!==7){p('REPORT COMMAND NOT APPLICABLE TO CURRENT PLANT STATE','danger');return}if(!sim.s7.diagComplete){p('REPORT REJECTED: DIAGNOSTIC NOT COMPLETE','danger');return}if(up!=='REPORT SG-B-LVL-CH1'){p('REPORT REJECTED: DEVICE NOT CONFIRMED FAILED','danger');return}if(sim.s7.reported){p('REPORT ACKNOWLEDGED: SG-B-LVL-CH1 ALREADY REPORTED','alarm');return}sim.s7.reported=true;stableSince=null;p('FAULT REPORT ACCEPTED','ok');block(['SG-B-LVL-CH1 MARKED OUT OF SERVICE','VALID CHANNELS: CH2 / CH3'],'alarm');debugLogAdd('EVENT FAULT REPORT ACCEPTED: SG-B-LVL-CH1');return}
 if(up==='CLEAR'){out.innerHTML='';return}
 if(up==='RESET'){if(resetSimulation())return;p('RESET IS AVAILABLE IN SIMULATION MODE ONLY','danger');return}
 if(up==='HELP'){block(['COMMAND FAMILIES','STATUS [SYSTEM]','READ <DEVICE>','HISTORY <DEVICE> <PARAMETER>','ALARM [DETAIL]','CONTROL <DEVICE> <ACTION>','CONTROL <INSTRUMENT> DIAG','CLEAR',isSimulation()?'RESET':'']);return}
 if(!stage){p('NO ACTIVE STAGE','danger');return}
 if(a[0]==='STATUS'){status((a[1]||'').toLowerCase());return}
 if(a[0]==='READ'){read(a.slice(1).join('-'));return}
 if(a[0]==='HISTORY'){historyCmd(a[1],a[2]||'');return}
 if(a[0]==='ALARM'){alarms(a[1]==='DETAIL');return}
 if(a[0]==='CONTROL'){control(up);return}
 p('UNKNOWN COMMAND. See COMMAND REFERENCE in the manual.','danger')}
document.getElementById('executeBtn').onclick=()=>{execute(input.value);input.value=''};input.onkeydown=e=>{if(e.key==='Enter'){execute(input.value);input.value=''}else if(e.key==='ArrowUp'){if(cmdHistory.length){histPos=Math.max(0,histPos-1);input.value=cmdHistory[histPos]||'';e.preventDefault()}}else if(e.key==='ArrowDown'){histPos=Math.min(cmdHistory.length,histPos+1);input.value=cmdHistory[histPos]||'';e.preventDefault()}};returnBtn.onclick=showSelect;showSelect();
})();
