(()=>{
const out=document.getElementById('terminalOut'),input=document.getElementById('commandInput'),right=document.getElementById('rightBody'),rightTitle=document.getElementById('rightTitle'),returnBtn=document.getElementById('returnStageBtn'),timeStatus=document.getElementById('timeStatus');
let stage=null,startAt=0,finishAt=0,timer=null,controls=new Set(),controlCount=0,cmdHistory=[],histPos=0,finished=false,sim=null,lastCommand=null,lastCommandAt=null,lastControl=null,lastControlAt=null,stableSince=null;
let mode='stage',tutorialStep=0,tutorialCoach=null,tutorialHighlight=null,simulationFailureLatched=false;
let debugLogEnabled=true,debugLog=[],debugLogNextSample=5,debugLogLastSafe=null;
const isTutorial=()=>mode==='tutorial';
const isSimulation=()=>mode==='simulation';
const stageLabel=()=>isTutorial()?'TUTORIAL':isSimulation()?'SIMULATION':`STAGE-${stage?.id??'-'}`;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const approach=(v,target,rate,dt)=>v<target?Math.min(target,v+rate*dt):Math.max(target,v-rate*dt);
const trains=['A','B','C'];
function fmtPlantClock(minutes,withSeconds=false){if(minutes===null||!Number.isFinite(minutes))return '--:--';const v=Math.max(0,minutes),h=Math.floor(v/60),m=Math.floor(v%60);if(!withSeconds)return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;const sec=Math.floor((v-Math.floor(v))*60);return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}
const p=(t='',c='')=>{const d=document.createElement('div');d.textContent=t;if(c)d.className=c;out.appendChild(d);out.scrollTop=out.scrollHeight;if(debugLogEnabled&&stage&&t&&(t.startsWith('AUTO ACTION:')||t.startsWith('INTERLOCK:')||t.startsWith('COMMAND ACCEPTED:')||t.startsWith('COMMAND REJECTED:')||t.startsWith('RPS:')||t.startsWith('RCP-A:')||t.startsWith('INSTRUMENT DIAGNOSTIC')||t.startsWith('FAULT REPORT')))debugLogAdd(`EVENT ${t}`)};
const block=(a,c='')=>p(a.join('\n'),c);
function logTime(){return stage&&sim?sim.simTime:0}
function debugLogAdd(text,t=logTime()){if(debugLogEnabled)debugLog.push(`[P+${fmtPlantClock(t,true)}] ${text}`)}
function decayHeat(minutes){const sec=minutes*60,pts=[[0,6.5],[60,4.0],[300,2.8],[600,2.3],[1800,1.8],[28800,1.0]];for(let i=1;i<pts.length;i++){if(sec<=pts[i][0]){const [t0,v0]=pts[i-1],[t1,v1]=pts[i];const q=(sec-t0)/(t1-t0);return v0+(v1-v0)*q}}return 1.0}
function flowFromFrv(pos){if(pos<=10)return pos*2.5;if(pos<=25)return 25+(pos-10)*(35/15);if(pos<=50)return 60+(pos-25)*(40/25);return Math.min(105,100+(pos-50)*.5)}
function newTrain(name){return {name,state:'RUNNING',speed:100,flow:100,vib:1.0,bearing:70,stopAt:null}}
function newEdg(name){return {name,state:'STANDBY',speed:0,breakerCmd:'AUTO',breaker:'OPEN',closeAt:null}}
function newInstrumentGroup(name,value=56){return {name,channels:{1:{value,quality:'VALID'},2:{value:value+.2,quality:'VALID'},3:{value:value-.2,quality:'VALID'}},diagState:'IDLE',diagAt:null,diagComplete:false,confirmedFailed:null,reported:new Set()}}
function makeNormalPlant(conditions={}){
 const s={simTime:0,lastTick:Date.now(),conditions:{...conditions},events:{},reactor:{tripped:false,tripAt:null},turbine:{tripped:false},
  rcp:{A:newTrain('A'),B:newTrain('B'),C:newTrain('C')},
  rcs:{pressure:15.5,pressureTrend:0,temp:320,tempTrend:0,inventory:100,inventoryTrend:0,pzrLevel:52},
  sg:{A:{level:56,trend:0,pressure:6.9,steamFlow:100,mfwFlow:100,afwFlow:0},B:{level:56,trend:0,pressure:6.9,steamFlow:100,mfwFlow:100,afwFlow:0},C:{level:56,trend:0,pressure:6.9,steamFlow:100,mfwFlow:100,afwFlow:0}},
  mfw:{available:true,frv:{A:{cmd:'AUTO',actual:50,manualOverride:false},B:{cmd:'AUTO',actual:50,manualOverride:false},C:{cmd:'AUTO',actual:50,manualOverride:false}}},
  afw:{demand:false,A:{pump:'STANDBY',valveCmd:'OPEN',valveActual:100,flow:0},B:{pump:'STANDBY',valveCmd:'OPEN',valveActual:100,flow:0},C:{pump:'STANDBY',valveCmd:'OPEN',valveActual:100,flow:0}},
  condenser:{pressure:7,available:true},steamDump:{cmd:'AUTO',actual:0,flow:0},atmDump:{cmd:'STANDBY',actual:0,flow:0},
  electrical:{offsiteAvailable:true,busA:100,busB:100,edgA:newEdg('A'),edgB:newEdg('B')},
  si:{demand:false,flow:0},letdown:{iso:'OPEN',flow:100,leakRate:0},
  ccw:{A:{state:'RUNNING',speed:100},B:{state:'STANDBY',speed:0},flow:100,flowTrend:0,temp:35,rcpBearing:70,afwBearing:70,edgTemp:70},
  instruments:{'SG-A-LVL':newInstrumentGroup('SG-A-LVL',56),'SG-B-LVL':newInstrumentGroup('SG-B-LVL',56),'SG-C-LVL':newInstrumentGroup('SG-C-LVL',56)},
  history:{nextSample:10,data:{}}
 };
 applyInitialConditions(s);
 seedHistory(s);
 return s
}
function applyInitialConditions(s){const c=s.conditions;
 if(c.rcpADegrade){s.rcp.A.speed=97;s.rcp.A.flow=95;s.rcp.A.vib=1.8;s.rcp.A.bearing=75}
 if(c.frvBDrift){s.mfw.frv.B.actual=48;s.sg.B.level=56}
 if(c.initialTurbineTrip)s.turbine.tripped=true;
 if(c.offsiteLost){s.electrical.offsiteAvailable=false;s.electrical.busA=0;s.electrical.busB=0}
 if(c.mainFeedwaterLost)s.mfw.available=false;
 if(c.afwBValveClosed){s.afw.B.valveCmd='CLOSED';s.afw.B.valveActual=0}
 if(c.sgBLevelCh1StuckLow){s.instruments['SG-B-LVL'].channels[1].value=18}
 if(c.initialPostTrip){s.reactor.tripped=true;s.reactor.tripAt=0;s.turbine.tripped=true;s.afw.demand=true;for(const w of trains)s.afw[w].pump='RUNNING'}
 if(c.letdownLeak){s.letdown.leakRate=.30;s.letdown.flow=160}
 if(c.ccwAFailed){s.ccw.A.state='FAILED';s.ccw.A.speed=0}
 updateInstruments(s)
}
function plantClone(s){const q=typeof structuredClone==='function'?structuredClone(s):JSON.parse(JSON.stringify(s));for(const g of Object.values(q.instruments)){if(!(g.reported instanceof Set))g.reported=new Set(g.reported||[])}return q}
function eventOnce(s,key,msg,ctx,cls='alarm'){if(s.events[key])return;s.events[key]=true;if(ctx?.emit){p(msg,cls);debugLogAdd(`EVENT ${msg}`,s.simTime)}}
function tripReactor(s,cause,ctx){if(s.reactor.tripped)return;s.reactor.tripped=true;s.reactor.tripAt=s.simTime;s.turbine.tripped=true;eventOnce(s,'reactorTrip',`AUTO ACTION: REACTOR TRIP — ${cause}`,ctx)}
function demandAfw(s,ctx){if(!s.afw.demand){s.afw.demand=true;eventOnce(s,'afwDemand','AUTO ACTION: AUXILIARY FEEDWATER DEMAND',ctx)}for(const w of trains)if(s.afw[w].pump!=='FAILED')s.afw[w].pump='RUNNING'}
function demandSi(s,ctx){if(!s.si.demand){s.si.demand=true;eventOnce(s,'siDemand','AUTO ACTION: SAFETY INJECTION DEMAND',ctx)}}
function startEdgs(s,ctx){for(const key of ['edgA','edgB']){const e=s.electrical[key];if(e.state==='STANDBY'){e.state='CRANKING';eventOnce(s,`${key}Start`,`AUTO ACTION: ${key==='edgA'?'EDG-A':'EDG-B'} START — OFFSITE POWER LOST`,ctx)}}}
function updateRcp(r,dt,degrade=false,tutorial=false){
 if(r.state==='RUNNING'&&degrade){const f=tutorial?.35:1;r.speed=clamp(r.speed-.06*dt*f,tutorial?84:68,100);r.flow=clamp(r.flow-.17*dt*f,tutorial?78:55,100);r.vib=clamp(r.vib+.007*dt*f,1,4.5);r.bearing=clamp(r.bearing+.045*dt*f,70,94)}
 else if(r.state==='COASTDOWN'){r.speed=clamp(r.speed-7*dt,0,100);r.flow=clamp(Math.max(8,r.speed),8,100);r.vib=approach(r.vib,1,.08,dt);r.bearing=approach(r.bearing,70,.1,dt);if(r.speed<=1){r.speed=0;r.flow=8;r.state='STOPPED'}}
 else if(r.state==='STOPPED'){r.flow=8;r.vib=approach(r.vib,1,.03,dt);r.bearing=approach(r.bearing,70,.08,dt)}
 else if(r.state==='STARTING'){r.speed=clamp(r.speed+10*dt,0,100);r.flow=clamp(Math.max(8,r.speed),8,100);r.vib=approach(r.vib,1,.08,dt);r.bearing=approach(r.bearing,70,.08,dt);if(r.speed>=99){r.speed=100;r.flow=100;r.state='RUNNING'}}
 else if(r.state==='FAILED'){r.speed=approach(r.speed,0,8,dt);r.flow=approach(r.flow,8,8,dt)}
}
function updateElectrical(s,dt,ctx){const e=s.electrical;
 if(!e.offsiteAvailable)startEdgs(s,ctx);
 for(const key of ['edgA','edgB']){const d=e[key];if(d.state==='CRANKING'){d.speed=clamp(d.speed+10*dt,0,100);if(d.speed>=100)d.state='RUNNING'}else if(d.state==='RUNNING')d.speed=100;else if(d.state==='FAILED')d.speed=approach(d.speed,0,10,dt)}
 if(!e.offsiteAvailable){if(e.edgA.state==='RUNNING'&&e.edgA.breakerCmd==='AUTO'&&e.edgA.breaker==='OPEN'){e.edgA.breaker='CLOSED';eventOnce(s,'edgABreakerAuto','AUTO ACTION: EDG-A BREAKER CLOSE',ctx)}if(e.edgB.state==='RUNNING'&&e.edgB.breakerCmd==='AUTO'&&e.edgB.breaker==='OPEN'&&!s.conditions.edgBAutoBreakerFail){e.edgB.breaker='CLOSED';eventOnce(s,'edgBBreakerAuto','AUTO ACTION: EDG-B BREAKER CLOSE',ctx)}}
 for(const key of ['edgA','edgB']){const d=e[key];if(d.breakerCmd==='CLOSE'&&d.closeAt!==null&&s.simTime-d.closeAt>=2&&d.state==='RUNNING')d.breaker='CLOSED'}
 const aTarget=e.offsiteAvailable?100:(e.edgA.state==='RUNNING'&&e.edgA.breaker==='CLOSED'?100:0),bTarget=e.offsiteAvailable?100:(e.edgB.state==='RUNNING'&&e.edgB.breaker==='CLOSED'?100:0);e.busA=approach(e.busA,aTarget,25,dt);e.busB=approach(e.busB,bTarget,25,dt)
}
function updateCcw(s,dt){const c=s.ccw;if(s.conditions.ccwAFailed){c.A.state='FAILED';c.A.speed=0}
 for(const k of ['A','B']){const d=c[k];if(d.state==='STARTING'){d.speed=clamp(d.speed+5*dt,0,100);if(d.speed>=100)d.state='RUNNING'}else if(d.state==='RUNNING')d.speed=100;else if(['STANDBY','FAILED'].includes(d.state))d.speed=approach(d.speed,0,10,dt)}
 const target=(c.A.state==='RUNNING'||c.B.state==='RUNNING')?100:0,old=c.flow;c.flow=approach(c.flow,target,target?2.5:.35,dt);c.flowTrend=(c.flow-old)/dt;const deficit=Math.max(0,100-c.flow)/100;
 if(c.flow>=70){c.temp=approach(c.temp,35,.10,dt);c.rcpBearing=approach(c.rcpBearing,70,.10,dt);c.afwBearing=approach(c.afwBearing,70,.08,dt);c.edgTemp=approach(c.edgTemp,70,.10,dt)}else{const extra=c.flow<30?.15:0;c.temp=clamp(c.temp+(.035+deficit*.15+extra*.4)*dt,30,120);c.rcpBearing=clamp(c.rcpBearing+(.025+deficit*.20+extra)*dt,65,150);c.afwBearing=clamp(c.afwBearing+(.02+deficit*.20+extra)*dt,65,150);c.edgTemp=clamp(c.edgTemp+(.03+deficit*.22+extra)*dt,60,160)}
 if(c.rcpBearing>=125&&s.rcp.A.state!=='FAILED')s.rcp.A.state='FAILED';if(c.afwBearing>=120)for(const w of trains)s.afw[w].pump='FAILED';if(c.edgTemp>=130){for(const key of ['edgA','edgB']){s.electrical[key].state='FAILED';s.electrical[key].breaker='OPEN'}}
}
function updateActuators(s,dt){
 updateRcp(s.rcp.A,dt,!!s.conditions.rcpADegrade,!!s.conditions.tutorialMode);updateRcp(s.rcp.B,dt,false,false);updateRcp(s.rcp.C,dt,false,false);
 for(const w of trains){const f=s.mfw.frv[w];let target=f.cmd==='OPEN'?60:f.cmd==='CLOSE'?0:50;if(w==='B'&&s.conditions.frvBDrift&&f.cmd==='AUTO')target=0;f.actual=approach(f.actual,target,(w==='B'&&s.conditions.frvBDrift&&f.cmd==='AUTO')?.11:(f.cmd==='CLOSE'?1.8:1.4),dt)}
 for(const w of trains){const a=s.afw[w];a.valveActual=approach(a.valveActual,a.valveCmd==='CLOSED'?0:100,5,dt)}
 const autoSteam=s.turbine.tripped?(s.conditions.steamDumpAutoLimit??100):0,steamTarget=s.steamDump.cmd==='OPEN'?100:s.steamDump.cmd==='CLOSE'?0:autoSteam;s.steamDump.actual=approach(s.steamDump.actual,steamTarget,3,dt);
 const atmTarget=s.atmDump.cmd==='OPEN'?100:0;s.atmDump.actual=approach(s.atmDump.actual,atmTarget,4,dt)
}
function updateFlows(s,dt){
 const e=s.electrical;for(const w of trains){const f=s.mfw.frv[w];const target=s.mfw.available&&!s.turbine.tripped?flowFromFrv(f.actual):0;s.sg[w].mfwFlow=approach(s.sg[w].mfwFlow,target,3,dt)}
 const power={A:e.busA>=90,B:e.busB>=90,C:e.busA>=90},afwPerf=clamp((120-s.ccw.afwBearing)/20,0,1);for(const w of trains){const a=s.afw[w],target=a.pump==='RUNNING'&&power[w]?a.valveActual*afwPerf:0;a.flow=approach(a.flow,target,5,dt);s.sg[w].afwFlow=a.flow}
 s.condenser.available=s.condenser.pressure<25;const condAcceptance=clamp((25-s.condenser.pressure)/15,0,1);s.steamDump.flow=s.steamDump.actual*condAcceptance;s.atmDump.flow=s.atmDump.actual;
 const path=s.turbine.tripped?Math.max(s.steamDump.flow,s.atmDump.flow):100;for(const w of trains){const g=s.sg[w];g.steamFlow=path;const afwEquivalent=s.reactor.tripped?g.afwFlow:g.afwFlow*.25,inflow=g.mfwFlow+afwEquivalent,outflow=g.steamFlow;const scale=s.turbine.tripped?.002:.006;g.trend=(inflow-outflow)*scale;g.level=clamp(g.level+g.trend*dt,0,100);if(s.turbine.tripped){if(path<60)g.pressure=clamp(g.pressure+(.006+(60-path)*.00008)*dt,6.5,8.2);else g.pressure=approach(g.pressure,6.9,.025,dt)}else g.pressure=approach(g.pressure,6.9,.02,dt)}
}
function updateLeakAndInventory(s,dt){const r=s.rcs,oldP=r.pressure,oldI=r.inventory;
 if(s.conditions.letdownLeak&&s.letdown.iso==='OPEN'){s.letdown.leakRate=.30;s.letdown.flow=160;const injection=s.si.flow/100*.10;r.inventory=clamp(r.inventory-(s.letdown.leakRate-injection)*dt,0,110);r.pzrLevel=clamp(r.pzrLevel-(s.reactor.tripped?.08:.18)*dt,0,100);r.pressure=clamp(r.pressure-(s.reactor.tripped?.004:.015)*dt,10,16)}else{s.letdown.leakRate=0;s.letdown.flow=s.letdown.iso==='OPEN'?100:0;if(s.reactor.tripped&&r.inventory<100)r.inventory=approach(r.inventory,100,.16,dt);r.pzrLevel=approach(r.pzrLevel,52,.12,dt);r.pressure=approach(r.pressure,15.5,.025,dt)}
 r.inventoryTrend=(r.inventory-oldI)/dt;r.pressureTrend=(r.pressure-oldP)/dt;s.si.flow=approach(s.si.flow,s.si.demand?100:0,2,dt)
}
function updateProtection(s,ctx){const minRcp=Math.min(...trains.map(w=>s.rcp[w].flow)),minSg=Math.min(...trains.map(w=>s.sg[w].level));
 if(s.turbine.tripped&&!s.reactor.tripped)tripReactor(s,'TURBINE TRIP',ctx);
 if(!s.reactor.tripped&&minRcp<75)tripReactor(s,'PRIMARY FLOW VERY LOW',ctx);
 if(!s.reactor.tripped&&minSg<=50)tripReactor(s,'STEAM GENERATOR LEVEL LOW-LOW',ctx);
 if(s.condenser.pressure>=25&&!s.turbine.tripped){s.turbine.tripped=true;eventOnce(s,'turbineTripCondenser','AUTO ACTION: TURBINE TRIP — CONDENSER VACUUM LOW',ctx);tripReactor(s,'CONDENSER VACUUM LOW',ctx)}
 if(!s.electrical.offsiteAvailable&&s.simTime>=3&&!s.reactor.tripped)tripReactor(s,'LOSS OF OFFSITE POWER',ctx);
 if(s.rcs.pressure<=14.8){if(!s.reactor.tripped)tripReactor(s,'RCS PRESSURE LOW',ctx);demandSi(s,ctx)}
 if(s.ccw.flow<=15&&!s.reactor.tripped)tripReactor(s,'SUPPORT COOLING LOW',ctx);
 if(s.reactor.tripped||!s.mfw.available)demandAfw(s,ctx)
}
function updatePrimaryThermal(s,dt){const r=s.rcs,old=r.temp;
 if(!s.reactor.tripped){const circulation=trains.reduce((a,w)=>a+s.rcp[w].flow,0)/300,feed=trains.reduce((a,w)=>a+s.sg[w].mfwFlow,0)/300,cooling=Math.min(circulation,feed);if(cooling>=.85)r.temp=approach(r.temp,320,.03,dt);else r.temp=clamp(r.temp+(.85-cooling)*.09*dt,295,340)}
 else{const afwCap=clamp(trains.reduce((a,w)=>a+s.afw[w].flow,0)/200,0,1),steamCap=clamp(Math.max(s.steamDump.flow,s.atmDump.flow)/100,0,1),circ=clamp(trains.reduce((a,w)=>a+s.rcp[w].flow,0)/300,0,1),removal=Math.min(afwCap,steamCap);if(removal>=.75){const circFactor=clamp((circ-.35)/.65,.2,1);r.temp=clamp(r.temp-.08*circFactor*dt,295,340)}else r.temp=clamp(r.temp+(.75-removal)*.12*dt,295,340)}
 r.tempTrend=(r.temp-old)/dt
}
function updateInstruments(s){for(const w of trains){const g=s.instruments[`SG-${w}-LVL`],v=s.sg[w].level;for(const n of [1,2,3]){if(w==='B'&&n===1&&s.conditions.sgBLevelCh1StuckLow)g.channels[n].value=18;else g.channels[n].value=v+(n===1?0:n===2?.3:-.4)}}}
function updateDiagnostics(s,ctx){for(const [name,g] of Object.entries(s.instruments)){if(g.diagState==='RUNNING'&&g.diagAt!==null&&s.simTime-g.diagAt>=20&&!g.diagComplete){g.diagState='COMPLETE';g.diagComplete=true;const failed=Object.entries(g.channels).find(([,c])=>c.quality==='FAILED' || (name==='SG-B-LVL'&&s.conditions.sgBLevelCh1StuckLow&&c===g.channels[1]));if(name==='SG-B-LVL'&&s.conditions.sgBLevelCh1StuckLow){g.channels[1].quality='FAILED';g.confirmedFailed=`${name}-CH1`}else g.confirmedFailed=null;if(ctx?.emit){p('INSTRUMENT DIAGNOSTIC COMPLETE','ok');const lines=[''];for(const n of [1,2,3])lines.push(`${name}-CH${n}   ${g.channels[n].quality==='FAILED'?'FAILED — STUCK LOW':'NORMAL'}`);if(g.confirmedFailed)lines.push('','MAINTENANCE NOTIFICATION REQUIRED','TYPE: REPORT <DEVICE>');else lines.push('','NO CHANNEL FAULT DETECTED');block(lines,'alarm')}}}}
function sampleHistory(s,t){const vals={
 'RCP-A FLOW':s.rcp.A.flow,'RCP-A VIBRATION':s.rcp.A.vib,'RCP-A SPEED':s.rcp.A.speed,
 'SG-A LEVEL':s.sg.A.level,'SG-B LEVEL':s.sg.B.level,'SG-C LEVEL':s.sg.C.level,
 'FRV-A POSITION':s.mfw.frv.A.actual,'FRV-B POSITION':s.mfw.frv.B.actual,'FRV-C POSITION':s.mfw.frv.C.actual,
 'CONDENSER PRESSURE':s.condenser.pressure,'BUS-A VOLTAGE':s.electrical.busA,'BUS-B VOLTAGE':s.electrical.busB,
 'AFW-A FLOW':s.afw.A.flow,'AFW-B FLOW':s.afw.B.flow,'AFW-C FLOW':s.afw.C.flow,
 'SG-A-LVL-CH1 LEVEL':s.instruments['SG-A-LVL'].channels[1].value,'SG-B-LVL-CH1 LEVEL':s.instruments['SG-B-LVL'].channels[1].value,'SG-B-LVL-CH2 LEVEL':s.instruments['SG-B-LVL'].channels[2].value,'SG-C-LVL-CH1 LEVEL':s.instruments['SG-C-LVL'].channels[1].value,
 'RCS PRESSURE':s.rcs.pressure,'PZR LEVEL':s.rcs.pzrLevel,'CCW FLOW':s.ccw.flow};for(const [k,v] of Object.entries(vals))pushHist(s,k,t,v)}
function pushHist(s,key,t,v){const a=s.history.data[key]||(s.history.data[key]=[]);a.push({t,v});if(a.length>24)a.shift()}
function seedHistory(s){for(let t=-50;t<=0;t+=10)sampleHistory(s,t)}
function stepPlant(s,dt,ctx={emit:false,history:true}){s.simTime+=dt;
 if(s.conditions.condenserDegrade)s.condenser.pressure=clamp(s.condenser.pressure+.29*dt,0,40);
 updateActuators(s,dt);updateElectrical(s,dt,ctx);updateCcw(s,dt);updateFlows(s,dt);updateLeakAndInventory(s,dt);updateProtection(s,ctx);updateFlows(s,0);updatePrimaryThermal(s,dt);updateInstruments(s);updateDiagnostics(s,ctx);
 if(ctx.history!==false)while(s.history.nextSample<=s.simTime){sampleHistory(s,s.history.nextSample);s.history.nextSample+=10}
}
function failureStateFor(s){return s.rcs.temp>=335||s.rcs.inventory<=30||s.rcs.pressure<=11.5}
function failureCauseFor(s){if(s.rcs.inventory<=30||s.rcs.pressure<=11.5)return 'RCS INVENTORY LOST';if(s.electrical.busA<10&&s.electrical.busB<10&&s.reactor.tripped)return 'SAFETY BUS POWER LOST';if(s.ccw.flow<30&&(s.ccw.afwBearing>=120||s.ccw.rcpBearing>=125))return 'SUPPORT COOLING LOST';return 'INADEQUATE HEAT REMOVAL'}
function forecastFailureMinutes(){if(!sim)return null;if(failureStateFor(sim))return 0;const q=plantClone(sim),max=24*60,step=1;for(let m=step;m<=max;m+=step){stepPlant(q,step,{emit:false,history:false});if(failureStateFor(q))return m}return null}
function plantMarginMinutes(){return forecastFailureMinutes()}
function timeLimitRemaining(){if(!stage||!sim||isSimulation())return null;return Math.max(0,TIME_CONFIG.timeLimitMinutes-sim.simTime)}
function plantTimeDisplay(pm,tl){if(pm===null||!Number.isFinite(pm))return '--:--';if(tl!==null&&Number.isFinite(tl)&&pm>tl)return '&gt; TIME LIMIT';return fmtPlantClock(pm)}
function updateTimeStatus(){if(!timeStatus)return;if(!stage||!sim){timeStatus.innerHTML='<span>PLANT TIME&nbsp;&nbsp;--:--</span><span>TIME LIMIT&nbsp;&nbsp;--:--</span>';return}const pm=plantMarginMinutes(),tl=timeLimitRemaining(),plantText=plantTimeDisplay(pm,tl),plantCritical=pm!==null&&(tl===null||pm<=tl)&&pm<=60;timeStatus.innerHTML=`<span${plantCritical?' class="critical"':''}>PLANT TIME&nbsp;&nbsp;${plantText}</span><span${tl!==null&&tl<=60?' class="critical"':''}>TIME LIMIT&nbsp;&nbsp;${fmtPlantClock(tl)}</span>`}
function debugSnapshot(){if(!sim)return;debugLogAdd(`SNAPSHOT SAFE=${baseSafeState()?'YES':'NO'} STABLE=${stableFor().toFixed(1)}m PLANT=${fmtPlantClock(plantMarginMinutes())} LIMIT=${fmtPlantClock(timeLimitRemaining())} | ${debugExtra().join(' | ')}`)}
function debugSampleDue(){if(!debugLogEnabled||!sim)return;while(sim.simTime>=debugLogNextSample){debugSnapshot();debugLogNextSample+=5}}
function updateSim(){if(!stage||finished||!sim)return;const now=Date.now();let dt=(now-sim.lastTick)/1000/(TIME_CONFIG?.realSecondsPerPlantMinute??1);if(dt<=0)return;sim.lastTick=now;while(dt>0){const step=Math.min(.5,dt);stepPlant(sim,step,{emit:true,history:true});dt-=step}debugSampleDue();updateTimeStatus()}
function currentFissionPower(){if(!sim.reactor.tripped)return 100;const x=Math.max(0,sim.simTime-(sim.reactor.tripAt??0));if(x<2)return Math.max(5,100-47.5*x);if(x<5)return Math.max(.8,5-(x-2)*1.4);return 0}
function currentDecay(){return sim.reactor.tripped?decayHeat(Math.max(0,sim.simTime-(sim.reactor.tripAt??0))):null}
function instrumentSpread(name){const g=sim.instruments[name],v=[1,2,3].filter(n=>!g.reported.has(`${name}-CH${n}`)).map(n=>g.channels[n].value);return Math.max(...v)-Math.min(...v)}
function systemStates(){const steamWarn=trains.some(w=>sim.sg[w].level<50||sim.sg[w].level>65||sim.sg[w].pressure<6.6||sim.sg[w].pressure>7.2);const primaryWarn=trains.some(w=>sim.rcp[w].flow<95||sim.rcp[w].vib>1.4)||sim.rcs.pressure<15.2||sim.rcs.temp>325;const feedWarn=!sim.mfw.available||trains.some(w=>Math.abs(sim.sg[w].mfwFlow-100)>10)||sim.afw.demand;const elecWarn=!sim.electrical.offsiteAvailable||sim.electrical.busA<95||sim.electrical.busB<95;const instBad=Object.keys(sim.instruments).some(k=>instrumentSpread(k)>10),instReported=Object.values(sim.instruments).some(g=>g.reported.size>0);const supportWarn=sim.ccw.flow<90||sim.ccw.temp>45;return {reactor:sim.reactor.tripped?'TRIPPED':'NORMAL',primary:primaryWarn?'WARNING':'NORMAL',steam:steamWarn?'WARNING':'NORMAL',feedwater:feedWarn?'WARNING':'NORMAL',electrical:elecWarn?'WARNING':'NORMAL',safety:sim.reactor.tripped||sim.afw.demand||sim.si.demand?'ACTIVE':'STANDBY',instrument:instBad?'DISAGREEMENT':instReported?'CHANNEL OUT OF SERVICE':'NORMAL',support:supportWarn?'WARNING':'NORMAL'}}
function status(name){updateSim();const st=systemStates();if(!name){block([`REACTOR       ${st.reactor}`,`PRIMARY       ${st.primary}`,`STEAM         ${st.steam}`,`FEEDWATER     ${st.feedwater}`,`ELECTRICAL    ${st.electrical}`,`SAFETY        ${st.safety}`,`INSTRUMENT    ${st.instrument}`,`SUPPORT       ${st.support}`]);return}
 if(name==='reactor')block(['REACTOR',`STATE        ${sim.reactor.tripped?'TRIPPED':'RUNNING'}`,`POWER        ${currentFissionPower().toFixed(currentFissionPower()<10?1:0)} %`,`DECAY HEAT   ${sim.reactor.tripped?currentDecay().toFixed(1)+' %':'--'}`]);
 else if(name==='primary')block(['PRIMARY SYSTEM',...trains.map(w=>`LOOP-${w}       ${sim.rcp[w].flow<95||sim.rcp[w].state!=='RUNNING'?'WARNING':'NORMAL'}`),`RCS PRESS    ${sim.rcs.pressure.toFixed(1)} MPa`,`HOT LEG      ${sim.rcs.temp.toFixed(0)} C`]);
 else if(name==='steam'){const lines=['STEAM / SG'];for(const w of trains){const g=sim.instruments[`SG-${w}-LVL`];if(instrumentSpread(`SG-${w}-LVL`)>10)lines.push(`SG-${w} LEVEL   ${g.channels[1].value.toFixed(0)} / ${g.channels[2].value.toFixed(0)} / ${g.channels[3].value.toFixed(0)} %`);else lines.push(`SG-${w} LEVEL   ${sim.sg[w].level.toFixed(0)} %`)}lines.push(`SG PRESS     ${sim.sg.B.pressure.toFixed(2)} MPa`);block(lines)}
 else if(name==='feedwater')block(['FEEDWATER',...trains.map(w=>`MFW-${w} FLOW   ${sim.sg[w].mfwFlow.toFixed(0)} %`),...trains.map(w=>`AFW-${w} FLOW   ${sim.afw[w].flow.toFixed(0)} % AFW-RATED`),`AFW DEMAND   ${sim.afw.demand?'YES':'NO'}`]);
 else if(name==='turbine')block(['TURBINE / GENERATOR',`TURBINE      ${sim.turbine.tripped?'TRIPPED':'RUNNING'}`,`GENERATOR    ${sim.turbine.tripped?'OFFLINE':'ONLINE'}`]);
 else if(name==='condenser')block(['CONDENSER',`PRESSURE     ${sim.condenser.pressure.toFixed(1)} kPa(abs)`,`AVAILABLE    ${sim.condenser.available?'YES':'NO'}`]);
 else if(name==='electrical')block(['ELECTRICAL',`OFFSITE      ${sim.electrical.offsiteAvailable?'AVAILABLE':'LOST'}`,`BUS-A        ${sim.electrical.busA.toFixed(0)} %`,`BUS-B        ${sim.electrical.busB.toFixed(0)} %`,`EDG-A        ${sim.electrical.edgA.state}`,`EDG-B        ${sim.electrical.edgB.state}`]);
 else if(name==='safety')block(['SAFETY / PROTECTION',`RPS          ${sim.reactor.tripped?'TRIP COMPLETE':'STANDBY'}`,`AFW          ${sim.afw.demand?'DEMAND / ACTIVE':'STANDBY'}`,`SI           ${sim.si.demand?'DEMAND / ACTIVE':'STANDBY'}`,'INTERLOCKS   NORMAL']);
 else if(name==='instrumentation'){const lines=['INSTRUMENTATION'];for(const w of trains){const n=`SG-${w}-LVL`,g=sim.instruments[n];lines.push(`${n.padEnd(12)} ${instrumentSpread(n)>10?'DISAGREEMENT':g.reported.size?'OUT OF SERVICE':'NORMAL'} / DIAG ${g.diagState}`)}block(lines)}
 else if(name==='support')block(['SUPPORT / CCW',`CCW-A        ${sim.ccw.A.state}`,`CCW-B        ${sim.ccw.B.state}`,`HEADER FLOW  ${sim.ccw.flow.toFixed(0)} %`,`HEADER TEMP  ${sim.ccw.temp.toFixed(0)} C`]);
 else p('UNKNOWN STATUS SYSTEM','danger')}
function read(dev){updateSim();
 if(/^RCP-[ABC]$/.test(dev)){const w=dev.at(-1),r=sim.rcp[w];block([dev,`STATE        ${r.state}`,`SPEED        ${r.speed.toFixed(0)} %`,`FLOW         ${r.flow.toFixed(0)} %`,`VIBRATION    ${r.vib.toFixed(1)} INDEX`,`BEARING      ${(w==='A'?Math.max(r.bearing,sim.ccw.rcpBearing):r.bearing).toFixed(0)} C`])}
 else if(/^SG-[ABC]$/.test(dev)){const w=dev.at(-1),g=sim.sg[w],ig=sim.instruments[`SG-${w}-LVL`];const lines=[dev];if(instrumentSpread(`SG-${w}-LVL`)>10){for(const n of [1,2,3])lines.push(`LEVEL CH${n}    ${ig.channels[n].value.toFixed(0)} %`)}else lines.push(`LEVEL        ${g.level.toFixed(0)} %`);lines.push(`PRESSURE     ${g.pressure.toFixed(2)} MPa`,`STEAM FLOW   ${g.steamFlow.toFixed(0)} %`,`MFW FLOW     ${g.mfwFlow.toFixed(0)} %`,`AFW FLOW     ${g.afwFlow.toFixed(0)} % AFW-RATED`);block(lines)}
 else if(/^FRV-[ABC]$/.test(dev)){const w=dev.at(-1),f=sim.mfw.frv[w];block([dev,`COMMAND      ${f.cmd}`,`ACTUAL       ${f.actual.toFixed(0)} %`,`FLOW         ${sim.sg[w].mfwFlow.toFixed(0)} %`])}
 else if(dev==='CONDENSER')status('condenser');
 else if(/^EDG-[AB]$/.test(dev)){const w=dev.at(-1),e=sim.electrical[`edg${w}`];block([dev,`DEMAND       ${!sim.electrical.offsiteAvailable?'YES':'NO'}`,`ENGINE       ${e.state}`,`SPEED        ${e.speed.toFixed(0)} %`,`BREAKER CMD ${e.breakerCmd}`,`BREAKER      ${e.breaker}`,`COOLING TEMP ${sim.ccw.edgTemp.toFixed(0)} C`])}
 else if(/^EDG-[AB]-BREAKER$/.test(dev)){const w=dev[4],e=sim.electrical[`edg${w}`],bus=w==='A'?sim.electrical.busA:sim.electrical.busB;block([`${dev}`,`COMMAND      ${e.breakerCmd}`,`POSITION     ${e.breaker}`,`BUS-${w}        ${bus<10?'DEAD':'ENERGIZED'}`])}
 else if(/^BUS-[AB]$/.test(dev)){const w=dev.at(-1);block([dev,`VOLTAGE      ${(w==='A'?sim.electrical.busA:sim.electrical.busB).toFixed(0)} %`])}
 else if(dev==='OFFSITE')block(['OFFSITE POWER',`STATE        ${sim.electrical.offsiteAvailable?'AVAILABLE':'LOST'}`,`VOLTAGE      ${sim.electrical.offsiteAvailable?'100':'0'} %`]);
 else if(/^AFW-[ABC]$/.test(dev)){const w=dev.at(-1),a=sim.afw[w];block([dev,`DEMAND       ${sim.afw.demand?'YES':'NO'}`,`PUMP         ${a.pump}`,`FLOW         ${a.flow.toFixed(0)} % AFW-RATED`,`BEARING      ${sim.ccw.afwBearing.toFixed(0)} C`])}
 else if(/^AFW-VALVE-[ABC]$/.test(dev)){const w=dev.at(-1),a=sim.afw[w];block([`${dev} DELIVERY VALVE`,`COMMAND      ${a.valveCmd}`,`ACTUAL       ${a.valveActual.toFixed(0)} %`])}
 else if(/^SG-[ABC]-LVL-CH[123]$/.test(dev)){const m=dev.match(/^SG-([ABC])-LVL-CH([123])$/),name=`SG-${m[1]}-LVL`,n=Number(m[2]),g=sim.instruments[name],tag=`${name}-CH${n}`,quality=g.reported.has(tag)?'OUT OF SERVICE':g.channels[n].quality;block([dev,`VALUE        ${g.channels[n].value.toFixed(0)} %`,`QUALITY      ${quality}`])}
 else if(dev==='REACTOR')status('reactor');
 else if(dev==='RCS')block(['RCS',`PRESSURE     ${sim.rcs.pressure.toFixed(1)} MPa`,`HOT LEG      ${sim.rcs.temp.toFixed(0)} C`,`COLD LEG     ${(sim.rcs.temp-30).toFixed(0)} C`,'DELTA-T      30 C',`INVENTORY     ${sim.rcs.inventory.toFixed(0)} %`]);
 else if(dev==='PZR')block(['PZR',`PRESSURE     ${sim.rcs.pressure.toFixed(1)} MPa`,`LEVEL        ${sim.rcs.pzrLevel.toFixed(0)} %`,'HEATER       AUTO','SPRAY        AUTO']);
 else if(dev==='RCS-LETDOWN')block(['RCS LETDOWN',`FLOW         ${sim.letdown.flow.toFixed(0)} %`,`ISOLATION    ${sim.letdown.iso}`,`DOWNSTREAM   ${sim.letdown.leakRate>0?'LEAK INDICATION':'NORMAL'}`]);
 else if(dev==='RCS-LETDOWN-ISO')block(['RCS LETDOWN ISOLATION',`COMMAND      ${sim.letdown.iso}`,`POSITION     ${sim.letdown.iso}`]);
 else if(dev==='SI')block(['SAFETY INJECTION',`DEMAND       ${sim.si.demand?'YES':'NO'}`,`FLOW         ${sim.si.flow.toFixed(0)} % SI-RATED`]);
 else if(/^CCW-[AB]$/.test(dev)){const w=dev.at(-1),c=sim.ccw[w];block([dev,`STATE        ${c.state}`,`SPEED        ${c.speed.toFixed(0)} %`,`HEADER FLOW  ${sim.ccw.flow.toFixed(0)} %`])}
 else if(dev==='CCW-HEADER')block(['CCW HEADER',`FLOW         ${sim.ccw.flow.toFixed(0)} %`,`TEMP         ${sim.ccw.temp.toFixed(0)} C`,`TREND        ${sim.ccw.flowTrend>=0?'+':''}${sim.ccw.flowTrend.toFixed(2)} %/m`]);
 else if(dev==='RPS')status('safety');
 else if(dev==='TURBINE'||dev==='GENERATOR')status('turbine');
 else if(dev==='STEAM-DUMP')block(['STEAM-DUMP',`COMMAND      ${sim.steamDump.cmd}`,`ACTUAL       ${sim.steamDump.actual.toFixed(0)} %`,`FLOW         ${sim.steamDump.flow.toFixed(0)} %`,'HEAT SINK    CONDENSER',`AVAILABLE    ${sim.condenser.available?'YES':'NO'}`]);
 else if(dev==='ATM-DUMP')block(['ATM-DUMP',`COMMAND      ${sim.atmDump.cmd}`,`ACTUAL       ${sim.atmDump.actual.toFixed(0)} %`,`FLOW         ${sim.atmDump.flow.toFixed(0)} %`]);
 else p('UNKNOWN DEVICE','danger')}
function histLabel(t){if(t<0){const sec=Math.abs(Math.round(t));return `T-${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}const sec=Math.round(t);return `T+${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function historyCmd(dev,param){updateSim();const key=`${dev} ${param}`.trim(),data=sim.history.data[key];if(!data||!data.length){p('NO HISTORY DATA','danger');return}const unit=key.includes('VIBRATION')?'':key.includes('POSITION')||key.includes('FLOW')||key.includes('LEVEL')||key.includes('VOLTAGE')||key.includes('SPEED')?' %':key.includes('PRESSURE')?' MPa':'';const lines=[`${key} HISTORY`];data.slice(-8).forEach(x=>lines.push(`${histLabel(x.t).padEnd(10)} ${Number(x.v).toFixed(key.includes('VIBRATION')||key.includes('PRESSURE')?1:0)}${unit}`));lines.push(`NOW        ${Number(data.at(-1).v).toFixed(key.includes('VIBRATION')||key.includes('PRESSURE')?1:0)}${unit}`);block(lines)}
function activeAlarms(){const a=[],add=(code,msg)=>a.push([code,msg]);
 for(const w of trains){const r=sim.rcp[w];if(r.speed<95)add(`P-11${w.charCodeAt(0)-65}`,`RCP-${w} SPEED LOW`);if(r.flow<90)add(`P-12${w.charCodeAt(0)-65}`,`PRIMARY LOOP-${w} FLOW LOW`);if(r.vib>2)add(`P-13${w.charCodeAt(0)-65}`,`RCP-${w} VIBRATION HIGH`)}
 for(const w of trains){const g=sim.sg[w];if(g.level<52)add(`S-12${w.charCodeAt(0)-65}`,`SG-${w} LEVEL LOW`);if(Math.abs(g.mfwFlow-g.steamFlow)>25&&!sim.turbine.tripped)add(`F-12${w.charCodeAt(0)-65}`,`FW-${w} / STEAM FLOW MISMATCH`);if(sim.afw.demand&&sim.afw[w].pump==='RUNNING'&&sim.afw[w].flow<40)add(`F-16${w.charCodeAt(0)-65}`,`AFW-${w} DELIVERY LOW`)}
 if(sim.condenser.pressure>15)add('C-140','CONDENSER VACUUM DEGRADED');if(sim.condenser.pressure>=25)add('C-141','CONDENSER VACUUM LOW');if(sim.reactor.tripped)add('R-001','REACTOR TRIP');if(sim.turbine.tripped)add('T-001','TURBINE TRIP');
 if(!sim.electrical.offsiteAvailable)add('E-150','OFFSITE POWER LOST');if(sim.electrical.busA<90)add('E-151','BUS-A UNDERVOLTAGE');if(sim.electrical.busB<90)add('E-152','BUS-B UNDERVOLTAGE');if(sim.electrical.edgB.state==='RUNNING'&&sim.electrical.busB<10)add('E-153','EDG-B OUTPUT NOT CONNECTED');
 for(const w of trains){const name=`SG-${w}-LVL`,g=sim.instruments[name];if(instrumentSpread(name)>10)add(`I-17${w.charCodeAt(0)-65}`,`${name} CHANNEL DISAGREEMENT`);for(const n of [1,2,3])if(g.reported.has(`${name}-CH${n}`))add(`I-18${w.charCodeAt(0)-65}`,`${name}-CH${n} OUT OF SERVICE`)}
 if(sim.rcs.pressure<15.2)add('R-190','RCS PRESSURE LOW');if(sim.rcs.pzrLevel<45)add('R-191','PZR LEVEL LOW');if(sim.letdown.flow>130)add('R-192','RCS LETDOWN FLOW HIGH');if(sim.rcs.inventory<50)add('R-194','RCS INVENTORY LOW');
 if(sim.ccw.A.state==='FAILED')add('W-200','CCW-A UNAVAILABLE');if(sim.ccw.flow<70)add('W-201','CCW HEADER FLOW LOW');if(sim.ccw.rcpBearing>85)add('W-202','RCP AUX BEARING TEMP HIGH');if(sim.ccw.afwBearing>85)add('W-203','AFW AUX BEARING TEMP HIGH');if(sim.ccw.edgTemp>95)add('W-204','EDG AUX COOLING TEMP HIGH');return a}
function alarms(detail=false){updateSim();const a=activeAlarms();if(!a.length){block(['ACTIVE ALARMS','','NONE']);return}block(['ACTIVE ALARMS','',...a.map(x=>`${x[0]}   ${x[1]}`),detail?'\nNOTE: Alarm source is not necessarily root cause.':''])}
function acceptControl(cmd,msg,fn){if(fn)fn();controls.add(cmd);controlCount++;p('COMMAND ACCEPTED: '+cmd.replace('CONTROL ','').toUpperCase(),'ok');if(msg)p(msg,'alarm');stableSince=null;return true}
function rejectControl(msg){p('COMMAND REJECTED: '+msg,'danger');return false}
function noChange(msg){p('COMMAND ACKNOWLEDGED: '+msg,'alarm');return false}
function busForAfw(w){return w==='B'?sim.electrical.busB:sim.electrical.busA}
function control(cmd){if(finished&&!isSimulation()){p('STAGE COMPLETE: CONTROL DISABLED','danger');return false}updateSim();
 if(cmd==='CONTROL REACTOR TRIP'){if(sim.reactor.tripped)return noChange('REACTOR ALREADY TRIPPED');return acceptControl(cmd,'RPS: REACTOR TRIP COMPLETE',()=>{sim.reactor.tripped=true;sim.reactor.tripAt=sim.simTime;sim.turbine.tripped=true;sim.events.reactorTrip=true})}
 if(cmd==='CONTROL RCP-A STOP'){const r=sim.rcp.A;if(['STOPPED','COASTDOWN'].includes(r.state))return noChange('RCP-A ALREADY STOPPING / STOPPED');if(r.state==='FAILED')return noChange('RCP-A FAILED / NOT RUNNING');return acceptControl(cmd,'RCP-A: COASTDOWN INITIATED',()=>{r.state='COASTDOWN';r.stopAt=sim.simTime})}
 if(cmd==='CONTROL RCP-A START'){const r=sim.rcp.A;if(['RUNNING','STARTING'].includes(r.state))return noChange('RCP-A ALREADY RUNNING / STARTING');if(r.state==='COASTDOWN')return rejectControl('RCP-A COASTDOWN IN PROGRESS');if(r.state==='FAILED')return rejectControl('RCP-A EQUIPMENT FAILURE — START UNAVAILABLE');if(sim.rcs.pressure<13)return rejectControl('RCS PRESSURE START PERMISSIVE NOT MET');return acceptControl(cmd,'RCP-A: START SEQUENCE INITIATED',()=>{r.state='STARTING'})}
 let m=cmd.match(/^CONTROL FRV-([ABC]) (OPEN|CLOSE)$/);if(m){const [,w,act]=m,f=sim.mfw.frv[w],open=act==='OPEN';if((open&&f.cmd==='OPEN')||(!open&&f.cmd==='CLOSE'))return noChange(`FRV-${w} ALREADY ${act}`);return acceptControl(cmd,`FRV-${w} COMMAND ${act}; ACTUAL RESPONSE IN PROGRESS`,()=>{f.cmd=act;f.manualOverride=true})}
 m=cmd.match(/^CONTROL AFW-([ABC]) (START|STOP)$/);if(m){const [,w,act]=m,a=sim.afw[w],start=act==='START';if(start){if(a.pump==='FAILED')return rejectControl(`AFW-${w} EQUIPMENT FAILURE`);if(busForAfw(w)<80)return rejectControl(`AFW-${w} POWER PERMISSIVE NOT MET`);if(a.pump==='RUNNING')return noChange(`AFW-${w} ALREADY RUNNING`);return acceptControl(cmd,`AFW-${w} START REQUEST`,()=>{a.pump='RUNNING'})}if(a.pump==='STOPPED'||a.pump==='STANDBY')return noChange(`AFW-${w} ALREADY STOPPED / STANDBY`);return acceptControl(cmd,`AFW-${w} STOP REQUEST`,()=>{a.pump='STOPPED'})}
 m=cmd.match(/^CONTROL AFW-VALVE-([ABC]) (OPEN|CLOSE)$/);if(m){const [,w,act]=m,a=sim.afw[w],open=act==='OPEN';if((open&&a.valveCmd==='OPEN')||(!open&&a.valveCmd==='CLOSED'))return noChange(`AFW-${w} DELIVERY VALVE ALREADY ${open?'OPEN':'CLOSED'}`);return acceptControl(cmd,`AFW-${w} DELIVERY PATH ${open?'OPENING':'CLOSING'}`,()=>{a.valveCmd=open?'OPEN':'CLOSED'})}
 if(cmd==='CONTROL STEAM-DUMP OPEN'||cmd==='CONTROL STEAM-DUMP CLOSE'){const open=cmd.endsWith('OPEN');if(open&&!sim.turbine.tripped)return rejectControl('OPEN PERMISSIVE NOT MET — TURBINE RUNNING');if((open&&sim.steamDump.cmd==='OPEN')||(!open&&sim.steamDump.cmd==='CLOSE'))return noChange(`STEAM-DUMP ALREADY ${open?'OPENING':'CLOSING'}`);return acceptControl(cmd,open?'STEAM-DUMP MANUAL OPEN REQUEST':'STEAM-DUMP MANUAL CLOSE REQUEST',()=>{sim.steamDump.cmd=open?'OPEN':'CLOSE'})}
 if(cmd==='CONTROL ATM-DUMP OPEN'||cmd==='CONTROL ATM-DUMP CLOSE'){const open=cmd.endsWith('OPEN');if(open&&!sim.turbine.tripped)return rejectControl('OPEN PERMISSIVE NOT MET — TURBINE RUNNING');if((open&&sim.atmDump.cmd==='OPEN')||(!open&&sim.atmDump.cmd==='CLOSE'))return noChange(`ATM-DUMP ALREADY ${open?'OPENING':'CLOSING'}`);return acceptControl(cmd,open?'ATMOSPHERIC HEAT-REMOVAL PATH OPENING':'ATMOSPHERIC HEAT-REMOVAL PATH CLOSING',()=>{sim.atmDump.cmd=open?'OPEN':'CLOSE'})}
 m=cmd.match(/^CONTROL EDG-([AB]) START$/);if(m){const w=m[1],e=sim.electrical[`edg${w}`];if(e.state==='FAILED')return rejectControl(`EDG-${w} EQUIPMENT FAILURE`);if(['RUNNING','CRANKING'].includes(e.state))return noChange(`EDG-${w} ALREADY RUNNING / CRANKING`);return acceptControl(cmd,`EDG-${w} START REQUEST`,()=>{e.state='CRANKING'})}
 m=cmd.match(/^CONTROL EDG-([AB])-BREAKER (OPEN|CLOSE)$/);if(m){const [,w,act]=m,e=sim.electrical[`edg${w}`],bus=w==='A'?sim.electrical.busA:sim.electrical.busB,close=act==='CLOSE';if(!close){if(e.breaker==='OPEN')return noChange(`EDG-${w} BREAKER ALREADY OPEN`);return acceptControl(cmd,`EDG-${w} BREAKER OPEN COMMAND`,()=>{e.breakerCmd='OPEN';e.breaker='OPEN';e.closeAt=null})}if(e.speed<95||e.state!=='RUNNING')return rejectControl(`EDG-${w} SPEED PERMISSIVE NOT MET`);if(sim.electrical.offsiteAvailable||bus>20)return rejectControl(`BUS-${w} ENERGIZED — CLOSE PERMISSIVE NOT MET`);if(e.breaker==='CLOSED'||e.breakerCmd==='CLOSE')return noChange(`EDG-${w} BREAKER ALREADY CLOSED / CLOSING`);return acceptControl(cmd,`EDG-${w} BREAKER CLOSE COMMAND; ACTUAL CLOSURE PENDING`,()=>{e.breakerCmd='CLOSE';e.closeAt=sim.simTime})}
 m=cmd.match(/^CONTROL SG-([ABC])-LVL DIAG$/);if(m){const name=`SG-${m[1]}-LVL`,g=sim.instruments[name];if(g.diagComplete)return noChange(`${name} DIAGNOSTIC ALREADY COMPLETE`);if(g.diagState==='RUNNING')return noChange(`${name} DIAGNOSTIC ALREADY RUNNING`);return acceptControl(cmd,`${name} CHANNEL DIAGNOSTIC STARTED`,()=>{g.diagState='RUNNING';g.diagAt=sim.simTime})}
 if(cmd==='CONTROL RCS-LETDOWN-ISO CLOSE'||cmd==='CONTROL RCS-LETDOWN-ISO OPEN'){const close=cmd.endsWith('CLOSE');if((close&&sim.letdown.iso==='CLOSED')||(!close&&sim.letdown.iso==='OPEN'))return noChange(`RCS LETDOWN ISOLATION ALREADY ${close?'CLOSED':'OPEN'}`);return acceptControl(cmd,close?'RCS LETDOWN PATH ISOLATED':'RCS LETDOWN PATH REOPENED',()=>{sim.letdown.iso=close?'CLOSED':'OPEN'})}
 m=cmd.match(/^CONTROL CCW-([AB]) (START|STOP)$/);if(m){const [,w,act]=m,c=sim.ccw[w],start=act==='START';if(start){if(c.state==='FAILED')return rejectControl(`CCW-${w} EQUIPMENT FAILURE`);if(['STARTING','RUNNING'].includes(c.state))return noChange(`CCW-${w} ALREADY STARTING / RUNNING`);return acceptControl(cmd,`CCW-${w} START SEQUENCE INITIATED`,()=>{c.state='STARTING'})}if(['STANDBY','FAILED'].includes(c.state))return noChange(`CCW-${w} ALREADY STOPPED / UNAVAILABLE`);return acceptControl(cmd,`CCW-${w} STOP REQUEST`,()=>{c.state='STANDBY';c.speed=0})}
 return rejectControl('CONTROL COMMAND NOT APPLICABLE TO CURRENT PLANT STATE')}
function commonConvergingSafe(){if(failureStateFor(sim))return false;if(sim.reactor.tripped){const afwCap=clamp(trains.reduce((a,w)=>a+sim.afw[w].flow,0)/200,0,1),steamCap=clamp(Math.max(sim.steamDump.flow,sim.atmDump.flow)/100,0,1);return Math.min(afwCap,steamCap)>=.75&&sim.rcs.tempTrend<=.005&&sim.rcs.inventory>40&&sim.rcs.pressure>12}return systemStates().primary==='NORMAL'&&systemStates().steam==='NORMAL'&&sim.rcs.tempTrend<=.005}
function baseSafeState(){if(!stage||!sim||isSimulation())return false;const o=stage.objective;
 if(o==='RCP_A_SECURED')return sim.reactor.tripped&&sim.rcp.A.state==='STOPPED'&&sim.rcp.A.speed===0&&sim.rcs.temp<=315&&commonConvergingSafe();
 if(o==='FRV_B_RECOVERED')return sim.mfw.frv.B.manualOverride&&sim.mfw.frv.B.cmd==='OPEN'&&sim.sg.B.level>=45&&sim.sg.B.level<=62&&sim.sg.B.trend>=-.01&&commonConvergingSafe();
 if(o==='STEAM_DUMP_ESTABLISHED')return sim.steamDump.cmd==='OPEN'&&sim.steamDump.actual>=80&&sim.condenser.available&&sim.rcs.temp<=315&&commonConvergingSafe();
 if(o==='ATM_DUMP_ESTABLISHED')return sim.atmDump.cmd==='OPEN'&&sim.atmDump.actual>=80&&sim.rcs.temp<=315&&commonConvergingSafe();
 if(o==='SAFETY_BUSES_RESTORED')return sim.electrical.busA>=95&&sim.electrical.busB>=95&&sim.electrical.edgA.breaker==='CLOSED'&&sim.electrical.edgB.breaker==='CLOSED'&&commonConvergingSafe();
 if(o==='AFW_B_DELIVERY_RESTORED')return sim.reactor.tripped&&sim.afw.B.valveCmd==='OPEN'&&sim.afw.B.flow>=80&&trains.reduce((a,w)=>a+sim.afw[w].flow,0)>=200&&sim.sg.B.level>=45&&commonConvergingSafe();
 if(o==='INSTRUMENT_FAULT_REPORTED'){const g=sim.instruments['SG-B-LVL'];return g.reported.has('SG-B-LVL-CH1')&&sim.sg.B.level>=50&&sim.sg.B.level<=60}
 if(o==='POST_TRIP_CONVERGENCE')return sim.reactor.tripped&&currentDecay()<5&&sim.rcs.temp<312&&sim.rcs.tempTrend<=0&&commonConvergingSafe();
 if(o==='RCS_LEAK_ISOLATED')return sim.letdown.iso==='CLOSED'&&sim.rcs.inventory>=70&&sim.rcs.pressure>=14.5&&sim.rcs.pzrLevel>=40&&commonConvergingSafe();
 if(o==='CCW_RESTORED')return sim.ccw.B.state==='RUNNING'&&sim.ccw.flow>=90&&sim.ccw.temp<=45&&sim.ccw.rcpBearing<=90&&sim.ccw.afwBearing<=90&&(!sim.reactor.tripped||commonConvergingSafe());return false}
function failureState(){return failureStateFor(sim)}
function failureCause(){return failureCauseFor(sim)}
function stableFor(){return stableSince===null?0:Math.max(0,sim.simTime-stableSince)}
function checkClear(){if(finished||isSimulation())return;const safe=baseSafeState();if(debugLogEnabled&&debugLogLastSafe!==safe){debugLogAdd(`SAFE BASE ${debugLogLastSafe?'YES':'NO'} -> ${safe?'YES':'NO'}`);debugLogLastSafe=safe}if(safe){if(stableSince===null){stableSince=sim.simTime;debugLogAdd('STABLE TIMER START')}}else if(stableSince!==null){debugLogAdd('STABLE TIMER RESET');stableSince=null}if(stableFor()>=stage.stable)finish('clear')}
function finish(reason){if(finished)return;updateSim();const clear=reason==='clear',timeout=reason==='timeout';debugLogAdd(clear?'RESULT CLEAR':timeout?'RESULT TIME LIMIT EXCEEDED':`RESULT PLANT FAILURE: ${failureCause()}`);finishAt=Date.now();finished=true;if(timer)clearInterval(timer);updateTimeStatus();clearTutorialUI();const banner=clear?'=== CLEAR ===':timeout?'=== TIME LIMIT EXCEEDED ===':'=== PLANT FAILURE ===';p('');p(banner,clear?'ok':'danger');if(!clear&&!timeout)p(`CAUSE: ${failureCause()}`,'danger');rightTitle.textContent=clear?'RESULT // CLEAR':timeout?'RESULT // TIME LIMIT':'RESULT // PLANT FAILURE';right.className='right-body';const tutorialDone=isTutorial()&&clear,title=tutorialDone?'TUTORIAL COMPLETE':clear?'STAGE CLEAR':timeout?'TIME LIMIT EXCEEDED':'PLANT FAILURE',note=timeout?'PLANT NOT RESTORED WITHIN ALLOWABLE TIME':tutorialDone?'BASIC OPERATION / MANUAL WORKFLOW COMPLETE':clear?'PLANT RESTORED / CONDITION RESOLVED':`PLANT SAFETY LIMIT EXCEEDED<br>CAUSE: ${failureCause()}`;right.innerHTML=`<div class="result"><h2>${title}</h2><p>${note}<br>${stageLabel()}<br>PLANT ELAPSED ${fmtPlantClock(sim.simTime)}<br>CONTROL ACTIONS ${controlCount}</p><button id="retry">RETRY</button><button id="sel">STAGE SELECT</button></div>`;right.querySelector('#retry').onclick=()=>isTutorial()?startTutorial():startStage(stage,mode);right.querySelector('#sel').onclick=showSelect}
function tick(){if(!stage||finished)return;updateSim();if(isSimulation()){if(failureState()&&!simulationFailureLatched){simulationFailureLatched=true;p('');p('=== PLANT FAILURE CONDITION ===','danger');p(`CAUSE: ${failureCause()}`,'danger');p('SIMULATION CONTINUES — TYPE RESET TO RESTORE NORMAL STATE','alarm');debugLogAdd(`SIMULATION FAILURE CONDITION: ${failureCause()}`)}return}if(failureState()){finish('failure');return}if(!isTutorial()&&timeLimitRemaining()<=0){finish('timeout');return}checkClear()}
function debugExtra(){return [`RCS TEMP      ${sim.rcs.temp.toFixed(1)} C`,`RCS PRESS     ${sim.rcs.pressure.toFixed(2)} MPa`,`RCS INVENTORY ${sim.rcs.inventory.toFixed(1)} %`,`SG A/B/C      ${sim.sg.A.level.toFixed(1)} / ${sim.sg.B.level.toFixed(1)} / ${sim.sg.C.level.toFixed(1)} %`,`AFW A/B/C     ${sim.afw.A.flow.toFixed(0)} / ${sim.afw.B.flow.toFixed(0)} / ${sim.afw.C.flow.toFixed(0)} %`,`BUS A/B       ${sim.electrical.busA.toFixed(0)} / ${sim.electrical.busB.toFixed(0)} %`,`CCW FLOW      ${sim.ccw.flow.toFixed(1)} %`]}
function clearTutorialUI(){if(tutorialCoach){tutorialCoach.remove();tutorialCoach=null}if(tutorialHighlight){tutorialHighlight.classList.remove('tutorial-highlight');tutorialHighlight=null}}
function tutorialTarget(which){if(!which)return null;if(which==='time')return timeStatus;if(which==='terminal')return document.querySelector('.terminal-panel');if(which==='manual')return document.querySelector('.right-panel');if(which==='input')return input;if(which.startsWith('selector:'))return document.querySelector(which.slice(9));return null}
function showTutorial(text,target=null,button=false){clearTutorialUI();const el=document.createElement('div');el.className='tutorial-coach';el.innerHTML=`<div class="tutorial-label">TUTORIAL</div><div class="tutorial-text"></div>${button?'<button type="button">次へ</button>':''}`;el.querySelector('.tutorial-text').textContent=text;document.body.appendChild(el);tutorialCoach=el;const t=tutorialTarget(target);if(t){t.classList.add('tutorial-highlight');tutorialHighlight=t;if(typeof t.scrollIntoView==='function'&&target?.startsWith?.('selector:'))t.scrollIntoView({block:'nearest',inline:'nearest'})}if(button)el.querySelector('button').onclick=()=>tutorialNext()}
function tutorialJump(nextStep){tutorialStep=nextStep-1;tutorialNext()}
function tutorialNext(){if(!isTutorial())return;tutorialStep++;
 if(tutorialStep===1)showTutorial('左がターミナル、右が運転・保守マニュアルです。異常を調査し、必要な設備だけを操作して安全側へ収束させます。','terminal',true);
 else if(tutorialStep===2)showTutorial('PLANT TIME は現在の設備状態と因果関係から予測した物理的な猶予です。TIME LIMIT は本編で共通8時間の復旧・解明期限です。','time',true);
 else if(tutorialStep===3)showTutorial('まず全体状態を確認します。入力欄へ STATUS と入力して実行してください。','input');
 else if(tutorialStep===4)showTutorial('PRIMARY が WARNING です。今度はマニュアルを使います。右上の「索引」ボタンを押してください。','selector:[data-nav="index"]');
 else if(tutorialStep===5)showTutorial('索引から「RCP（原子炉冷却材ポンプ）」を開いてください。','selector:[data-page="rcp"]');
 else if(tutorialStep===6)showTutorial('STATUS PRIMARY を実行してください。直接入力しても、強調されたマニュアルのボタンをクリックして入力欄へ挿入しても構いません。','selector:[data-command="STATUS PRIMARY"]');
 else if(tutorialStep===7)showTutorial('次はRCP-Aを個別に調べます。READ RCP-A を実行してください。直接入力でも、マニュアルのボタンからでも進めます。','selector:[data-command="READ RCP-A"]');
 else if(tutorialStep===8)showTutorial('警報も調査材料です。ALARM を実行してみてください。','input');
 else if(tutorialStep===9)showTutorial('次の操作はCONTROL資料から探します。まず「索引」ボタンを押してください。','selector:[data-nav="index"]');
 else if(tutorialStep===10)showTutorial('索引から「コマンド — CONTROL」を開いてください。','selector:[data-page="cmd-control"]');
 else if(tutorialStep===11)showTutorial('CONTROL REACTOR TRIP を実行してください。直接入力でも、強調されたボタンをクリックして入力欄へ挿入しても構いません。','selector:[data-command="CONTROL REACTOR TRIP"]');
 else if(tutorialStep===12)showTutorial('続いて故障したRCP-Aを停止します。CONTROL RCP-A STOP を実行してください。入力方法はどちらでも構いません。','selector:[data-command="CONTROL RCP-A STOP"]');
 else if(tutorialStep===13)showTutorial('操作は完了です。STATUS / READで設備のACTUAL状態と温度が安全側へ収束するか確認してください。↑キーを押すと、以前に実行したコマンドを呼び出せます。','time')}
function tutorialOnCommandExecuted(up){if(!isTutorial())return;if(tutorialStep===3&&up==='STATUS')tutorialJump(4);else if(tutorialStep===6&&up==='STATUS PRIMARY')tutorialJump(7);else if(tutorialStep===7&&up==='READ RCP-A')tutorialJump(8);else if(tutorialStep===8&&up==='ALARM')tutorialJump(9);else if(tutorialStep===11&&up==='CONTROL REACTOR TRIP')tutorialJump(12);else if(tutorialStep===12&&up==='CONTROL RCP-A STOP')tutorialJump(13)}
function tutorialHooks(){return {onPage(id){if(!isTutorial())return;if(tutorialStep===4&&id==='index')tutorialJump(5);else if(tutorialStep===5&&id==='rcp')tutorialJump(6);else if(tutorialStep===9&&id==='index')tutorialJump(10);else if(tutorialStep===10&&id==='cmd-control')tutorialJump(11)},onCommand(){}}}
function insert(cmd){input.value=cmd;input.focus();input.setSelectionRange(input.value.length,input.value.length)}
function showSelect(){clearTutorialUI();mode='stage';stage=null;finished=false;finishAt=0;sim=null;stableSince=null;controlCount=0;lastCommand=null;lastCommandAt=null;lastControl=null;lastControlAt=null;if(timer)clearInterval(timer);updateTimeStatus();returnBtn.classList.add('hidden');rightTitle.textContent='STAGE SELECT';right.className='right-body';right.innerHTML='<div class="stage-select-head"><div><h1>SELECT MODE / STAGE</h1></div></div><div id="modeGrid" class="stage-grid mode-grid"></div><div id="stageGrid" class="stage-grid"></div>';const mg=right.querySelector('#modeGrid');[['TUTORIAL',()=>startTutorial()],['SIMULATION',()=>startSimulation()]].forEach(([name,fn])=>{const d=document.createElement('div');d.className='stage-card special-card';d.innerHTML=`<h3>${name}</h3><button>START</button>`;d.querySelector('button').onclick=fn;mg.appendChild(d)});const grid=right.querySelector('#stageGrid');STAGES.forEach(s=>{const d=document.createElement('div');d.className='stage-card';d.innerHTML=`<h3>STAGE-${s.id}</h3><button>START</button>`;d.querySelector('button').onclick=()=>startStage(s,'stage');grid.appendChild(d)});out.innerHTML='';p('TERMINAL READY');p('SELECT TUTORIAL / SIMULATION / STAGE FROM THE RIGHT PANEL.')}
function startStage(s,newMode='stage'){clearTutorialUI();mode=newMode;stage=s;startAt=Date.now();finishAt=0;finished=false;controls=new Set();controlCount=0;stableSince=null;lastCommand=null;lastCommandAt=null;lastControl=null;lastControlAt=null;simulationFailureLatched=false;sim=makeNormalPlant(s.conditions||{});debugLog=[];debugLogNextSample=5;debugLogLastSafe=baseSafeState();debugLogAdd(`${stageLabel()} START`);out.innerHTML='';returnBtn.classList.remove('hidden');rightTitle.textContent=`OPERATING & MAINTENANCE MANUAL // ${stageLabel()}`;Manual.render(right,insert,'cover',isTutorial()?tutorialHooks():null);p('!! EVENT !!','alarm');p('');p(`${stageLabel()} INITIALIZED`);p(s.brief,'alarm');p('');updateTimeStatus();if(timer)clearInterval(timer);timer=setInterval(tick,1000);if(isTutorial()){tutorialStep=0;showTutorial('このチュートリアルでは、実際の異常を解決しながらゲームの流れ・画面・マニュアルの使い方を確認します。','terminal',true)}}
function startTutorial(){const s={...STAGES[0],conditions:{...STAGES[0].conditions,tutorialMode:true}};startStage(s,'tutorial')}
function startSimulation(){startStage({id:0,difficulty:'TRAINING',devTitle:'正常運転シミュレーション',brief:'NORMAL OPERATION — FREE CONTROL TEST',stable:0,conditions:{},objective:null},'simulation');p('SIMULATION MODE: NORMAL PLANT / NO CLEAR / NO TIME LIMIT');p('TYPE RESET TO RESTORE NORMAL INITIAL CONDITIONS.')}
function resetSimulation(){if(!isSimulation())return false;sim=makeNormalPlant({});stableSince=null;simulationFailureLatched=false;debugLogAdd('SIMULATION RESET');p('SIMULATION RESET: NORMAL OPERATING STATE RESTORED','ok');updateTimeStatus();return true}
function reportDevice(up){const dev=up.replace(/^REPORT\s+/,'');for(const g of Object.values(sim.instruments)){if(g.confirmedFailed===dev){if(g.reported.has(dev)){p(`REPORT ACKNOWLEDGED: ${dev} ALREADY REPORTED`,'alarm');return}g.reported.add(dev);const n=Number(dev.at(-1));g.channels[n].quality='OUT OF SERVICE';stableSince=null;p('FAULT REPORT ACCEPTED','ok');block([`${dev} MARKED OUT OF SERVICE`,'VALID CHANNELS: '+[1,2,3].filter(x=>x!==n).map(x=>`CH${x}`).join(' / ')],'alarm');return}}p('REPORT REJECTED: DEVICE NOT CONFIRMED FAILED','danger')}
function debugExtraLine(){return debugExtra()}
function execute(raw){const text=raw.trim();if(!text)return;cmdHistory.push(text);histPos=cmdHistory.length;p('> '+text);const up=text.toUpperCase(),a=up.split(/\s+/);
 if(up==='DEBUG LOG ON'){debugLogEnabled=true;if(stage){debugLog=[];debugLogNextSample=Math.ceil(sim.simTime/5)*5;if(debugLogNextSample<=sim.simTime)debugLogNextSample+=5;debugLogLastSafe=baseSafeState();debugLogAdd('DEBUG LOG ON');debugSnapshot()}block(['DEBUG LOG','STATE            ON','SAMPLE INTERVAL  5 plant min','EVENT CAPTURE    ON']);return}
 if(up==='DEBUG LOG OFF'){debugLogAdd('DEBUG LOG OFF');debugLogEnabled=false;block(['DEBUG LOG','STATE            OFF']);return}
 if(up==='DEBUG LOG CLEAR'){debugLog=[];if(stage)debugLogAdd('DEBUG LOG CLEARED');block(['DEBUG LOG','LOG CLEARED']);return}
 if(up==='DEBUG LOG SHOW'){if(!debugLog.length){block(['DEBUG LOG','NO LOG DATA']);return}block(['DEBUG LOG',...debugLog,'END DEBUG LOG']);return}
 if(up==='DEBUG STATE'){if(stage)updateSim();block(['DEBUG STATE',`STAGE         ${stageLabel()}`,`PLANT ELAPSED ${stage?fmtPlantClock(sim.simTime,true):'00:00:00'}`,`PLANT TIME    ${stage?fmtPlantClock(plantMarginMinutes()):'--:--'}`,`TIME LIMIT    ${stage?fmtPlantClock(timeLimitRemaining()):'--:--'}`,`CONTROL ACT   ${controlCount}`,`SAFE BASE     ${stage&&baseSafeState()?'YES':'NO'}`,`STABLE FOR   ${stage?stableFor().toFixed(1):'0.0'} / ${stage?.stable??0} plant min`,...(stage?debugExtraLine():[])]);return}
 if(up==='DEBUG TIME'){if(stage)updateSim();const now=stage?sim.simTime:0;block(['DEBUG TIME',`PLANT ELAPSED   ${fmtPlantClock(now,true)}`,`PLANT TIME      ${stage?fmtPlantClock(plantMarginMinutes()):'--:--'}`,`TIME LIMIT      ${stage?fmtPlantClock(timeLimitRemaining()):'--:--'}`,`LAST COMMAND    ${lastCommand??'NONE'}`,`LAST COMMAND AT ${lastCommandAt===null?'--':fmtPlantClock(lastCommandAt,true)}`,`LAST CONTROL    ${lastControl??'NONE'}`,`LAST CONTROL AT ${lastControlAt===null?'--':fmtPlantClock(lastControlAt,true)}`]);return}
 if(up==='DEBUG SENSORS'){if(!stage){p('NO ACTIVE STAGE','danger');return}const lines=['DEBUG SENSORS'];for(const [name,g] of Object.entries(sim.instruments))lines.push(`${name} ${g.channels[1].value.toFixed(1)} / ${g.channels[2].value.toFixed(1)} / ${g.channels[3].value.toFixed(1)} | ${g.diagState}`);block(lines);return}
 if(up==='DEBUG PROTECTION'){block(['DEBUG PROTECTION',stage&&sim.reactor.tripped?'RPS TRIP COMPLETE / POST-TRIP LOGIC ACTIVE':'RPS STANDBY']);return}
 if(/^STAGE-(?:[1-9]|10)$/.test(up)){startStage(STAGES[Number(up.split('-')[1])-1],'stage');return}if(up==='TUTORIAL'){startTutorial();return}if(up==='SIMULATION'){startSimulation();return}
 if(stage){updateSim();lastCommand=up;lastCommandAt=sim.simTime;if(a[0]==='CONTROL'){lastControl=up;lastControlAt=lastCommandAt}tutorialOnCommandExecuted(up)}
 if(a[0]==='REPORT'){if(!stage){p('NO ACTIVE STAGE','danger');return}reportDevice(up);return}
 if(up==='CLEAR'){out.innerHTML='';return}
 if(up==='RESET'){if(resetSimulation())return;p('RESET IS AVAILABLE IN SIMULATION MODE ONLY','danger');return}
 if(up==='HELP'){block(['COMMAND FAMILIES','STATUS [SYSTEM]','READ <DEVICE>','HISTORY <DEVICE> <PARAMETER>','ALARM [DETAIL]','CONTROL <DEVICE> <ACTION>','CONTROL <INSTRUMENT> DIAG','CLEAR',isSimulation()?'RESET':'']);return}
 if(!stage){p('NO ACTIVE STAGE','danger');return}
 if(a[0]==='STATUS'){status((a[1]||'').toLowerCase());return}if(a[0]==='READ'){read(a.slice(1).join('-'));return}if(a[0]==='HISTORY'){historyCmd(a[1],a[2]||'');return}if(a[0]==='ALARM'){alarms(a[1]==='DETAIL');return}if(a[0]==='CONTROL'){control(up);return}p('UNKNOWN COMMAND. See COMMAND REFERENCE in the manual.','danger')}
document.getElementById('executeBtn').onclick=()=>{execute(input.value);input.value=''};input.onkeydown=e=>{if(e.key==='Enter'){execute(input.value);input.value=''}else if(e.key==='ArrowUp'){if(cmdHistory.length){histPos=Math.max(0,histPos-1);input.value=cmdHistory[histPos]||'';e.preventDefault()}}else if(e.key==='ArrowDown'){histPos=Math.min(cmdHistory.length,histPos+1);input.value=cmdHistory[histPos]||'';e.preventDefault()}};returnBtn.onclick=showSelect;showSelect();
})();
